### ISSUE TITLE
rr doesn't process all heap updates correctly

### ISSUE THREAD

**Issue by joneschrisg** [rr-debugger/rr#1113]
Discovered while working on #603.  Now that we're not re-`exec()`ing the replayer process on restarts, the initial tracee forks into whatever random address space rr has at the time of restart.  In the test I'm debugging, the bottom of the vm looks like

<pre>
081c2000-081cc000 rw-p 00179000 fd:02 3539042                            /home/cjones/rr/obj/bin/rr
081cc000-082cf000 rw-p 00000000 00:00 0 
09120000-09141000 rw-p 00000000 00:00 0                                  [heap]
09141000-09161000 rw-p 00000000 00:00 0                                  [heap]
4cee1000-4cf00000 r-xp 00000000 fd:00 1315350                            /usr/lib/ld-2.18.so
</pre>

Several things here that would confuse our vm tracking code
- a non-heap region has been mapped just after the data segment. rr doesn't know to update the program break if this happens.
- the heap isn't contiguous.  Presumably part of it has been unmapped.  (Perhaps glibc's memory allocator has gotten smarter?)  rr assumes a contiguous heap.
- the heap isn't adjacent to the last non-heap page.  It could be that it was originally adjacent, but then the adjacent part was unmapped.

We've apparently been able to get away with this for so long because FF uses jemalloc, which doesn't touch the vm heap.

We need to support this eventually, but for #603 I might hack in a temporary workaround that skips inferring the vm for non-verified processes (initial rr fork child).

**Comment by Keno** [comment]
There've been a bunch of fixes in this area. Without a full reproducer it's hard to say that this particular issue is fixed, but if anybody runs into it, that could be a new issue.
