### ISSUE TITLE
Get Jenkins to set project status, do builds for pull requests, remove Travis

### ISSUE THREAD

**Issue by luser** [rr-debugger/rr#1468]
I stood up a Jenkins instance that's doing builds + tests for master. It needs a little more fiddling to be comparable to what Travis gives us:
- Set project status
- Build pull requests

Once we get those working we can remove Travis.

**Comment by GitMensch** [comment]
Travis is not used anymore 85a767100957e31b61ce4e8227c22ec43ddbcf98 (since 2022), is this issue going anywhere or should it be closed as unplanned?

**Comment by rocallahan** [comment]
Yep
