### ISSUE TITLE
terminate called after throwing an instance of 'std::domain_error'

### ISSUE THREAD

**Issue by Hassan-Ahmadi** [rr-debugger/rr#1685]
When I'm trying to run our project , which is a large multi-thread C++ project, it stops and gives this error :
terminate called after throwing an instance of 'std::domain_error'
what(): Thread::wait failed. Because it was not started.

**Comment by rocallahan** [comment]
It's hard to tell, but this *could* be an actual bug in your project exposed by rr's altered scheduling. You should be able to `rr replay` to debug the bug.

**Comment by rocallahan** [comment]
So, I suggest using `rr replay` to try to find out why this is happening in your code.

**Comment by HassanRBT** [comment]
Thanks for your attention and solution, I'm still working on it with rr replay.

**Comment by GitMensch** [comment]
I guess this one may be closed?

**Comment by rocallahan** [comment]
Sure.
