### ISSUE TITLE
Recording WINE is slow

### ISSUE THREAD

**Issue by Keno** [rr-debugger/rr#1778]
Continuing from our IRC conversation, there is significant overhead to recording WINE. E.g.:

```
$ time wineconsole ./usr/bin/julia.exe -e 'quit()'
real    0m0.976s
user    0m0.006s
sys 0m0.010s

$ time ~/rr-build/bin/rr record wineconsole ./usr/bin/julia.exe -e 'quit()'
real    0m42.874s
user    0m32.998s
sys 0m10.637s
```
#1777 has helped some, but unfortunately this is after (before it was 2x this). Most of the time is spent in rr. This workload appears notable in that it frequently descheds in `read` for synchronization purposes (requests made to the `wineserver`).

A flamegraph of the whole execution tree is available here: 
https://gist.github.com/Keno/c1ec0b7f22ccb585d378ddf0e03cd426

**Comment by rocallahan** [comment]
Simple ping-pong testcase: https://gist.github.com/rocallahan/fec1dcd017d1bb3fcb5e29ba0ed70b15

````
[roc@glory src]$ time ~/tmp/test
real	0m0.500s
user	0m0.017s
sys	0m0.612s
[roc@glory src]$ time taskset 1 ~/tmp/test
real	0m0.248s
user	0m0.028s
sys	0m0.220s
[roc@glory src]$ time rr record ~/tmp/test
real	0m55.117s
user	0m34.208s
sys	0m15.618s
````

**Comment by rocallahan** [comment]
````
[roc@glory src]$ time rr record -n ~/tmp/test
real	0m29.472s
user	0m20.507s
sys	0m7.613s
````
I expect this kind of context-switch-dominated test to be bad. But not this bad...

**Comment by rocallahan** [comment]
Those were with a debug rr build. With an opt build:
````
[roc@glory src]$ time rr record ~/tmp/test
real	0m20.520s
user	0m8.752s
sys	0m9.723s
[roc@glory src]$ time rr record -n ~/tmp/test
real	0m12.579s
user	0m6.076s
sys	0m6.021s
````

**Comment by Keno** [comment]
Yeah, since this spends so much time in rr optimizations make a huge difference. There's some more things we can do to make rr itself faster (not descheduling performance counters, avoiding syscalls if we can, etc.), but seems like the original design was really trying to avoid having to do that ;).

**Comment by rocallahan** [comment]
Yeah, up until now we've been able to get good performance on workloads we care about just by reducing the number of context switches to rr. But when the tracee itself is dominated by context switches, there's no way to avoid context switching to rr. At least, not without extraordinary changes to the way rr works.

**Comment by rocallahan** [comment]
I'd accept patches to improve this benchmark, but I don't see any incredibly low-hanging fruit, and to be honest I have other priorities at the moment. Most applications don't context-switch this badly because that's kinda bad for performance in general. I guess Wine is kind of constrained by the need to emulate the Windows kernel.

**Comment by Keno** [comment]
> I'd accept patches to improve this benchmark

I'll do some benchmarking tomorrow and see what I can do.

**Comment by rocallahan** [comment]
I think avoiding the full perf-counter resets would be good. We never got to the bottom of why that was necessary; hopefully it was an old kernel bug that we can just ignore now.

You could look at `Task::resume_execution` and the `waitpid(WNOHANG)` we do there; maybe you can figure out a better way to address the problem described in the comment.

Just running `strace` on rr will probably show a number of syscalls that can be optimized out with better caching.

**Comment by Keno** [comment]
> I think avoiding the full perf-counter resets would be good. We never got to the bottom of why that was necessary; hopefully it was an old kernel bug that we can just ignore now.

Yes, it's a kernel bug, but IIRC it was only fixed recently, I want to say somewhere around 3.17, certainly after 3.11 but before 4.7 since that's the versions I looked at. Still, we can avoid the reset on on new-enough kernels.

**Comment by Keno** [comment]
> You could look at Task::resume_execution and the waitpid(WNOHANG) we do there; maybe you can figure out a better way to address the problem described in the comment.

Is the primary problem the robust futex handling? If so what is wrong with the following:
- If we detect that this race happened (because the tracee died without us having seen the exit event), wait until we're sure the kernel is done with the process and has applied any necessary OWNER_DIED bits
- During replay, when we get to the exit event, we should now have the futex list (since we decide when to exit), so we should be able to apply the OWNER_DIED bits.

I.e. the suggestion is moving the behavior of record_robust_futex_changes from record-time to replay time and letting the kernel take care of it at record-time. Please poke holes in this design ;)

**Comment by rocallahan** [comment]
The core issue is that whenever we allow the kernel to apply the robust futex changes itself, we risk an unreplayable race between those changes and the currently recording thread. So we need to keep the current `record_robust_futex_change` path as the "normal path".

I think you're suggesting adding a backup path that we only use in case of async SIGKILL and removing the waitpid(NOHANG) in `resume_execution` so that the potential race window opens a little wider, but hopefully not enough to be a significant problem in practice. Right?

Having two different ways that the robust futex changes get applied is annoying extra complexity, but if it doesn't cause problems in practice and it lets us remove that extra `waitpid`, I'd be happy with that.

**Comment by rocallahan** [comment]
Hmmm. What if we didn't expose the tracee's robust futex list to the kernel at all, by blocking that syscall, and made rr responsible for applying those changes, synchronously after we've detected task death? That might work!

**Comment by rocallahan** [comment]
Oh, I remember why that doesn't work. It's because after task death you may have no access to the address space so you can't walk the robust futex list. (And some of them might be in shared memory so might still need to be updated.)

**Comment by rocallahan** [comment]
Another thing that might work is to start trapping SIGCHLD in rr. That has its own overheads, of course, but probably not very much and it would let us avoid a lot of waitpid(NOHANG) calls in the scheduler and in `resume_execution` here. One way to do it might be to have a dedicated thread handling SIGCHLD and storing the results in a thread-safe data structure that we can probe efficiently.

**Comment by rocallahan** [comment]
If you handle SIGCHLD on the main thread then you might have better synchronization properties. For example I think we can guarantee that upon return from a successful `waitpid`, the corresponding `SIGCHLD` will already have been delivered.

**Comment by Keno** [comment]
> The core issue is that whenever we allow the kernel to apply the robust futex changes itself, we risk an unreplayable race between those changes and the currently recording thread. So we need to keep the current record_robust_futex_change path as the "normal path".

I don't understand this race, so long as the exit event still happens (even if we accidentally continued past is). It seems like all modifications by the currently recording thread should have been done at that point. Or are you worried that we can't detect when the kernel is done applying those changes?

**Comment by rocallahan** [comment]
The latter.

E.g. suppose rr sees tracee thread T1 go into a blocking syscall, issues a`PTRACE_CONT` and schedules another task T2 via another `PTRACE_CONT`. Meanwhile T1 received `SIGKILL`, entered `do_exit`, got to the `PTRACE_EVENT_EXIT` stop, receives `PTRACE_CONT`, and continues. `do_exit` can be preempted between `ptrace_event(PTRACE_EVENT_EXIT)` and `exit_mm` (which does the robust futex updates), so we can run some arbitrary amount of T2 before T1's updates appear.

If you do a little git archaeology you can see that I actually tried emulating robust-futex handling during replay (4d9350939165a056d71a53797cd40f3a782bbc4e) but backed it out because I encountered this race issue.

**Comment by Keno** [comment]
Sorry, not quite clear on this yet. Why does T1 receive `PTRACE_CONT` when we're currently running `T2`?

> do_exit can be preempted between ptrace_event(PTRACE_EVENT_EXIT) and exit_mm (which does the robust futex updates), so we can run some arbitrary amount of T2 before T1's updates appear.

Why can't we `waitpid` for the task to exit to avoid it being pre-empted?

**Comment by rocallahan** [comment]
> Sorry, not quite clear on this yet. Why does T1 receive PTRACE_CONT when we're currently running T2?

When T1 enters a blocking syscall, we send it PTRACE_CONT so it can execute the syscall. Then we schedule another thread T2.

> Why can't we waitpid for the task to exit to avoid it being pre-empted?

Because we don't know it's exiting.

**Comment by Keno** [comment]
> When T1 enters a blocking syscall, we send it PTRACE_CONT so it can execute the syscall. Then we schedule another thread T2.

Ah, I see it's the PTRACE_CONT to continue the blocking syscall that races with the SIGKILL, got it! Thanks for explaining.

**Comment by rocallahan** [comment]
I think the SIGCHLD approach is probably the way to go. Apart from removing this waitpid(), it allows us to fix the issue in `Scheduler` where we currently probe tasks one-by-one to see if they have a status change, which is algorithmically bad.

**Comment by Keno** [comment]
I'm looking into using SIGCHLD to drive Task state transitions. Though of course that in-principle will still not fix the race condition (and furthermore it doesn't seem possible to fix the race condition in user mode - a `ptrace` flag to not PTRACE_CONT if the current stop is an exit stop would be nice). I've been thinking about how to nevertheless be able to do robust futex handling (either if the race becomes a problem in practice or should the kernel start disallowing exit events for explicit SIGKILLs - as was suggested in the recent LKML thread). It seems to me we could simply `clone(CLONE_VM)` any task that sets up a robust futex list (and not pass the robust futex list on to the kernel). We could keep that shadow task suspended until the main task exits and then do the futex processing ourselves. Since the shadow task wouldn't be in the same task group, it should be unaffected by any SIGKILLs, but would preserve the address space.

**Comment by Keno** [comment]
Also, as an optimization we could keep one such task per task group.

**Comment by rocallahan** [comment]
> It seems to me we could simply clone(CLONE_VM) any task that sets up a robust futex list (and not pass the robust futex list on to the kernel). We could keep that shadow task suspended until the main task exits and then do the futex processing ourselves.

Yes, that sounds reasonable.

> Also, as an optimization we could keep one such task per task group.

One per `AddressSpace` I think.

This task will need to have its own mem-fd. For simplicity it might be best to always create this task and route all memory access through it.

**Comment by Keno** [comment]
I have some additional performance numbers. Not descheduling perf counters makes things go about 20% faster. Using SIGCHLD makes things ~10% slower though (with essentially all the increase being kernel time) - at least in my implementation. I'm working on getting an accurate profile of where the remaining time goes, but it looks like it's getting close to the point where just raw kernel ptrace overhead is the problem - we'll see more once I have an accurate profile.

**Comment by rocallahan** [comment]
How is perf affected if you just remove the extra waitpid in `Task::resume_execution`?

**Comment by Keno** [comment]
A measurable, but not very large effect. Probably around 3% or so.

**Comment by Keno** [comment]
Ok, here's the processed profile files: https://gist.github.com/Keno/1b6f375897866dc0fd1fb6b8a7e50203. Might have to download them since the github preview does not have the interactivity to actually see what the function is. I had to split it up into multiple files because the tool I used didn't like creating these for multiple address spaces. FWIW, we're at about equal shares of time (1/3 each) between the two ping-pong processes (and their time spent in kernel space) and rr (though rr is slightly larger still 18k samples vs 15k).

**Comment by rocallahan** [comment]
I'm not very good at reading those flame graphs, but I trust your analysis :-).

It seems pretty clear that a lot of the rr overhead is due to the desched handling due to blocking syscallbuf calls. My results showed that disabling syscallbuf was a significant improvement; I guess that if we disabled syscallbuf for just the blocking read() call, the results would be even better. So if we could come up with some way to detect probable-blocking and go straight to a traced-syscall, that could be worth doing. One approach would be to do a `select` call before every `read`, but that would penalize readers who don't block. We could mitigate that with some per-fd state in `preload.c` that tracks how often reads from that fd have blocked in the past. But before going down that path, it's probably worth knowing how many reads from the wineserver fd block, and what the perf impact is of a hack that forces just those reads down a non-syscallbuf path.

**Comment by rocallahan** [comment]
Another thing that might help is that we're working on adding user-space support for CPUID faulting to Linux. Once we have that we no longer need to pin all tasks to the same CPU, and then we might be able to do something clever where tasks stick to different CPUs and we can maybe reduce the cost of context switching. Speculative.

**Comment by Keno** [comment]
Right, I agree with your assessment. On my machine disabling the syscallbuf is about 40% faster on the pingpong test (though still 30x slower than uninstrumented), so that would seem like a win if we can came up with a heuristic for when not to use the syscall buf. For fun, I reran the profile without the syscall buf. As expected all the perf related junk is gone from the profile. Interestingly, the ratios of time in rr / time in the tracee remained about the same. For the tracees, essentially all the time is in the linux scheduler. For rr it looks about the same (almost all in ptrace).

> Another thing that might help is that we're working on adding user-space support for CPUID faulting to Linux.

Awesome, I was considering writing that patch myself, but didn't quite feel like dealing with lkml review. Looking forward to having that (primarily interested in it for trace portability).

**Comment by rocallahan** [comment]
> I was considering writing that patch myself, but didn't quite feel like dealing with lkml review.

Good move. Fortunately Kyle is taking it for the team :-).

**Comment by khuey** [comment]
> >  I was considering writing that patch myself, but didn't quite feel like dealing with lkml review.

> Good move. Fortunately Kyle is taking it for the team :-).

That's one way to describe what is happening ;)

**Comment by Keno** [comment]
FWIW, here's the (not cleaned up) patch for SIGCHLD support, in case it ever becomes worth reconsidering: https://gist.github.com/Keno/a9607cb7ed8cfed880d8e7cec4b16542

**Comment by GitMensch** [comment]
Now the pending question is: Was that not cleaned patch ever cleaned and integrated? If not I suggest to assign this issue, if yes: do the happy dance and close :-)

**Comment by rocallahan** [comment]
It wasn't integrated but I don't think we want to do anything here.
