### ISSUE TITLE
What do to about timeouts on the new buildbots

### ISSUE THREAD

**Issue by Keno** [rr-debugger/rr#1963]
I've looked at the last couple of failures on the buildbots and a lot of them seem to be legitimate timeouts. I suspect what is happening is that two long-running tests get randomly assigned to the same CPU core, and the core isn't fast enough to get both done in the timeout window. Options I see
- Just raise the timeout (not ideal, because a lot of rr bugs only manifest themselves as timeouts)
- Somehow get ctest to tell rr which core to pin to
- Have the rr instances coordinate to pick cores
- Reduce parallelism when running the tests (Though I should point out that it's already only using 2/3 of the KNL because of this issue).

**Comment by rocallahan** [comment]
increase the timeouts just for the longrunning tests?

**Comment by Keno** [comment]
Yeah that's an option. The main thing I don't like about that is:
- The max timeouts are already quite high (10min), so making them even higher would make the buildbot turnaround slower potentially
- Without coordination, we don't take advantage of all available CPU cores on the buildbot (this is probably just psychological - the buildbot steals cores away from the regular work on that machine while it's running, so I feel like it should be using it ;)).

**Comment by Keno** [comment]
I suppose another option is just to apply @khuey's kernel patch and stop pinning cores.

**Comment by rocallahan** [comment]
That's definitely the long-term solution. Though longer-term than I was hoping! Maybe it's not worth doing anything complicated and just increase the timeouts until we can stop pinning?

**Comment by Keno** [comment]
> That's definitely the long-term solution.

I have no problem patching the kernel on these machines if we want to apply @khuey's rr patch. But yeah, I just increase the timeouts I guess.

**Comment by Keno** [comment]
Hmm https://ci.rr-project.org/#/builders/3/builds/28/steps/9/logs/stdio looks like a real timeout, but I just timed that test and it took about 6 secs.
