### ISSUE TITLE
Intermittent test failure in `daemon_read`

### ISSUE THREAD

**Issue by rocallahan** [rr-debugger/rr#1987]
I've seen this on and off. It just happened on `ci.rr-project.org`. Relevant log: https://ci.rr-project.org/#/builders/2/builds/142/steps/7/logs/stdio

**Comment by rocallahan** [comment]
Unfortunately `test-monitor` doesn't show us the state of the daemon child because it has become a child of pid 1 (by design).

And we couldn't get a stack trace of rr because `ptrace_scope` was set to 1 on that machine. I've just fixed that, so next time...

**Comment by Keno** [comment]
I just saw another failure in daemon_read, but since the original log in this issue is gone, I'm just gonna close this and open a new issue for the new failure with the new log.
