### ISSUE TITLE
support for rr replay --tty=...

### ISSUE THREAD

**Issue by facontidavide** [rr-debugger/rr#1988]
I guess you have more pressing priorities than this one, but I am trying to integrate RR with some popular IDEs, starting with QtCreator (Eclise might be the next).

It would be helpful if we have the equivalent of the option __gdb --tty__ 

Cheers

Davide

**Comment by khuey** [comment]
Is `rr replay -o="<gdb options"` not sufficient?

**Comment by khuey** [comment]
@facontidavide?

**Comment by facontidavide** [comment]
I will test it today with QtCreator

**Comment by facontidavide** [comment]
technically this issue is solved... on the other hand, I am still failing miserably in my attemp to get __rr replay__ working with QtCreator. Thanks

**Comment by khuey** [comment]
Feel free to file more issues!

**Comment by rocallahan** [comment]
And let us know if we can help you get rr working with QtCreator.

**Comment by fredcadete** [comment]
Sorry for reviving the thread, but I am having the same issue when attempting to integrate into vim, and the following could be helpful to understand the situation.

In summary: the behavior intended by the request for `rr replay --tty=...` can't be implemented by passing options to gdb.

The intention when using gdb's `--tty` is usually to have separate windows: one for the gdb console, and another for the tracee's stdout/stderr.

With gdb, this is achievable with `gdb --tty <other_tty> --args echo hello`.
Result: `(gdb)` console is in current tty, "hello" is printed to the other tty. OK
With rr, this is not achievable. `rr record echo hello` ; `rr replay -o --tty -o <other_tty>` .
Result: `(rr)` console is in current tty, "hello" is printed to current tty and nothing is printed to the other tty. NOK - was expecting "hello" in the other tty.

IIUC this is inevitable with the current "rr gdbserver + gdb client" architceture of "rr replay". The tty redirection needs to happen on the debugging server. gdb's own `--tty` flag and `set inferior-tty` command have no effect when running on a remote target (even with gdb + gdbserver).

So this is a feature of gdb that is not available in `rr replay`. Which is a pity for some IDE integrations, like vim's `termdebug`, that are using this feature of gdb.
I see that most rr IDE integrations are using `rr replay -s` and launching their own client. So they likely sidestep this by launching `rr replay` directly with redirections for the final tty/output buffer.

**Comment by fredcadete** [comment]
😲 Thank you very much for such a response! And of course for the tool in general. It seemed amazing just from using it, and after diving a bit into the code it is even more impressive.
