### ISSUE TITLE
Support `QPassSignals`

### ISSUE THREAD

**Issue by rocallahan** [rr-debugger/rr#2175]
gdb supports `QPassSignals` as a way to tell the agent about signals that should be passed directly to the debuggee without being reported to gdb. Supporting this could greatly speed up reverse execution when many gdb-ignored signals have been delivered, e.g. `SIGSYS` in Firefox sandboxed content processes.

**Comment by JOE1994** [comment]
Seems like this issue is addressed and is ready to be closed :)
