### ISSUE TITLE
Support for FS_IOC_FIEMAP ioctl

### ISSUE THREAD

**Issue by namibj** [rr-debugger/rr#2289]
When testing https://github.com/the8472/ffcnt I encountered a panic/crash and remembering the ease of debugging with back-and-forth execution when homing into the problem site, I tried to use `rr record` on it.
Specifically `rr record ffcnt -s .` in my home folder.
The [stderr.log](https://github.com/mozilla/rr/files/2600938/stderr.log) from `rr record ffcnt -s . 2> stderr.log` speaks about `ioctl(0xc020660b)` being unknown. This is `FS_IOC_FIEMAP` according to man 2 ioctl_list.

Can't these ioctl's be added in bulk? They aren't *that* exotic and while somewhat rare, any software making use of them is probably likely to emphasize speed and we know that mindset creates code that benefits particularly much from rr as state is assumed often and checked late if ever, so rr's reverse-continue with watchpoints for a reverse-dataflow trace is very useful.

I actually tried to use bare gdb and failed to find the error in ffcnt. The best guess from that was weirdness resulting from a singleton file from chromium, judging by some strace-ing of ffcnt.

**Comment by rocallahan** [comment]
> Can't these ioctl's be added in bulk?

We like to have testcases for ioctls we add, so there is some nontrivial work per ioctl. In some cases adding a testcase is not possible (e.g. hardware that no-one has), in which case we'll make an exception.

Adding ioctl support is usually not very difficult, just a bit tedious. Maybe you could submit a PR? :-)
