### ISSUE TITLE
Use of stack in syscall hooks

### ISSUE THREAD

**Issue by Keno** [rr-debugger/rr#2603]
I was looking to doing the syscallbuf properly on aarch64 and I'm having trouble coming up with a sequence that does not require storing values on the original stack or leaving registers clobbered after the syscall. This is currently problematic because we explicitly test that syscalls work fine with a bad stack pointer. What do we want to assume about what we're allowed to clobber for the purposes of syscall patching? If we don't think we can clobber anything, the only other option I see would be to return using an extra sigreturn syscall or maybe to hide some state in the upper part of the SVE registers, which are documented to be clobbered during syscalls.

**Comment by khuey** [comment]
Can you cram whatever you need in the `preload_thread_locals` struct?

**Comment by khuey** [comment]
To elaborate slightly more: whatever it is that you think you need to leave on the original stack might be able to go in there?

**Comment by Keno** [comment]
Right, so after taking a step back, I do think we can do the return without too much difficulty by loading from `preload_thread_locals`. We don't need to do a sigreturn, that was a bit of a brain freeze on my part. For syscalls of the form
```
mov     x8, ??
svc     #0x0
```
I think we're also fine, since we can clobber x8 with the address of `preload_thread_locals` if necessary and then store anything we need there. So I think the only remaining question is what to do about generic syscalls where we don't know if there's a register we can clobber. I don't think aarch64 has any sort of indirect store instruction we could use here.

**Comment by rocallahan** [comment]
> do think we can do the return without too much difficulty by loading from preload_thread_locals

How would that work?

**Comment by Keno** [comment]
So for the case where we have `x8` to clobber initially, I think we can just have the patch be:
```
ldr x8, .+4
br x8
[jump_addr]
return_addr: ldp x7, lr, [x7]
```
With the extended jump stub being something along the lines of
```
mov preload_thread_locals, x8
stp x7, lr, [x8]
add x8, x8, #16
mov sp, x7
str x7, [x8]
add x8, x8, #8
[yada, yada, do the stack adjust]
```
and the final return being along the lines of
```
[restore everything but x7, lr]
mov preload_thread_local, x7
mov return_addr, lr
ret
```
Which leaves all the register in the correct place.

I just don't know what do to when we don't have x8.

**Comment by khuey** [comment]
What do some patterns with non-const x8 (e.g. syscall(2) presumably) look like?

**Comment by rocallahan** [comment]
I don't think I've ever seen a true non-const syscall number in any context other than `syscall()`.

Of course the compiler might move the load of `x8` around so it doesn't match simple patterns :-(.
