### ISSUE TITLE
Give rr page proper unwind info

### ISSUE THREAD

**Issue by Keno** [rr-debugger/rr#2721]
I'm seeing occasional failures in the Julia backtracing tests when running under rr which happen whenever the thread whose backtrace is being taken happens to be in the rr page. The reason for the failure is that our backtracing relies on the CFA info for unwinding (rather than the more heuristic unwinder that gdb has for example). However, the rr page does not have any unwind info, since it's not technically part of any shared library. I can hack around this by just adding an rr special case in julia's unwinder, but I figured if we ran into it others might as well, so perhaps there is a general solution on the rr side. One option is certainly `__register_frame` which is provided by the unwind library to dynamically register (e.g. JITTed) frames. However, I'm worried that mechanism would be a bit brittle since it requires the unwind library to be listening for these events (and in particular requires the unwind to be done using the system unwind library if that unwind library is the one set up to listen for such events). I think a more robust scheme would actually be to try to make the rr page part of some dynamic library that the dynamic linker knows about (since all unwind libraries know how to read the dynamic linker maps). I think a scheme that would work is:

1. Make the rr_page an ET_EXEC elf file rather than a plain binary (with an appropriate PT_LOAD to load it at the right absolute address)
2. Link librrpreload with rr_page (in the DT_NEEDED sense)
3. When the dynamic linker tries to execute the PT_LOAD command by mapping over the RR page, recognize that it is the rr page being mapped and don't clear the IS_RR_PAGE flag.

That way we can add an eh_frame section to the rr page ET_EXEC file that the dynamic linker would know about and could be accessed by any unwind library.

Thoughts? If that seems too complicated for a marginal case, I'm happy to just hack around it on our side.

**Comment by rocallahan** [comment]
To be clear, you're suggesting that we continue to map the rr page on exec as now, but the dynamic loader would *also* map the rr page. The initial map would use the correct page of the ELF file I suppose.

Sure, I guess this could work. Constructing the magical ELF file might be complex but it wouldn't interact with other complex things so I think that's not a big deal. So yeah I can imagine taking a PR for this.

**Comment by khuey** [comment]
I'm definitely not opposed to taking a PR for this but we're planning to do a release Real Soon Now (TM) and I think we'd want this to wait for the next one.

**Comment by Keno** [comment]
> To be clear, you're suggesting that we continue to map the rr page on exec as now, but the dynamic loader would _also_ map the rr page. The initial map would use the correct page of the ELF file I suppose.

That's right
