### ISSUE TITLE
Doesn't build on FreeBSD: Couldn't find linux/seccomp.h.

### ISSUE THREAD

**Issue by yurivict** [rr-debugger/rr#2743]
Can Linux-specific functionality be made conditional on a cmake variable?

gdb works on BSDs without requiring any Linux-specific functions.

**Comment by rocallahan** [comment]
rr is a lot more invasive than gdb and relies on a lot of Linux specific features. Check out https://arxiv.org/abs/1705.05937. Making rr work on FreeBSD would be a massive amount of work and probably require FreeBSD kernel changes.
