### ISSUE TITLE
No support for mutex w/ PTHREAD_PRIO_INHERIT

### ISSUE THREAD

**Issue by mdavidsaver** [rr-debugger/rr#2750]
I find that when protocol is set to `PTHREAD_PRIO_INHERIT`, `pthread_mutex_init()` will error with `EOPNOTSUPP` (95).  The same executable will succeed when run outside of RR with the same permissions.

From some digging, I think the `EOPNOTSUPP` is a translation of an `ENOSYS`, which I guess means that the Priority Inheritance futex() operation aren't currently supported through RR.

https://github.com/bminor/glibc/blob/76ea70c613cee23a1846b9605e6433c1fa8baea7/nptl/pthread_mutex_init.c#L44

**Comment by rocallahan** [comment]
That's right.

I didn't know about this glibc check. We patch out priority inheritance via `fix_mutex_kind` but apparently that's not enough to work around the problem, because this glibc check.

It's been a long time; I don't remember exactly why we didn't override `pthread_mutex_init` with `fix_mutex_kind`. I guess we should try that. Feel like trying?

**Comment by mdavidsaver** [comment]
I take it you are referring to:

https://github.com/rr-debugger/rr/blob/7c74ca16362b2711ba04acc80530bbd464dbdb98/src/preload/overrides.c#L21-L24

Without having tried, adding an override for `pthread_mutex_init()` seems straightforward enough (to the point of being almost trivial).  I wouldn't mind trying to make this change, though I don't have any special need to see my name in the RR commit history.  Where I might be tripped up is in adding test cases, if the existing coverage is not considered sufficient.

I'm attaching a short program which demonstrates the error.

```sh
$ gcc -o pthread_pi_demo -x c pthread_pi_demo.c.txt -pthread
$ ./pthread_pi_demo 
Success
$ rr record ./pthread_pi_demo 
rr: Saving execution to trace directory `/home/mdavidsaver/.local/share/rr/pthread_pi_demo-1'.
Error on line 18 : 95
```

[pthread_pi_demo.c.txt](https://github.com/rr-debugger/rr/files/5587128/pthread_pi_demo.c.txt)

**Comment by rocallahan** [comment]
Yeah a testcase is a little more work, but pretty easy to do. See commit 8abaccd83277a51c21ac27de81c8d798bcf3bdfe for an example that adds a "basic test" --- i.e. something that we just try to record and replay correctly.

**Comment by rocallahan** [comment]
Existing coverage is definitely not sufficient since the test suite passes 100% on most distros AFAIK...

**Comment by mdavidsaver** [comment]
Attempting to address with #2752

**Comment by khuey** [comment]
So I think we're good here now?

**Comment by mdavidsaver** [comment]
Yes.
