### ISSUE TITLE
Test nested_detach fails at i386 since 34c80347fe.

### ISSUE THREAD

**Issue by bernhardu** [rr-debugger/rr#2777]
Hello, after the last patch there is still a failing test nested_detach fails at i386.

Sometimes the core shows the function name _switch_stack_vsyscall and the disassembly below matches.
It looks the problem is that we put in $esp from alt_stack_nesting_level, unfortunately the thread locals page contains zeros,
therefore $esp gets a value of zero and the process crashes.

If I still let the copy happen for the thread locals page the test succeeds.
Would a change like below be acceptable?
But I cannot explain why this is not needed at x86_64.

```
$ bin/rr record bin/rr record --nested=detach bin/simple
rr: Saving execution to trace directory `/home/benutzer/.local/share/rr/rr-88'.
$
```
```
[432013.041446] rr[2221]: segfault at fffffffc ip b7ec2289 sp 00000000 error 7 in librrpreload.so[b7ec1000+8000]
[432013.041457] Code: 90 90 e8 08 00 00 00 8f 05 08 10 00 70 eb 46 89 25 08 10 00 70 ff 05 0c 10 00 70 83 3d 0c 10 00 70 01 75 06 8b 25 00 10 00 70 <ff> 35 08 10 00 70 83 04 24 04 89 3d 08 10 00 70 8b 3c 24 ff 77 fc
[432013.041463] rr[2220]: segfault at fffffffc ip b7ec2289 sp 00000000 error 7 in librrpreload.so[b7ec1000+8000]
[432013.041470] Code: 90 90 e8 08 00 00 00 8f 05 08 10 00 70 eb 46 89 25 08 10 00 70 ff 05 0c 10 00 70 83 3d 0c 10 00 70 01 75 06 8b 25 00 10 00 70 <ff> 35 08 10 00 70 83 04 24 04 89 3d 08 10 00 70 8b 3c 24 ff 77 fc
```
```
# coredumpctl gdb 2220
...
(gdb) info thread
  Id   Target Id         Frame 
* 1    LWP 2221          0xb7ec2289 in ?? ()
  2    LWP 2220          0xb7ec2289 in ?? ()
(gdb) disassemble $pc-40,$pc+20
Dump of assembler code from 0xb7ec2261 to 0xb7ec229d:
   0xb7ec2261:  call   0xb7ec226e
   0xb7ec2266:  pop    0x70001008
   0xb7ec226c:  jmp    0xb7ec22b4
   0xb7ec226e:  mov    %esp,0x70001008
   0xb7ec2274:  incl   0x7000100c
   0xb7ec227a:  cmpl   $0x1,0x7000100c
   0xb7ec2281:  jne    0xb7ec2289
   0xb7ec2283:  mov    0x70001000,%esp
=> 0xb7ec2289:  push   0x70001008
   0xb7ec228f:  addl   $0x4,(%esp)
   0xb7ec2293:  mov    %edi,0x70001008
   0xb7ec2299:  mov    (%esp),%edi
   0xb7ec229c:  push   -0x4(%edi)
End of assembler dump.
```
```patch
--- a/src/Task.cc
+++ b/src/Task.cc
@@ -3557,7 +3557,16 @@ void Task::dup_from(Task *other) {
       LOG(debug) << "Creating mapping " << km << " for " << tid;
       create_mapping(this, remote_this, km);
       LOG(debug) << "Copying mapping into " << tid;
+      bool do_copy = false;
       if (!(km.flags() & MAP_SHARED)) {
+        do_copy = true;
+      }
+#if defined(__i386__)
+      if (km.start() == PRELOAD_THREAD_LOCALS_ADDR) {
+        do_copy = true;
+      }
+#endif
+      if (do_copy) {
         copy_mem_mapping(other, this, km);
       }
     }
```

CC: @Keno

**Comment by Keno** [comment]
Yeah, we should probably recreate the thread locals page, but we should probably recreate it as MAP_PRIVATE. I agree that it should also be required on x86_64, we're probably just getting lucky with how we're entering the syscallbuf.

**Comment by bernhardu** [comment]
Thanks for having a look. If I understand you right the thread locals page is not MAP_SHARED on purpose, but until that is fixed doing the copy_mem_mapping would be the right thing to do, also on x86_64?

**Comment by bernhardu** [comment]
@Keno I could confirm that 47878cf7a fixes this issue.

(Just a small note: I tried to reproduce this issue before checking if the patch fixes it, with the VM host and guest just freshly booted up. But there it did not show up. Just after running the whole tests. There were some dmesg lines `perf: interrupt took too long (20573 > 19917), lowering kernel.perf_event_max_sample_rate to 9500` shown after starting the tests, might they be related to it, or make it more likely to happen?)

Thanks for looking into it. All tests passed now with current head de49ae507 in my i386 debian testing VM.
I guess this issue could be closed then?

**Comment by rocallahan** [comment]
Great!
