### ISSUE TITLE
32-bit rr running below 64-kernel / with 64-bit userland

### ISSUE THREAD

**Issue by bernhardu** [rr-debugger/rr#2782]
Hello, for performance reasons I lately found the cmake option `-Dforce32bit=true` which works great.
So I attempted to run also the tests found a few issues.
This [branch](https://github.com/bernhardu/rr/commits/fix-32bit-rr-under-64bit-kernel) contains some commits to avoid these failures. They also succeed on "real" 32-bit or 64-bit environments.
Is there interest to get these committed? Any comments?

**Comment by rocallahan** [comment]
Sure, submit PRs for these.

**Comment by bernhardu** [comment]
Thanks for your time, I created a first one in #2783.

**Comment by bernhardu** [comment]
Thanks for merging.
With current head 10c5146 tests are succeeding with:
* 64bit and 32bit rr below a 64bit kernel at a Ryzen 7 1700
* 32bit rr below a 32bit kernel inside a VM below a host with a 64bit kernel at an i5-4210U.
I hope its ok if I close this issue?

**Comment by rocallahan** [comment]
> I hope its ok if I close this issue?

Sure, let's do that. Thanks for all this!
