### ISSUE TITLE
Add privacy health warning to `rr pack`

### ISSUE THREAD

**Issue by joechrisellis** [rr-debugger/rr#2819]
Hi guys!

First off: thank you for `rr`! It's an incredibly useful tool and a pleasure to use.

I have been thinking today about the privacy implications of sharing `rr` traces. If `rr record` is not used in a sanitised environment it is quite probable for sensitive information to be captured in the trace. I can foresee this compromising privacy in some quite subtle ways -- in essence, any file read by the debugee could be captured in the trace. @Keno's excellent blog post captures most of my thoughts on the matter ([here](https://julialang.org/blog/2020/05/rr/#a_word_on_privacy)).

`rr pack` reads:

```
Eliminates duplicate files in the trace directory, and copies files into
the trace directory as necessary to ensure that all needed files are in
the trace directory and none of them are links to files outside the
trace directory. This makes the trace directory independent of changes
to other files and ready to be transported elsewhere (e.g. by packaging
it into a ZIP or tar archive).
```

Since its primary use case seems to be for sharing/transporting traces, maybe it would be a good to inform the user that the trace could contain sensitive information that they might want to keep private. I'm not 100% sure how this would look in practice -- perhaps a one-time warning, a bit like the Linux `sudo` 'lecture'?

What do you think? Thanks again for all your work on `rr`! 😄

**Comment by rocallahan** [comment]
That's a good point. I added d40b4df823273f5db7124d65b858d294c1c2fad6. It's difficult to craft perfect text here.
