### ISSUE TITLE
Test failures with Threadripper 3975wx

### ISSUE THREAD

**Issue by mystor** [rr-debugger/rr#2826]
Threadripper 3975wx

The exact set of test failures varies a bit run-to-run, but these two seem to fail fairly reliably:
```
105 - detach_threads-no-syscallbuf (Failed)
579 - setuid-no-syscallbuf (Failed)
```

[rr_test_verbose_log.txt](https://github.com/rr-debugger/rr/files/6127587/rr_test_verbose_log.txt)

Let me know if there are any other files which would be useful.

**Comment by rocallahan** [comment]
Looks like the setuid tests are diverging, which is worrying.

If you do `_RR_TRACE_DIR=/tmp/rr-test-setuid-uAEzsgFkv rr replay -a` does it fail?

Can you `rr pack /tmp/rr-test-setuid-uAEzsgFkv/*-0` and then tar that up and send it to me?

**Comment by mystor** [comment]
> Looks like the setuid tests are diverging, which is worrying.
> 
> If you do `_RR_TRACE_DIR=/tmp/rr-test-setuid-uAEzsgFkv rr replay -a` does it fail?

Yup, that fails with an rr assertion failure.

> Can you `rr pack /tmp/rr-test-setuid-uAEzsgFkv/*-0` and then tar that up and send it to me?

I DM-ed it to you on matrix. Let me know if you need anything else

**Comment by rocallahan** [comment]
This is caused by an RDRAND executing at address 0x7f4eac348c33, which is in /usr/lib/x86_64-linux-gnu/libnss_systemd.so.2.  So you need a version of systemd with https://github.com/systemd/systemd/pull/17115.

**Comment by rocallahan** [comment]
The other intermittent failures might be interesting to look into but probably not worth your time. Nothing here is going to affect Firefox I guess. So I suggest not taking further action here.
