### ISSUE TITLE
when trying to reverse step after a segfault, I receive "target multithread does not support this command"

### ISSUE THREAD

**Issue by jkordani** [rr-debugger/rr#2831]
rr version 5.4.0
gdb 10
gdb with -i=mi in gud-mode
set annotate 1
set filename-display absolute
set target-async off
set non-stop off
target extended-remote ip:port.
hit run watch the segfault then try to reverse step

**Comment by khuey** [comment]
rr doesn't support non-stop mode (nor would it make sense to) which is probably the cause of that error message.

**Comment by jkordani** [comment]
I think I have to set these before I attach, and rr replay -s kept closing and I missed a window or something
