### ISSUE TITLE
trace file not readable

### ISSUE THREAD

**Issue by jkordani** [rr-debugger/rr#2832]
I've recorded a session with rr record, but when I go to replay it I get trace file is not readable.  The trace file path is actually the full path of my binary with the addition of /version (note the slash).  It doesn't seem to exist.

In general, how does rr know where to look for the latest recording of a binary?

**Comment by khuey** [comment]
If you don't give it a trace argument, the symlink `~/.local/share/rr/latest-trace` which points to the most recent trace (recorded without _RR_TRACE_DIR set in the environment) is used.

If you do give `rr replay` a trace argument, you want to point it at the directory containing the `version` file.
