### ISSUE TITLE
Possible to have rr work with  /proc/sys/kernel/perf_event_paranoid == 2?

### ISSUE THREAD

**Issue by wcohen** [rr-debugger/rr#2835]
There are a number of checks that perf_event_paranoid <= 1 in the rr code.  Would it be possible to loosen this restriction to work with perf_event_paranoid == 2?

**Comment by khuey** [comment]
I believe you can pass the `-n` argument to `rr record` to disable the code paths that require `perf_event_paranoid <= 1`, at the cost of slower performance.

**Comment by wcohen** [comment]
rr does make mention of that:

$ rr record ./muliply
rr needs /proc/sys/kernel/perf_event_paranoid <= 1, but it is 2.
Change it to 1, or use 'rr record -n' (slow).
Consider putting 'kernel.perf_event_paranoid = 1' in /etc/sysctl.conf.
See 'man 8 sysctl', 'man 5 sysctl.d' and 'man 5 sysctl.conf' for more details.

The question was more what prevents the performance counter use in rr record for normal users when perf_event_paranoid == 2?

**Comment by khuey** [comment]
rr uses the `PERF_COUNT_SW_CONTEXT_SWITCHES` which the kernel considers "kernel profiling" (thus requiring perf_event_paranoid <= 1 or a user with CAP_PERFMON).

**Comment by wcohen** [comment]
Thanks.
