### ISSUE TITLE
Strangeness when using a diversion session in a multi-threaded trace replay

### ISSUE THREAD

**Issue by Bob131** [rr-debugger/rr#2836]
I'm working on something in which I would like to break on an event in one thread, switch to another thread and evaluate some expressions containing function calls. In executing a diversion session, however, replay of other threads seems to continue in parallel which causes GDB to abandon calls when a signal/breakpoint is hit in the inappropriately executing thread; when this happens, I've observed one of three things:

 - Call is aborted and I'm given a prompt in the context of the hit breakpoint/signal
 - Call never starts executing (the diverted thread's IP gets stuck at the beginning of the function) and execution in the other thread appears to continue beyond the extent of the recorded trace
 - GDB signals an error due to some failed assertion

An excerpt from an affected session:

```
(rr) reverse-continue
Thread 5 hit Hardware watchpoint 1: -location mini_object->refcount

Old value = 0
New value = 1
0x00007f6426c143ce in gst_mini_object_unref (mini_object=0x7f63f806a240 [None]) at ../gst/gstminiobject.c:642
642	  old_refcount = g_atomic_int_add (&mini_object->refcount, -1);
(rr) info threads
  Id   Target Id                                Frame 
... <snip> ...
* 5    Thread 1114424.1114431 (guile2.2)        0x00007f6426c143ce in gst_mini_object_unref (mini_object=0x7f63f806a240 [None]) at ../gst/gstminiobject.c:642
... <snip> ...
  13   Thread 1114424.1114862 (multiqueue0:src) 0x00007f643ad7a7a5 in vm_regular_engine (thread=0x7f64281d51a0, vp=0x7f6424ddbea0, registers=0x7f6428da0aa0, resume=15) at vm-engine.c:1446
... <snip> ...
(rr) thread 13
[Switching to thread 13 (Thread 1114424.1114862)]
#0  0x00007f643ad7a7a5 in vm_regular_engine (thread=0x7f64281d51a0, vp=0x7f6424ddbea0, registers=0x7f6428da0aa0, resume=15) at vm-engine.c:1446
1446	      BR_UNARY (x, SCM_HAS_TYP7 (x, (ip[1] >> 1) & 0x7f));
(rr) set scheduler-locking on
(rr) call scm_backtrace()
(guile2.2:1114426): GStreamer-CRITICAL **: 03:58:46.074: gst_mini_object_unref: assertion 'GST_MINI_OBJECT_REFCOUNT_VALUE (mini_object) > 0' failed
../../gdb/inline-frame.c:383: internal-error: void skip_inline_frames(thread_info*, bpstat): Assertion `find_inline_frame_state (thread) == NULL' failed.
A problem internal to GDB has been detected,
```

**Comment by Bob131** [comment]
Having a look at the code, it seems like the assumption that the ID of the task to be executed in the diversion `== last_continue_tuid` (see [`GdbServer::divert`](https://github.com/rr-debugger/rr/blob/ef2ddde82258f32e779a59db8c0039d2af5ead9e/src/GdbServer.cc#L1025)) is violated by my use case. Is this correct, or does GDB issue some debugger requests that make the assumption valid when setting up for a function call?

**Comment by rocallahan** [comment]
I don't think running code in the non-current thread has ever been supported.

**Comment by Bob131** [comment]
I vaguely recall reading that rr does some tricks to serialise execution of concurrent threads; is this what you mean by 'current thread'? The thread currently replaying execution?

What would be involved in making this work? AFAICS LWPs are made for threads more or less normally, so it seems to me (perhaps naively) that choosing the correct task in `GdbServer::divert()` should be sufficient. I'm assuming this is wrong, but I'm just wondering how much hairier it gets?

**Comment by rocallahan** [comment]
> The thread currently replaying execution?

Right.

It's probably not that hard to get something working here.

**Comment by Bob131** [comment]
So simply changing uses of `last_continue_tuid` to `last_query_tuid` in `GdbServer::diverter_process_debugger_requests()` and `GdbServer::divert()` seems to work, but it's not clear to me whether this is correct. Do you remember the rationale for using `last_continue_tuid`?

I'm also wondering if the code might be clearer if the diverter methods had an explicit `TaskUid` parameter rather than determining it heuristically through the `last_x_tuid` state machine and have `GdbServer::process_debugger_requests()` pass `req.target.tid`? AFAICS this should be equivalent to using `last_query_tuid` as above, so obviously subject to the same question re correctness.

**Comment by rocallahan** [comment]
> Do you remember the rationale for using last_continue_tuid?

No. This code hasn't been touched for a long time.

> the code might be clearer if the diverter methods had an explicit TaskUid parameter rather than determining it heuristically

Sounds good to me.

**Comment by Bob131** [comment]
Okay, so I've figured out what's going on. Ignore what I've said above: `last_continue_tuid` is correct per the appendix on the serial protocol in the GDB manual, and an explicit parameter is not appropriate as the right `last_continue_tuid` isn't known at invocation and may change. The problem is actually a bug in which `last_continue_tuid` isn't updated to reflect the TID specified in the `vCont` packet that kicks off the execution of the diversion.

I have a fix in the works; I'll open a PR when it's in a more review-able state.
