### ISSUE TITLE
ioctl TIOCGSERIAL causes assertion failure

### ISSUE THREAD

**Issue by durka** [rr-debugger/rr#2855]
I ran into the same problem as #2091, but with TIOCGSERIAL (0x541E). Can this be trivially whitelisted as well?

**Comment by khuey** [comment]
This was added in 3a9344f8edbc4b4c2fb1e4c76cc314ba1af5b40f so you probably just need to build the latest rr from source.

**Comment by durka** [comment]
Oh okay, thanks. I had downloaded the latest release (ubuntu is shipping an ancient rr from 2017!) but I guess that wasn't quite recent enough.

**Comment by khuey** [comment]
Yeah we'll probably do a new release shortly though it doesn't sound like that will help your Ubuntu version.
