### ISSUE TITLE
Is there any way to uniquely identify a stack frame? 

### ISSUE THREAD

**Issue by danielzfranklin** [rr-debugger/rr#2857]
I'm looking for a way to uniquely identify a stack frame. Can I use the event number at the start for this purpose?

**Comment by rocallahan** [comment]
No.
Using event number + tick count will work *most* of the time but there are cases where it won't work, e.g.
```
void g() { }
void f() {
   g();
   g();
}
```
so no ticks elapse between calls to g().

**Comment by danielzfranklin** [comment]
Thank you!
