### ISSUE TITLE
replay with extended remote

### ISSUE THREAD

**Issue by GitMensch** [rr-debugger/rr#2874]
I have two nodes. nodeOne recorded a run and I can use `rr replay -k -s 9999` on it and then connect in a different terminal within GDB with `target extended-remote :9999`.

But the actual debugging should be done from nodeTwo which does not have `rr` installed at all, is this possible?

Note: for "normal" debugging I use `gdbserver --multi :9999` on nodeOne and then can issue `target extended-remote nodeOne:9999` just fine - but that did not work with `rr replay` (5.4.0). Is this possible?

Things I've tried so far:

`rr replay -k -s 9999`
`rr replay -k -s 9999 -h "*"`
`rr replay -k -s 9999 -h ""`
`rr replay -k -s 9999 -h nodeTwo`

... but in all cases GDB times out when connecting from nodeTwo.

**Comment by khuey** [comment]
`set debug remote 1` in gdb and post the log when you try to connect?

**Comment by GitMensch** [comment]
Will do. What is the correct command to I start `rr replay -s` to allow connections from a different computer?

**Comment by khuey** [comment]
`rr replay -s` should be fine as long as you actually route the port appropriately.

**Comment by GitMensch** [comment]
So my test findings:

* `rr replay -s 1234 -h ""` --> no connection possible at all; I suggest to make that an error
* `rr replay -s 1234 -h "*"` --> no connection possible at all; I suggest to make that an error
* `rr replay -s 1234`
    * `target extended-remote :1234` -> connection possible
    * `target extended-remote 127.0.0.1:1234` -> connection possible
    * `target extended-remote own-ip:1234` -> connection timeout

... and as the connection times out there is no output of `debug remote 1` either.
A `!ping own-ip` works fine so I'd guess I need to pass "something" on the `rr` command line to allow that.

... compared to gdbserver:
`gdbserver --multi :1234 /path/to/binary` and then (on the same machine in a gdb session) `target extended-remote own-ip:1234` --> connection possible

**Comment by GitMensch** [comment]
I've retested that with rr master today and the result is the same:

`target extended-remote 127.0.0.1:1234` -> connection possible
`target extended-remote real_ip_resolved_by_ping:1234` ->  Connection timed out.

If the starting process was gdbserver then both work.

I guess we possibly can find out more with RR_LOG? Before we do: @khuey Can you please try to connect `rr -s` with `target extended-remote own-ip:port` on your side?

**Comment by khuey** [comment]
If you really want the `gdbserver` behavior you can add `-h 0.0.0.0` to the `rr replay` command. gdbserver binds to INADDR_ANY by default, rr binds to localhost by default.

**Comment by GitMensch** [comment]
That was the answer I've searched. Now it is [part of the wiki](https://github.com/rr-debugger/rr/wiki/Using-rr-in-an-IDE/270a3ba2f5f3b7babdaf0105005e1b69dc14432b) and therefore this issue can be closed.
Thanks again!
