### ISSUE TITLE
calling library functions during rr replay

### ISSUE THREAD

**Issue by GitMensch** [rr-debugger/rr#2875]
I currently use a pretty printer that resolves values by calling into the library. While GDB folks highlight (sadly not in the documentation) that a pretty printer should better do what the library does (otherwise the pretty printer won't work for debugging coredumps, fore example) this normally works quite fine in a "normal" debugging session, because the library functions called don't change the state of the the library.

This even works during rr replay - but trashes the session relative fast.

Question: Is it possible to call into the debugged library without breaking the state?

The current layout is:

* call into the library to malloc necessary buffers (I guess this is most problematic part)
* call into the library passing the buffer and the parts to pretty-print, the library _only_ writes to the buffer

Can this somehow work in a rr replay session?

**Comment by rocallahan** [comment]
Can you give an example of how this "trashes the state"? rr should be creating a separate DiversionSession for this.

**Comment by GitMensch** [comment]
That's interesting, to what extend is it possible to have a diverting state (I assume changing a variable of the program with `p var=1` or `jump` likely won't work)?

> Can you give an example of how this "trashes the state"?

That's as easily reproduced as I've thought, but once it is the calls to `malloc` from the pretty-printer return an error and if I `continue`/`start` I get into a loop of

> [FATAL /builddir/build/BUILD/rr-5.4.0/src/Task.cc:2928:write_bytes_helper() errno: EIO]
 (task 28291 (rec:4721) at time 3685)
 -> Assertion `nwritten == buf_size' failed to hold. Should have written 1 bytes to 0x7fbbf2854ef9, but only wrote -1
Tail of trace dump:
{
  real_time:871307.875171 global_time:3665, event:`SYSCALL: munmap' (state:ENTERING_SYSCALL) tid:4719, ticks:13929102
rax:0xffffffffffffffda rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x2 rsi:0x6600d8 rdi:0x7fbbf046c000 rbp:0x7ffcc1b6dc50 rsp:0x681ffde0 r8:0x7fbbfcd86930 r9:0x7fbbfcd75b80 r10:0x0 r11:0x246 r12:0x7ffcc1b6db6c r13:0x7ffcc1b6daf0 r14:0x7fbbfcd87120 r15:0x1d2b460 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xb fs_base:0x7fbbfcd75b80 gs_base:0x0
}
{
  real_time:871307.875232 global_time:3666, event:`SYSCALL: munmap' (state:EXITING_SYSCALL) tid:4719, ticks:13929102
rax:0x0 rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x2 rsi:0x6600d8 rdi:0x7fbbf046c000 rbp:0x7ffcc1b6dc50 rsp:0x681ffde0 r8:0x7fbbfcd86930 r9:0x7fbbfcd75b80 r10:0x0 r11:0x246 r12:0x7ffcc1b6db6c r13:0x7ffcc1b6daf0 r14:0x7fbbfcd87120 r15:0x1d2b460 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xb fs_base:0x7fbbfcd75b80 gs_base:0x0
}
{
  real_time:871307.875265 global_time:3667, event:`SYSCALL: munmap' (state:ENTERING_SYSCALL) tid:4719, ticks:13931000
rax:0xffffffffffffffda rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x2 rsi:0x64c028 rdi:0x7fbbf0acd000 rbp:0x7ffcc1b6dc50 rsp:0x681ffde0 r8:0x7fbbfcd86930 r9:0x7fbbfcd75b80 r10:0x0 r11:0x246 r12:0x7ffcc1b6db7b r13:0x7ffcc1b6db18 r14:0x7fbbfcd87120 r15:0x1d28f80 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xb fs_base:0x7fbbfcd75b80 gs_base:0x0
}
{
  real_time:871307.875387 global_time:3668, event:`SYSCALL: munmap' (state:EXITING_SYSCALL) tid:4719, ticks:13931000
rax:0x0 rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x2 rsi:0x64c028 rdi:0x7fbbf0acd000 rbp:0x7ffcc1b6dc50 rsp:0x681ffde0 r8:0x7fbbfcd86930 r9:0x7fbbfcd75b80 r10:0x0 r11:0x246 r12:0x7ffcc1b6db7b r13:0x7ffcc1b6db18 r14:0x7fbbfcd87120 r15:0x1d28f80 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xb fs_base:0x7fbbfcd75b80 gs_base:0x0
}
{
  real_time:871307.875420 global_time:3669, event:`SYSCALL: munmap' (state:ENTERING_SYSCALL) tid:4719, ticks:13932853
rax:0xffffffffffffffda rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x2 rsi:0x64f7a0 rdi:0x7fbbf111a000 rbp:0x7ffcc1b6dc50 rsp:0x681ffde0 r8:0x7fbbfcd86930 r9:0x7fbbfcd75b80 r10:0x0 r11:0x246 r12:0x7ffcc1b6db7a r13:0x7ffcc1b6db10 r14:0x7fbbfcd87120 r15:0x1d25b60 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xb fs_base:0x7fbbfcd75b80 gs_base:0x0
}
{
  real_time:871307.875544 global_time:3670, event:`SYSCALL: munmap' (state:EXITING_SYSCALL) tid:4719, ticks:13932853
rax:0x0 rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x2 rsi:0x64f7a0 rdi:0x7fbbf111a000 rbp:0x7ffcc1b6dc50 rsp:0x681ffde0 r8:0x7fbbfcd86930 r9:0x7fbbfcd75b80 r10:0x0 r11:0x246 r12:0x7ffcc1b6db7a r13:0x7ffcc1b6db10 r14:0x7fbbfcd87120 r15:0x1d25b60 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xb fs_base:0x7fbbfcd75b80 gs_base:0x0
}
{
  real_time:871307.875578 global_time:3671, event:`SYSCALL: munmap' (state:ENTERING_SYSCALL) tid:4719, ticks:13934649
rax:0xffffffffffffffda rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x2 rsi:0x2037c8 rdi:0x7fbbf176a000 rbp:0x7ffcc1b6dc50 rsp:0x681ffde0 r8:0x7fbbfcd86930 r9:0x7fbbfcd75b80 r10:0x0 r11:0x246 r12:0x7ffcc1b6db79 r13:0x7ffcc1b6db18 r14:0x7fbbfcd87120 r15:0x1d241e0 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xb fs_base:0x7fbbfcd75b80 gs_base:0x0
}
{
  real_time:871307.875601 global_time:3672, event:`SYSCALL: munmap' (state:EXITING_SYSCALL) tid:4719, ticks:13934649
rax:0x0 rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x2 rsi:0x2037c8 rdi:0x7fbbf176a000 rbp:0x7ffcc1b6dc50 rsp:0x681ffde0 r8:0x7fbbfcd86930 r9:0x7fbbfcd75b80 r10:0x0 r11:0x246 r12:0x7ffcc1b6db79 r13:0x7ffcc1b6db18 r14:0x7fbbfcd87120 r15:0x1d241e0 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xb fs_base:0x7fbbfcd75b80 gs_base:0x0
}
{
  real_time:871307.875633 global_time:3673, event:`SYSCALL: munmap' (state:ENTERING_SYSCALL) tid:4719, ticks:13936393
rax:0xffffffffffffffda rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x2 rsi:0x670730 rdi:0x7fbbf196e000 rbp:0x7ffcc1b6dc50 rsp:0x681ffde0 r8:0x7fbbfcd86930 r9:0x7fbbfcd75b80 r10:0x0 r11:0x246 r12:0x7ffcc1b6db78 r13:0x7ffcc1b6db10 r14:0x7fbbfcd87120 r15:0x1d21f70 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xb fs_base:0x7fbbfcd75b80 gs_base:0x0
}
{
  real_time:871307.875763 global_time:3674, event:`SYSCALL: munmap' (state:EXITING_SYSCALL) tid:4719, ticks:13936393
rax:0x0 rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x2 rsi:0x670730 rdi:0x7fbbf196e000 rbp:0x7ffcc1b6dc50 rsp:0x681ffde0 r8:0x7fbbfcd86930 r9:0x7fbbfcd75b80 r10:0x0 r11:0x246 r12:0x7ffcc1b6db78 r13:0x7ffcc1b6db10 r14:0x7fbbfcd87120 r15:0x1d21f70 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xb fs_base:0x7fbbfcd75b80 gs_base:0x0
}
{
  real_time:871307.875799 global_time:3675, event:`SYSCALL: munmap' (state:ENTERING_SYSCALL) tid:4719, ticks:13938092
rax:0xffffffffffffffda rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x2 rsi:0x6667a8 rdi:0x7fbbf21ea000 rbp:0x7ffcc1b6dc50 rsp:0x681ffde0 r8:0x7fbbfcd86930 r9:0x7fbbfcd75b80 r10:0x0 r11:0x246 r12:0x7ffcc1b6db76 r13:0x7ffcc1b6db10 r14:0x7fbbfcd87120 r15:0x1d1cd80 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xb fs_base:0x7fbbfcd75b80 gs_base:0x0
}
{
  real_time:871307.875867 global_time:3676, event:`SYSCALL: munmap' (state:EXITING_SYSCALL) tid:4719, ticks:13938092
rax:0x0 rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x2 rsi:0x6667a8 rdi:0x7fbbf21ea000 rbp:0x7ffcc1b6dc50 rsp:0x681ffde0 r8:0x7fbbfcd86930 r9:0x7fbbfcd75b80 r10:0x0 r11:0x246 r12:0x7ffcc1b6db76 r13:0x7ffcc1b6db10 r14:0x7fbbfcd87120 r15:0x1d1cd80 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xb fs_base:0x7fbbfcd75b80 gs_base:0x0
}
{
  real_time:871307.875899 global_time:3677, event:`SYSCALL: munmap' (state:ENTERING_SYSCALL) tid:4719, ticks:13939744
rax:0xffffffffffffffda rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x2 rsi:0x7e4d28 rdi:0x7fbbf2851000 rbp:0x7ffcc1b6dc50 rsp:0x681ffde0 r8:0x7fbbfcd86930 r9:0x7fbbfcd75b80 r10:0x0 r11:0x246 r12:0x7ffcc1b6db75 r13:0x7ffcc1b6db08 r14:0x7fbbfcd87120 r15:0x1d1aff0 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xb fs_base:0x7fbbfcd75b80 gs_base:0x0
}
{
  real_time:871307.875981 global_time:3678, event:`SYSCALL: munmap' (state:EXITING_SYSCALL) tid:4719, ticks:13939744
rax:0x0 rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x2 rsi:0x7e4d28 rdi:0x7fbbf2851000 rbp:0x7ffcc1b6dc50 rsp:0x681ffde0 r8:0x7fbbfcd86930 r9:0x7fbbfcd75b80 r10:0x0 r11:0x246 r12:0x7ffcc1b6db75 r13:0x7ffcc1b6db08 r14:0x7fbbfcd87120 r15:0x1d1aff0 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xb fs_base:0x7fbbfcd75b80 gs_base:0x0
}
{
  real_time:871307.876187 global_time:3679, event:`PATCH_SYSCALL' tid:4719, ticks:13979982
rax:0x3 rbx:0x3 rcx:0xffffffffffffffff rdx:0x0 rsi:0x7fbbf21e8c58 rdi:0x3 rbp:0x7ffcc1b6dde0 rsp:0x7ffcc1b6dc90 r8:0x7fbbf441fac0 r9:0x1 r10:0x7ffcc1b6dc00 r11:0x246 r12:0x0 r13:0x7ffcc1b6dd08 r14:0x7fbbf21e8c60 r15:0x1d218f0 rip:0x7fbbfb782f4d eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xffffffffffffffff fs_base:0x7fbbfcd75b80 gs_base:0x0
  { tid:4719, addr:0x7fbbfcb89278, length:0x4f }
  { tid:4719, addr:0x7fbbfb782f4d, length:0x5 }
  { tid:4719, addr:0x7fbbfb782f52, length:0x3 }
}
{
  real_time:871307.876267 global_time:3680, event:`SYSCALLBUF_FLUSH' tid:4719, ticks:13981372
  { syscall:'close', ret:0x0, size:0x10 }
}
{
  real_time:871307.876291 global_time:3681, event:`PATCH_SYSCALL' tid:4719, ticks:13981372
rax:0xe7 rbx:0x7fbbfba4e880 rcx:0xffffffffffffffff rdx:0x0 rsi:0x3c rdi:0x0 rbp:0x0 rsp:0x7ffcc1b6dde8 r8:0xe7 r9:0xffffffffffffff80 r10:0x14 r11:0x246 r12:0x7fbbfba4e880 r13:0x2 r14:0x7fbbfba57348 r15:0x0 rip:0x7fbbfb75e254 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xffffffffffffffff fs_base:0x7fbbfcd75b80 gs_base:0x0
  { tid:4719, addr:0x7fbbfcb892c7, length:0x4f }
  { tid:4719, addr:0x7fbbfb75e254, length:0x5 }
  { tid:4719, addr:0x7fbbfb75e259, length:0x3 }
}
{
  real_time:871307.876294 global_time:3682, event:`SYSCALLBUF_RESET' tid:4719, ticks:13981372
}
{
  real_time:871307.876325 global_time:3683, event:`SYSCALL: exit_group' (state:ENTERING_SYSCALL) tid:4719, ticks:13981378
rax:0xffffffffffffffda rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x0 rsi:0x3c rdi:0x0 rbp:0x0 rsp:0x681ffde0 r8:0xe7 r9:0xffffffffffffff80 r10:0x14 r11:0x246 r12:0x7fbbfba4e880 r13:0x2 r14:0x7fbbfba57348 r15:0x0 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xe7 fs_base:0x7fbbfcd75b80 gs_base:0x0
}
{
  real_time:871307.876470 global_time:3684, event:`EXIT' tid:4719, ticks:13981378
  { tid:4719, addr:0x7fbbfcd75e50, length:0x4 }
}
{
  real_time:871307.877179 global_time:3685, event:`EXIT' tid:4721, ticks:153
}
[FATAL /builddir/build/BUILD/rr-5.4.0/src/Task.cc:2928:write_bytes_helper() errno: EIO]
 (task 28291 (rec:4721) at time 3685)
 -> Assertion `nwritten == buf_size' failed to hold. Should have written 1 bytes to 0x7fbbf2854ef9, but only wrote -1


I guess at least the loop should be fixable (by exiting from the debugger with a hard error), should I open a new issue about this part?

**Comment by rocallahan** [comment]
What exactly did you do to trigger that error?

**Comment by GitMensch** [comment]
That's harder to reproduce.... while I can do it, it involves debugging into production (zipped packed trace would be ~90MB and even then I cannot share that) *and* calling into the library debugged via some calls from the pretty-printer.
Is there something I can help to debug the issue without finding the minimal example?

**Comment by GitMensch** [comment]
This may or may not help: no matter "where" it happens (depends on where the pretty-printer is called) the error including backtrace and address is always identical.

**Comment by GitMensch** [comment]
Happened again in "debugging a production run", but this time no pretty-printer was even loaded and the system-distributed GDB (GNU gdb (GDB) Red Hat Enterprise Linux 8.2-12.el8) was used. So the "error" itself can now be tracked at #2879, when this is solved we can reinspect if the pretty-printer still creates issues - and in the meantime I've learned that it likely shouldn't because of then nice [DiversionSession](https://github.com/rr-debugger/rr/blob/878f756966c660a6e838cbf3516f953e586b9edc/src/DiversionSession.h#L13).

**Comment by GitMensch** [comment]
The pretty-printer now doesn't use library functions anymore (because that breaks printing when in coredumps and also created issues when printing in the signal handler); "minor" manual calls "here and there" worked fine and I've learned about the DiversionSession; I've once seen a message about not being able to create a DiversionSession because of a _huge_ malloc call (pretty printing a 64k value...); so for me the issue is solved now.
