### ISSUE TITLE
bytecode stream in file ‘CMakeFiles/rr.dir/src/Dwarf.cc.o’ generated with LTO version 9.2 instead of the expected 11.0

### ISSUE THREAD

**Issue by bdekoz** [rr-debugger/rr#2884]
top of tree linux build fails with:

...
[ 52%] Building C object CMakeFiles/clone_bad_tls.dir/src/test/clone_bad_tls.c.o
lto1: fatal error: bytecode stream in file ‘CMakeFiles/rr.dir/src/Dwarf.cc.o’ generated with LTO version 9.2 instead of the expected 11.0
compilation terminated.
lto-wrapper: fatal error: /usr/bin/c++ returned 1 exit status
compilation terminated.
/usr/bin/ld.bfd: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/rr.dir/build.make:1228: bin/rr] Error 1
make[1]: *** [CMakeFiles/Makefile2:13587: CMakeFiles/rr.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
....

%uname -a
Linux moss 5.12.8-300.fc34.x86_64 #1 SMP Fri May 28 15:20:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

%g++ --version
g++ (GCC) 11.1.1 20210428 (Red Hat 11.1.1-1)

%clang --version
clang version 12.0.0 (Fedora 12.0.0-0.3.rc1.fc34)

**Comment by bdekoz** [comment]
configured via:

cmake -DCMAKE_INSTALL_PREFIX=/home/bkoz/bin/H-rr -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" ..

**Comment by rocallahan** [comment]
Did you do a clean build? It sounds like you might have an existing build and then you updated some package...

**Comment by bdekoz** [comment]
Agh! You are right. I fresh checkout fixes this. Sorry about this noise.
