### ISSUE TITLE
Running with perf_event_paranoid > 1

### ISSUE THREAD

**Issue by DuckDuckWhale** [rr-debugger/rr#2891]
On version 5.4.0, even running with root I still get this message:
```
rr needs /proc/sys/kernel/perf_event_paranoid <= 1, but it is 4.
Change it to 1, or use 'rr record -n' (slow).
Consider putting 'kernel.perf_event_paranoid = 1' in /etc/sysctl.conf.
See 'man 8 sysctl', 'man 5 sysctl.d' and 'man 5 sysctl.conf' for more details.
```

From my limited understanding, the root user should be able to use the performance counters yet the hard coded check in rr prevents it from being used. I'm trying to run rr without changing the perf_event_paranoid setting system wide by giving it capabilities (CAP_PERFMON), but since even root can't help I have ran out of ideas. If my understanding is correct, could a way to disable explicitly checking perf_event_paranoid (or, better, making rr aware of capabilities) make it work in this case?

**Comment by rocallahan** [comment]
Fixed by 0f60b491118ba4d2e271101a264b6d6a005faad9
