### ISSUE TITLE
blink_unittests crashes when run under rr record

### ISSUE THREAD

**Issue by cbiesinger** [rr-debugger/rr#2894]
Chromium has a testing binary called blink_unittests. (If you have a build setup for chromium you can build it using `autoninja -C out/Debug blink_unittests`)

When I run it under rr, it crashes like this:
```
$ rr record out/Debug/blink_unittests  --gtest_filter=ExternalPopupMenuTest.PopupAccountsForDeviceScaleFactor
rr: Saving execution to trace directory `/usr/local/google/home/cbiesinger/.local/share/rr/blink_unittests-1'.
blink_unittests: ../../third_party/abseil-cpp/absl/debugging/internal/elf_mem_image.cc:254: void absl::debugging_internal::ElfMemImage::Init(const void *): Assertion `false' failed.
Aborted
```

I have also uploaded this to Pernosco at https://pernos.co/debug/MuKH7p-WgqR0tYY1oCxPKA/index.html 

It seems like it is trying to find the VDSO and failing in some way.

Code: https://source.chromium.org/chromium/chromium/src/+/main:third_party/abseil-cpp/absl/debugging/internal/elf_mem_image.cc;l=254?q=elf_mem_image.cc&ss=chromium

**Comment by khuey** [comment]
In particular this code `getauxval(AT_SYSINFO_EHDR)`, expects that to be vdso, and then dies when it's not.

Any thoughts @Keno?

**Comment by cbiesinger** [comment]
Some documentation at https://man7.org/linux/man-pages/man7/vdso.7.html seems to suggest that expecting AT_SYSINFO_EHDR to be the vDSO is correct.

**Comment by Keno** [comment]
Looks like it just assumes there's more DT entries in the vdso than we provide in librrpage (which we pretend is the vdso to avoid having to do sketchy vdso patching that breaks unwinding). I think we can probably just adjust librrpage to provide those expected entries.

**Comment by khuey** [comment]
We're missing DT_HASH, DT_VERSYM, DT_VERDEF, and DT_VERDEFNUM it looks like.

**Comment by rocallahan** [comment]
In fact this code expects all vdso dynamic symbols to be versioned :-(

**Comment by rocallahan** [comment]
I think 38571520bee9360aeb454a14be1de43e7490f324 should fix this but I haven't done a Chromium build to check.

**Comment by rocallahan** [comment]
> In fact this code expects all vdso dynamic symbols to be versioned :-(

This isn't true actually, AFAICT. It just wants those DT entries to exist.

**Comment by rocallahan** [comment]
I'll close this. Reopen if I got it wrong or if the test fails some other way.

**Comment by cbiesinger** [comment]
Thanks, this works now.
