### ISSUE TITLE
Assertion `data > hole' failed to hold. 

### ISSUE THREAD

**Issue by glacambre** [rr-debugger/rr#2911]
Dear maintainers,

I found an RR crash while trying to record the execution of a program. This happens using rr version 5.4.0 ( built from current master, 4ca2dc66a35f5f7833cf5ea493323e0710338cd3 ) on Linux 5.8.0. The (what seems to be) interesting part of RR's output after its crash is:
```
[ FATAL rr/src/record_syscall.cc:5416:find_holes() errno: EXDEV] 
 (task 2239487 (rec:2239487) at time 41288)
 -> Assertion `data > hole' failed to hold. 
```

I've attached a log file obtained with RR_LOG=all. Please let me know if there's anything else I should do to provide more information: [log.zip](https://github.com/rr-debugger/rr/files/6765355/log.zip).

**Comment by rocallahan** [comment]
I pushed some improved logging to master, so if you pull that and rerun we should get a little more info.

**Comment by glacambre** [comment]
Here you go: [log.zip](https://github.com/rr-debugger/rr/files/6768645/log.zip).

**Comment by khuey** [comment]
The issue here was that both SEEK_HOLE and SEEK_DATA seek to 0 on `/dev/zero`, and that was not being handled properly.

Separately, we weren't recognizing `/dev/zero` as `/dev/zero`, and if we do that we can skip trying to store it in the trace entirely.

**Comment by glacambre** [comment]
Oh, great to see that this was actually an easily fixed issue. Thanks a lot for taking care of it so quickly!
