### ISSUE TITLE
glibc 2.34 enablement around pthread mutex handling

### ISSUE THREAD

**Issue by fweimer-rh** [rr-debugger/rr#2913]
`src/preload/overrides.c` contains this code:

```c
/*
 * We need to able to call directly to __pthread_mutex_lock and
 * __pthread_mutex_trylock because setting up indirect function pointers
 * in init_process requires calls to dlsym which itself can call
 * pthread_mutex_lock (e.g. via application code overriding malloc/calloc
 * to use a pthreads-based implementation). So before our pointers are set
 * up, call these.
 */
extern int __pthread_mutex_lock(pthread_mutex_t* mutex);
extern int __pthread_mutex_trylock(pthread_mutex_t* mutex);
```

I want to remove most of the `__`-prefixed functions from the glibc 2.34 release. The above symbols would become unavailable for linking. Based on the comment, that should not be a problem because you can use `RTLD_NEXT` on glibc 2.34: `dlsym` uses an internal direct call to `pthread_mutex_lock`, without going through dynamic linking.

Would you be open to making this change? Fedora rawhide (available as a container image on `registry.fedoraproject.org/fedora:rawhide`) already contains a glibc 2.34 snapshot, if you want to experiment with it. Thanks.

**Comment by rocallahan** [comment]
Thanks for the heads-up! I guess the question is, how do we write the code so it works on both 2.34 and pre-2.34. It's no immediately obvious to me how to do that.

**Comment by fweimer-rh** [comment]
If you build against glibc 2.34, the resulting binaries won't run on older glibc versions anyway, so you can just use a compile-time conditional, like:

```c
#ifdef __GLIBC_PREREQ
#if __GLIBC_PREREQ(2, 34)
// New code goes here.
#else
// Old code goes here.
#endif
#endif
```

Old binaries will continue to load (we are about to remove `__pthread_mutex_lock`, `__pthread_mutex_trylock` only for linking new programs), but I don't know to what extent your tool depends on glibc internals. glibc 2.34 no longer has a separate `libpthread`, and there have been quite some changes how things are linked together internally as a result. Some porting unrelated to the symbol changes I mentioned might be needed.

**Comment by khuey** [comment]
The code in src/preload doesn't build/link against glibc at all (it uses `-nostartfiles`), it gets LD_PRELOADed into another process and ideally one binary would work in both glibc 2.33-using and glibc 2.34-using processes.

**Comment by khuey** [comment]
Actually ignore my last comment, that was wrong.

**Comment by rocallahan** [comment]
Sounds like we should just add that conditional build stuff and then carry on building with an old distro for releases (and let me mention once again how annoying that requirement is).
