### ISSUE TITLE
[wiki] Fedora build instructions: bits/c++config.h: No such file or directory

### ISSUE THREAD

**Issue by hexagonrecursion** [rr-debugger/rr#2918]
The below did not work for me:
https://github.com/rr-debugger/rr/wiki/Building-And-Installing#dependencies-installation:
> ```sh
> sudo dnf install \
>   ccache cmake make gcc gcc-c++ gdb libgcc libgcc.i686 \
>   glibc-devel glibc-devel.i686 libstdc++-devel libstdc++-devel.i686 \
>   python3-pexpect man-pages ninja-build capnproto capnproto-libs capnproto-devel
> ```
I got:
```
In file included from /usr/include/c++/11/stdlib.h:36,
                 from /home/rr/obj/32/util.h:15,
                 from /home/rr/obj/32/unwind_rr_page.cc:3:
/usr/include/c++/11/cstdlib:41:10: fatal error: bits/c++config.h: No such file or directory
   41 | #include <bits/c++config.h>
```
when running:
```sh
mkdir obj && cd obj
cmake ../rr
make -j8
```
I have had to additionally install `libstdc++-devel.x86_64`

**Comment by hexagonrecursion** [comment]
```
uname -m
x86_64
cat /etc/fedora-release 
Fedora release 34 (Thirty Four)
```

**Comment by rocallahan** [comment]
Wiki page updated, thanks.
