### ISSUE TITLE
"When" command when running rr replay in server mode.

### ISSUE THREAD

**Issue by jkordani** [rr-debugger/rr#2925]
gdb command is 
 gdb -i=mi -l 10000 -ex "target extended-remote 127.0.0.1:9888"

gdb init is 
set annotate 1
set filename-display absolute
set sysroot /
set non-stop off
set target-async off
maint set target-async off
maint set target-non-stop off

set debug-file-directory /usr/lib/debug:/usr/local/lib/debug

in gdb with remote target 
(gdb) when
Undefined command: "when".  Try "help".

**Comment by khuey** [comment]
You need to source rr's gdbinit. You can get that by running `rr gdbinit`, and it will print it to the terminal.
