### ISSUE TITLE
My gdb terminal in emacs has ^Z^Z before the beginning of some lines

### ISSUE THREAD

**Issue by jkordani** [rr-debugger/rr#2930]
`path/to/sopurce.cc:1035:24366:beg:0x68f990
1: _northing_m = 4207980.8885306921
2: _easting_m = 586627.33506983658`

sometimes when autocompleting in the gdb buffer, the cursor jumps up a few lines into the previous output.  I have a feeling this is due to the fact that the machine interface is leaking raw bytes into the gdb buffer, or something.

I have in .gdb init
set annotate 1
set filename-display absolute
set sysroot /
set non-stop off
set target-async off
maint set target-async off
maint set target-non-stop off

set max-completions 10000
source ~/.rrgdbinit # which is just the ourput of rr gdbinit

I start rr replay in server mode

My M-x gdb call is
 gdb -i=mi -l 10000 /path/to/program -ex "target extended-remote 127.0.0.1:9888"

Emacs version is 27.1

**Comment by rocallahan** [comment]
Does this happen when using gdb without rr?

**Comment by jkordani** [comment]
Do you mean, using gdb server and gdb without the rrgdbinit? or gdb without the init connected to rr replay?

**Comment by jkordani** [comment]
gdb in a termial without .rrgdbinit without -i=mi doesn't produce the Zs.  Not sure what else to test, gud-gdb doesn't work as well as normal gdb mode

**Comment by rocallahan** [comment]
I mean gdb without rr involved at all, but with MI enabled

**Comment by jkordani** [comment]
ah, yes it does....

**Comment by rocallahan** [comment]
It would be great if you could report this to upstream gdb.
