### ISSUE TITLE
Replay hangs on Python script containing `os.execv`

### ISSUE THREAD

**Issue by loganwendholt** [rr-debugger/rr#2931]
`exec` syscall appears to fail when called from a Python script, making the replay impossible to finish.

Steps to reproduce:

`test.py`:
```
print("hello, world!")
```

```
$ rr record python3 test.py
hello, world!
```
```
$ rr replay
...
(rr) c
Continuing.
hello, world!

Program received signal SIGKILL, Killed.
0x0000000070000002 in syscall_traced ()
(rr) c
Continuing.
[Inferior 1 (process 3280465) exited normally]
(rr)
```

`exec.py`:
```
import os, sys
os.execv(sys.executable, [sys.executable, "test.py"])
```

```
$ rr record python3 exec.py
hello, world!
```
```
$ rr replay
...
(rr) c
Continuing.

Program stopped.
0x0000000070000002 in syscall_traced ()
(rr) c
Continuing.

Program stopped.
0x0000000070000002 in syscall_traced ()
(rr) c
Continuing.

Program stopped.
0x0000000070000002 in syscall_traced ()
```

Reverse-stepping a bit confirms it's the `exec` syscall that's being called last:
```
(rr) p $rax
$2 = 59
```

**Comment by khuey** [comment]
I think this is a gdb integration thing. `rr replay -a` plays through and displays "hello world", right?

**Comment by loganwendholt** [comment]
Right, `rr replay -a` seems to work just fine.

**Comment by rocallahan** [comment]
Yeah, we don't support gdb executing past execve. You can work around it by digging event numbers out of the trace and doing `rr replay -g <event>`.

gdb might have some feature to debug past execve but I haven't looked into it. We would accept patches if someone figures it out. But even if this can be made to work with gdb somehow, I'm almost certain it won't be able to reverse-execute through an execve, which is one reason I think Pernosco is a much better long-term approach than trying to squeeze a little bit more functionality out of gdb.

**Comment by rocallahan** [comment]
I'm going to close this in favour of issue #2381 where implementing support gdb crossing execve has been discussed.
