### ISSUE TITLE
rr replay crashes for sandboxed process

### ISSUE THREAD

**Issue by vlovich** [rr-debugger/rr#2932]
We have a "zygote" process that sets up a seccomp sandbox & forks off to do the actual processing of a request. While it's fine when run normally or under `rr record`, I'm observing that running the replay against the forked process results in a SIGSYS for `__open_nocancel` as part of libc's `malloc` invoking `get_nprocs`. Wondering if this is something that can be fixed or if there's a change to the way I replay that needs to be made.

**Comment by vlovich** [comment]
Interestingly when I run it in autopilot mode it's fine.

**Comment by khuey** [comment]
That's normal, gdb stops at SIGSYS by default. If you don't want to stop there `handle SIGSYS nostop noprint` and continue.

https://github.com/rr-debugger/rr/issues/1875#issuecomment-257928915

**Comment by rocallahan** [comment]
If you debug sandboxed processes with gdb regularly then you probably already have a .gdbinit file that ignores SIGSYS I guess? You probably want to source that.
