### ISSUE TITLE
compile error missing initializer for field 'tv_sec' of 'struct timespec' 

### ISSUE THREAD

**Issue by GitMensch** [rr-debugger/rr#2935]
~~~
/tmp/rr-master/src/test/pthread_mutex_timedlock.c: In function 'main':
/tmp/rr-master/src/test/pthread_mutex_timedlock.c:8:10: error: missing initializer for field 'tv_sec' of 'struct timespec' [-Werror=missing-field-initializers]
   struct timespec abstime = {};
          ^
In file included from /usr/include/sys/select.h:43:0,
                 from /usr/include/sys/types.h:219,
                 from /usr/include/stdlib.h:314,
                 from /tmp/rr-master/src/test/util.h:15,
                 from /tmp/rr-master/src/test/pthread_mutex_timedlock.c:3:
/usr/include/time.h:122:14: note: 'tv_sec' declared here
     __time_t tv_sec;  /* Seconds.  */
              ^
cc1: all warnings being treated as errors
~~~

**Comment by GitMensch** [comment]
Work-around 1: make the initialization explicit:

```diff
-   struct timespec abstime = {};
+   struct timespec abstime = {0,0};
```

For reasons unknown that is the single file that seems to use the default initialization!

Work-around 2: clear all generated objects, then start again with `CC=gcc cmake -Ddisable32bit=ON`.
The issue here was that while `gcc --version` outputs 5.1.0 `cc --version` outputs 4.8.5...

Initial:
> -- The C compiler identification is GNU 4.8.5
> -- The CXX compiler identification is GNU 5.1.0

After:
> -- The C compiler identification is GNU 5.1.0
> -- The CXX compiler identification is GNU 5.1.0

Can/should we tell cmake to first try gcc before trying cc?
Side note: the first resulted in link errors at the end, the second one actually worked (but needed the 32bit disabling).

**Comment by rocallahan** [comment]
Send a PR with the first workaround?

**Comment by GitMensch** [comment]
PR as requested, though I did not check if every environment on earth has exactly two entries in the timespec attribute.

Any insights on the following?
> Can/should we tell cmake to first try `gcc` before trying `cc`?

**Comment by rocallahan** [comment]
I don't think we should do that. We might as well honour cc.

**Comment by GitMensch** [comment]
Everything resolved/answered here. Thanks.
