### ISSUE TITLE
What is the use of rr-where?

### ISSUE THREAD

**Issue by GitMensch** [rr-debugger/rr#2945]
I've seen that it is part of some auto-initialization but I still don't follow it. It has a doc-comment

> Helper to get the location for checkpoints/history. Used by auto-args

* Is it for the user and/or for rr internals?
* Where/How is it actually used?
* Is this only for getting the location?

The confusion possibly comes from the doc-comment of its invoke method:

```python
#Get the symbol name from 'frame 0' in the format:
# '#0  0x00007f9d81a04c46 in _dl_start (arg=0x7ffee1f1c740) at rtld.c:356
# 356 in rtld.c'
```
What symbol name? _dl_start? The address? The arg, the location?

Does it matter if it looks different? Because the output may be adjusted depending on different user settings...

Thanks for sharing its intention.

**Comment by rocallahan** [comment]
The idea is to get a label we can attach to checkpoints that we can display when we list checkpoints.

**Comment by GitMensch** [comment]
OK, so it would be both "no compatibility problem" _if_ the format would be changed and we could adjust that.
As I've recently changed a complex GDB addon to not use a user command (`frame`), then parse the result (which is not guaranteed as frame decorators and other user settings can adjust it) via matchers / manual string parsing, but to instead use the gdb API to directly.

If there's interest I'd do the same for `rr-where` (but in this case I'd need a defined wanted format); but for the use-case it has it possibly is _exactly_ the best thing to display the first line without the `#0` as seen by the user.

Opinions / Ideas?

**Comment by rocallahan** [comment]
I think it's fine if we change the format, but why would we want to do that work?

**Comment by GitMensch** [comment]
We'd _want_ to do that work if we need the output to be something specific, as I've understood this is not the case because only the user will see that as hint. In this case the current way "record how the user would have seen this" is good.
The main point was: the format is not guaranteed in any way but the leading frame number (which we remove), and depending on the available debug symbols a code line at the end. Parsing "user output" is commonly both unsafe to parse and has a bad performance - both parts are not relevant here as I understand.
I'll do some tests and then likely will do a minor PR keeping the "user output", adding/adjusting some comments and moving the matcher to be static or br replaced by split.

**Comment by rocallahan** [comment]
Alright, there's nothing to do here then.
