### ISSUE TITLE
Watchpoints not respected across threads

### ISSUE THREAD

**Issue by aarzilli** [rr-debugger/rr#2950]
This could be a general problem or related to how Go spawns new threads, I'm not sure.

The problem reproduces with rr built from 3f2c2243e786128596656bf377739c1591ea5087.

Reproduction steps:
* Get the Go program at https://gist.github.com/aarzilli/3fa0e50b627117cd0666303bacf743d4
* Compile it with `go build -gcflags='all=-N -l' databpeasy.go` (I used version 1.16.5 but it shouldn't matter)
* record and replay with rr

```
(rr) b main.main
Breakpoint 1 at 0x4b8540: file /home/aa/n/delve/_fixtures/databpeasy.go, line 11.
(rr) c
Continuing.
[New Thread 2559394.2559395]
[New Thread 2559394.2559396]
[New Thread 2559394.2559397]
[New Thread 2559394.2559398]

Thread 1 hit Breakpoint 1, main.main () at /home/aa/n/delve/_fixtures/databpeasy.go:11
11	func main() { // Position 0
(rr) watch main.globalvar1
Hardware watchpoint 2: main.globalvar1
(rr) c
Continuing.
0 1
[New Thread 2559394.2559399]

Thread 1 hit Hardware watchpoint 2: main.globalvar1

Old value = 0
New value = 2
main.main () at /home/aa/n/delve/_fixtures/databpeasy.go:17
17		fmt.Printf("%d %d\n", globalvar1, globalvar2) // Position 1
(rr) c
Continuing.
2 1
2 4

Thread 1 hit Hardware watchpoint 2: main.globalvar1

Old value = 2
New value = 5
main.main () at /home/aa/n/delve/_fixtures/databpeasy.go:23
23		fmt.Printf("%d %d\n", globalvar1, globalvar2)
(rr) c
Continuing.
5 4
hello world!
goodbye world!
[New Thread 2559394.2559401]

Thread 7 received signal SIGKILL, Killed.
[Switching to Thread 2559394.2559401]
runtime.futex () at /usr/local/go116/src/runtime/sys_linux_amd64.s:580
580		MOVL	AX, ret+40(FP)
(rr) 
```

The watchpoint is hit at lines 17 and 23 (i.e. in the original thread where the breakpoint was set), but not at line 34, which is executed on a different thread. The printf before and after the assignment confirm that the thread is executed and `disass main.f` confirms that there is indeed a write to main.globalvar1 there.

**Comment by rocallahan** [comment]
Does this happen when you're using gdb without rr?

**Comment by aarzilli** [comment]
Weirdly, yes, even though the manual of gdb says that "In multi-threaded programs, watchpoints will detect changes to the watched expression from every thread."

**Comment by rocallahan** [comment]
I don't know that the problem is, but I guess this is not an rr bug then.

**Comment by aarzilli** [comment]
For the record, the problem is not that the watchpoint hit is detected by rr and then ignored by gdb, I've confirmed it by looking at the packets exchanged between them.

**Comment by aarzilli** [comment]
Never mind: the reason this happens is because apparently writes where the variable doesn't actually change value shouldn't be reported.

**Comment by rocallahan** [comment]
Ah yes. That's a real pain, but it's the way gdb works. We do things differently in pernos.co
