### ISSUE TITLE
Slow down when running multiple replay instances concurrently.

### ISSUE THREAD

**Issue by jrenx** [rr-debugger/rr#2959]
Hi rr developers,
I'm not familiar with RR internals. I tried to run replay instances concurrently (16 copies) and the replay program slowed down from from 5s to 50s. Is there synchronization overhead inside of RR that is causing this slowdown? If not, is there a way we can get rid of this slowdown?

Many Thanks!

**Comment by rocallahan** [comment]
Applications have several different and somewhat obscure ways to determine which core the current thread is running on. To make sure these return the same value during replay as during recording, rr runs all recorded threads pinned to a single specific core, and during replay pins the replaying threads to the same core. So if you do multiple replays of the same recording at once, they will compete for that core and you see this slowdown.

**Comment by rocallahan** [comment]
`rr replay --cpu-unbound` will relax this binding but may cause your replay to fail, so try it out. If your hardware (and virtual machine hypervisor, if applicable) support CPUID faulting then your replay will probably be fine. If your software uses the LSL instruction method to determine which core it's on (e.g., OpenJDK) then bad luck, the only way to make that work is by ensuring it runs on the right core.

**Comment by jrenx** [comment]
Thanks so much for the fast explanation! Will give that a try.
