### ISSUE TITLE
replay recording when binary has changed

### ISSUE THREAD

**Issue by altmannmarcelo** [rr-debugger/rr#2962]
Hi there,

While troubleshooting some issues I might recompile my software a few times. Everytime I run RR, I also make a copy of my binary.
Is there a way to point the replay session to another binary instead of the original, in my case I would point to the binary `rr record` was ran against to ?

**Comment by khuey** [comment]
You can `rr pack` before you rebuild and then your recording will continue to work even after rebuilding your binary.

**Comment by altmannmarcelo** [comment]
@khuey awesome. Thanks for the quick answer!
