### ISSUE TITLE
feature request: automatically create checkpoint at end of trace

### ISSUE THREAD

**Issue by milianw** [rr-debugger/rr#2966]
Hey there,

rr is awesome and we regularly use it. One pain point that I regularly have is that I need to wait for the `rr replay` to get to the final state. I.e. I often want to start at the end, say after an `assert()` is handled, and then go back from there.

Currently, I have to `continue` first until the `assert` is hit, which can be time consuming for larger traces. Would it be possible to somehow add a `checkpoint` at the begginning and end of the file, such that I can `restart 1/2` directly to jump to the states? Or maybe separate commands for those two special states?

Or is there some other way to speed up `rr` to allow me to jump to the end of a larger trace? I have tried this:

```
$ rr dump -r-0 | wc
   7579   89070  509458
$ rr replay -g=7579
```

But then the tool just quits directly on me without any output. It works with `-g=7576`, but it's also not faster than just `continue` from the start (i.e. for the above trace it takes ~4-5 seconds). Jumping between checkpoints seems to be faster, but maybe that is already a misconception on my side?

Thanks a lot again for this awesome tool.

**Comment by khuey** [comment]
It would be straightforward to add a shortcut for playing forward to the end of the trace to replay your dump/replay -g sequence. As you have discovered, that doesn't really save any time, though the ergonomics would be easier for you.

rr doesn't store any checkpoints on disk. The checkpoints you create during a debugging session are forks of the replaying processes and are stored in memory. Serializing this state to disk and deserializing it to reconstruct the processes later would be considerable work to implement (this is #2184).

&lt;shameless plug&gt;
If you're interested in a faster (and all around better) debugging experience you could check out our latest project Pernosco, which builds on top of rr. The recorded state is compiled into a big database and then you can jump around instantly. Having all the program state available at once also enables a lot of other cool features.
https://pernos.co/
&lt;/shameless plug&gt;

**Comment by milianw** [comment]
Thank you, that clears it up for me.

I definitely will need to play with Pernosco eventually. Keep up the great work!
