### ISSUE TITLE
how to get changes between two addr?

### ISSUE THREAD

**Issue by iddm** [rr-debugger/rr#2981]
between two addr, if I want to know what registers were changed, what memory was changed, and what was changed , change to what, whatt should i do.
for example:
addr-->addr1:
rdi : orgin->xmodified   rsi: orgin->xmodified  mem： 0x4xxxxxx:orgin->modified

**Comment by rocallahan** [comment]
gdb doesn't support this. You can watch specific addresses using `watch`.
