### ISSUE TITLE
Compile error on Ubuntu 21.10 with gcc 11.2

### ISSUE THREAD

**Issue by heycam** [rr-debugger/rr#2987]
I have a fresh install of Ubuntu 21.10 with gcc 11.2 and I tried to build rr. I ran into this error:

```
[ 48%] Building C object CMakeFiles/at_threadexit.dir/src/test/at_threadexit.c.o
/z/rr/src/test/at_threadexit.c: In function ‘thread’:
/z/rr/src/test/at_threadexit.c:13:3: error: ‘pthread_setspecific’ expecting 1 byte in a region of size 0 [-Werror=stringop-overread]
   13 |   pthread_setspecific(exit_key, (void*)0x1);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /z/rr/src/test/util.h:57,
                 from /z/rr/src/test/at_threadexit.c:3:
/usr/include/pthread.h:1308:12: note: in a call to function ‘pthread_setspecific’ declared with attribute ‘access (none, 2)’
 1308 | extern int pthread_setspecific (pthread_key_t __key,
      |            ^~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

Removing all `-Werror`s from `CMakeLists.txt` makes the build succeed. (There might've been more warnings as errors, I didn't check.)

**Comment by khuey** [comment]
I think the warning is wrong, as far as pthread_getspecific/pthread_setspecific are concerned the pointer is an opaque word sized value.

**Comment by heycam** [comment]
Looks like in my pthread.h the function is annotated with `__attr_access_none (2)` and https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html says a "none" access mode means that the pointer must be null or pointing to a valid object. But I'd be surprised if pthread_setspecific relied on that.

**Comment by khuey** [comment]
This is just a test, we could hack around it by mmapping a bogus page to use as an argument here. I'm pretty sure the annotation in pthread.h is wrong though.

**Comment by pavel-kolesnikov** [comment]
Reproduces on Fedora 35 (`gcc (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1)`)

**Comment by khuey** [comment]
Alright that should fix it.

I complained on the gcc bugzilla too.

**Comment by pavel-kolesnikov** [comment]
> Alright that should fix it.
> 
> I complained on the glibc bugzilla too.

any chance to have a backlink here? @khuey

**Comment by khuey** [comment]
https://sourceware.org/bugzilla/show_bug.cgi?id=27714#c5
