### ISSUE TITLE
RHEL7 /usr/include/linux/videodev2.h doesn't define VIDIOC_QUERY_EXT_CTRL

### ISSUE THREAD

**Issue by wcohen** [rr-debugger/rr#2993]
When trying to do a scratch build of rr-5.5.0 on RHEL 7 the build failed due to RHEL7 missing  VIDIOC_QUERY_EXT_CTRL:

https://koji.fedoraproject.org/koji/taskinfo?taskID=79143940

The error can be seen in the build log:

https://kojipkgs.fedoraproject.org//work/tasks/4012/79144012/build.log

[ 35%] Building CXX object CMakeFiles/rr.dir/src/Registers.cc.o
/usr/bin/c++  -DRR_VERSION=\"5.5.0\" -Drr_EXPORTS -I/builddir/build/BUILD/rr-5.5.0/include -I/builddir/build/BUILD/rr-5.5.0/third-party/proc-service -I/builddir/build/BUILD/rr-5.5.0/third-party/brotli/include -I/builddir/build/BUILD/rr-5.5.0  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -D__USE_LARGEFILE64 -pthread -msse2 -D__MMX__ -D__SSE__ -D__SSE2__ -D__STDC_LIMIT_MACROS -D__STDC_FORMAT_MACROS -std=c++11  -pthread -DNDEBUG   -Wall -Wextra -UDEBUG -DNDEBUG -g3 -flto -o CMakeFiles/rr.dir/src/Registers.cc.o -c /builddir/build/BUILD/rr-5.5.0/src/Registers.cc
/builddir/build/BUILD/rr-5.5.0/src/record_syscall.cc: In function 'rr::Switchable rr::prepare_ioctl(rr::RecordTask*, rr::TaskSyscallState&)':
/builddir/build/BUILD/rr-5.5.0/src/record_syscall.cc:1943:26: error: 'VIDIOC_QUERY_EXT_CTRL' was not declared in this scope
     case IOCTL_MASK_SIZE(VIDIOC_QUERY_EXT_CTRL):

Looks like need a define somewhere for missing  the VIDIOC_QUERY_EXT_CTRL on older distributions.

**Comment by khuey** [comment]
See #2989

**Comment by khuey** [comment]
Should be fixed now.
