### ISSUE TITLE
Support `close_range`

### ISSUE THREAD

**Issue by Bob131** [rr-debugger/rr#2994]
`close_range` is a system call new in Linux 5.9 that allows a set of file descriptors to be closed with a single syscall. It's supported by glibc 2.34 and that support is used by GLib since 2.69.1.

Trying to run a program using GLib's process forking functionality with recent packages (in Fedora: glibc 2.34, GLib 2.70) under rr causes rr to bail out due to the unsupported syscall.

**Comment by rocallahan** [comment]
Should be a trivial fix, PR welcome :-)

**Comment by Bob131** [comment]
Should it? Having a look at the implementations in `record_syscall.cc` of functionally-adjacent syscalls like `close`, there seems to be a need to protect rr-related FDs. It seems as though implementing `close_range` correctly may require splitting an FD range up if an rr FD appears within and submitting multiple calls to `close_range` with the sanitised ranges.

Having a (quick) look through the big switch in `record_syscall.cc`, I can't spot any other syscall handlers that similarly result in multiple syscalls being performed.

**Comment by rocallahan** [comment]
Ok, slightly less than trivial, but not especially hard I guess.

> I can't spot any other syscall handlers that similarly result in multiple syscalls being performed.

I don't see this being a problem. `close_range` ignores close errors so we don't have to worry about which error(s) to return.

**Comment by khuey** [comment]
What arguments is your tracee actually calling close_range with?

**Comment by Bob131** [comment]
the range [4, `UINT_MAX`] with no flags. The relevant lines from `gspawn.c`: [here](https://gitlab.gnome.org/GNOME/glib/-/blob/f8bfd73e30bbd4eb443a07b70bc99a33b7cf4cc2/glib/gspawn.c#L1585) and [here](https://gitlab.gnome.org/GNOME/glib/-/blob/f8bfd73e30bbd4eb443a07b70bc99a33b7cf4cc2/glib/gspawn.c#L1749)

**Comment by khuey** [comment]
Then yeah, we would have to split up the ranges to make sure the rr protected fds are not closed.

**Comment by mistmist** [comment]
i have the same problem as Bob131, can't figure out how to do multiple system calls.

this prototype patch computes the ranges but then only uses 1st one.
(also it doesn't consider the possibility that 0 or UNIT_MAX could be rr fds)

[close_range.txt](https://github.com/rr-debugger/rr/files/7888926/close_range.txt)

**Comment by khuey** [comment]
You can look at SYS_rrcall_detach_teleport's code to see an example of doing multiple syscalls. Basically you will need to call exit_syscall, reset the registers for the next syscall (including the instruction pointer), enter_syscall, repeatedly, for each range that is safe to close.

**Comment by emilio** [comment]
I sent #3140 as a potential alternative to just fake `ENOSYS` rather than dealing with splitting the ranges. Feedback welcome :)
