### ISSUE TITLE
Missing definition of make_unique

### ISSUE THREAD

**Issue by GitMensch** [rr-debugger/rr#2999]
Seen when compiling with GCC 4.8.5 - I see that Dwarf.h, which is included from Dwarf.cc has a definition, but Task.cc, record_syscall.cc and SourcesCommand.cc don't have something similar - should they?

**Comment by rocallahan** [comment]
Why 4.8.5? Do we really need to support that?

If we do, then I guess we can move an implementation to a shared header file.

**Comment by GitMensch** [comment]
4.8.5 is the "cc", gcc is much newer but you've previously said that `cc` should be honored and only overridden by the user (which I commonly do) _and_ it work in previous versions (a year ago I guess).

So... as it _seems_ to be there's an implementation in Drarf.h already, could you please inspect moving this to a shared header file?

**Comment by GitMensch** [comment]
Note: I'm totally open for NOT having it compatible with that old GCC (but it seems to find some stuff like #2998 and it is always nice to have maximum compatibility): but if it isn't then we should explicit say which GCC version is the current minimum and/or let cmake check for explicit functions, here `make_unique` (not sure if/how this is done there, I'm "an autoconf person").

... or we may find it is not necessary / that useful and can adjust the code - the decision is yours to take, I'm just creating an issue that says "doesn't work anymore, so either should work again or be documented [and ideally checked by cmake]).

**Comment by GitMensch** [comment]
Just rechecked: `Dwarf.h` is included in all source files that have `make_unique` since over two years, either directly or via `ElfReader.h`.

I think it is reasonable to have that support, which was added with (4513b23c8092097dc42c73f3cbaf4cfaebd04efe (the commit date alone is pure beauty).

As a quick check I've just copy-pasted that definition into Task.cc and as expected "compile and link works just fine".

``` 
#if __cplusplus == 201103L

/**
 * Implementation of make_unique for C++11 (from https://herbsutter.com/gotw/_102/).
 */
template<typename T, typename ...Args>
std::unique_ptr<T> make_unique( Args&& ...args )
{
    return std::unique_ptr<T>( new T( std::forward<Args>(args)... ) );
}

#endif /* __cplusplus == 201103L */
```
