### ISSUE TITLE
[FATAL /builddir/build/BUILD/rr-5.4.0/src/PerfCounters_x86.h:94:compute_cpu_microarch()] AMD CPU type 0x60f80 unknown

### ISSUE THREAD

**Issue by charlesUnixPro** [rr-debugger/rr#3002]
`processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 23
model		: 104
model name	: AMD Ryzen 7 5700U with Radeon Graphics
stepping	: 1
microcode	: 0x8608102
cpu MHz		: 1400.000
cache size	: 512 KB
physical id	: 0
siblings	: 16
core id		: 0
cpu cores	: 8
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 16
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip rdpid overflow_recov succor smca
bugs		: sysret_ss_attrs spectre_v1 spectre_v2 spec_store_bypass
bogomips	: 3592.89
TLB size	: 3072 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 48 bits physical, 48 bits virtual
power management: ts ttp tm hwpstate cpb eff_freq_ro [13] [14]
`
(Repeats 15 times.)

**Comment by charlesUnixPro** [comment]
$ rr --version
rr version 5.4.0

**Comment by khuey** [comment]
Please try 5.5.0 or the latest master.

**Comment by charlesUnixPro** [comment]
[FATAL /builddir/build/BUILD/rr-5.5.0/src/PerfCounters_x86.h:106:compute_cpu_microarch()] Intel CPU type 0x60f80 unknown

**Comment by charlesUnixPro** [comment]
commit af6c5ab8acac7108db957837abd4e5d2be34dc14 (HEAD -> master, origin/master, origin/HEAD)

[FATAL /home/cac/Projects/rr/src/PerfCounters_x86.h:107:compute_cpu_microarch()] Intel CPU type 0x60f80 unknown

**Comment by charlesUnixPro** [comment]
I tried the simple approach:


$ git diff
diff --git a/src/PerfCounters_x86.h b/src/PerfCounters_x86.h
index 63b970dd..f6017b6d 100644
--- a/src/PerfCounters_x86.h
+++ b/src/PerfCounters_x86.h
@@ -86,6 +86,7 @@ static CpuMicroarch compute_cpu_microarch() {
     case 0x30f10: // Rome, Castle Peak (Zen 2)
     case 0x60f00: // Renoir (Zen 2) (UNTESTED)
     case 0x70f10: // Matisse (Zen 2) (UNTESTED)
+    case 0x60f80: // Lucienne
       if (ext_family == 8) {
         return AMDZen;
       } else if (ext_family == 3) {

and "make tests"

Every test fails:

 205/2713 Test  #205: setitimer-no-syscallbuf ...........................................***Failed  Error regular expression found in output. Regex=[FAILED]  0.19 sec

**Comment by khuey** [comment]
What does `sudo perf list` display on your machine?

**Comment by charlesUnixPro** [comment]
2,581 lines. 

https://drive.google.com/file/d/1tXDnfdEgRPDkpvdzYATofGaBOQaBjlco/view?usp=sharing

**Comment by charlesUnixPro** [comment]
Looking at the test logs, they suggested the zen_workaround.py; ran that and not the tests are passing....  70 down and all good...

**Comment by khuey** [comment]
The `perf list` output appears to show the necessary hardware support.

**Comment by charlesUnixPro** [comment]
921 tests done and still good. If they all pass, I'll generate a pull request.

**Comment by charlesUnixPro** [comment]
1021/2713 Testing: perf_event_mmap-no-syscallbuf
1021/2713 Test: perf_event_mmap-no-syscallbuf
Command: "/usr/bin/bash" "source_dir/src/test/perf_event_mmap.run" "perf_event_mmap" "-n" "bin_dir" "120"
Directory: /home/cac/Projects/obj
"perf_event_mmap-no-syscallbuf" start time: Dec 05 19:14 PST
Output:
----------------------------------------------------------
Test 'perf_event_mmap' FAILED: perf_event_mmap should have caused rr to fail
Test perf_event_mmap failed, leaving behind /tmp/rr-test-perf_event_mmap-kb6mqZtM4
To replay the failed test, run
  _RR_TRACE_DIR=/tmp/rr-test-perf_event_mmap-kb6mqZtM4 rr replay
<end of output>
Test time =   0.11 sec
----------------------------------------------------------
Test Fail Reason:
Error regular expression found in output. Regex=[FAILED]
"perf_event_mmap-no-syscallbuf" end time: Dec 05 19:14 PST
"perf_event_mmap-no-syscallbuf" time elapsed: 00:00:00
----------------------------------------------------------

**Comment by khuey** [comment]
That's #2975

**Comment by charlesUnixPro** [comment]
2262 & 2263 failed "No route to host"; I was offline at the time.
2377L Test 'perf_event_mmap_32' FAILED: perf_event_mmap should have caused rr to fail

**Comment by charlesUnixPro** [comment]
$ ctest -R crash_in_function-32
Test project /home/cac/Projects/obj
    Start 2262: crash_in_function-32
1/2 Test #2262: crash_in_function-32 .................***Failed  Error regular expression found in output. Regex=[FAILED]  6.63 sec
    Start 2263: crash_in_function-32-no-syscallbuf
2/2 Test #2263: crash_in_function-32-no-syscallbuf ...***Failed  Error regular expression found in output. Regex=[FAILED]  6.37 sec

0% tests passed, 2 tests failed out of 2

Total Test time (real) =  13.15 sec

The following tests FAILED:
	2262 - crash_in_function-32 (Failed)
	2263 - crash_in_function-32-no-syscallbuf (Failed)
Errors while running CTest
Output from these tests are in: /home/cac/Projects/obj/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
[cac@multics obj]$ vi /home/cac/Projects/obj/Testing/Temporary/LastTest.log


BFD: warning: system-supplied DSO at 0x6fffd000 has a section extending past end of file
source_dir/src/test/util.sh: line 296: 226279 Aborted                 _RR_TRACE_DIR="$workdir" test-monitor $TIMEOUT debug.err python3 $TESTDIR/$expectscript.py $RR_EXE $GLOBAL_OPTIONS replay -o-n -x $TESTDIR/test_setup.gdb $replayargs
Test 'crash_in_function_32' FAILED: debug script failed

**Comment by charlesUnixPro** [comment]
$ ctest -R perf_event_mmap-32-no-syscallbuf
Test project /home/cac/Projects/obj
    Start 2377: perf_event_mmap-32-no-syscallbuf
1/1 Test #2377: perf_event_mmap-32-no-syscallbuf ...***Failed  Error regular expression found in output. Regex=[FAILED]  0.11 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.26 sec

The following tests FAILED:
	2377 - perf_event_mmap-32-no-syscallbuf (Failed)
Errors while running CTest
Output from these tests are in: /home/cac/Projects/obj/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.



Test 'perf_event_mmap_32' FAILED: perf_event_mmap should have caused rr to fail

**Comment by charlesUnixPro** [comment]
Pull request #3003. The log files from the failed teats are in the request comments.

**Comment by charlesUnixPro** [comment]
It you need any additional testing, I'll be happy to help.

**Comment by khuey** [comment]
This is fixed now, I believe.
