### ISSUE TITLE
Running rr on a multi-process application

### ISSUE THREAD

**Issue by jrenx** [rr-debugger/rr#3007]
Hi rr developers,
We tried to record a multi-process application using rr, but it looked like only the parent process got recorded. Is there a way to ensure the child process also get recorded, or can we choose to record a particular process like you can attach gdb to a process given the process id? Or were we simply not using rr properly?
(Please let me know if I should provide the application.)

Many thanks!

**Comment by khuey** [comment]
Use `rr ps` to see all the processes in the recording, and use `rr replay -p <pid>` to drop into gdb in the selected process.

**Comment by jrenx** [comment]
Thanks so much!!
