### ISSUE TITLE
Suggested testsuite adjustments - LANG and GDB verbosity

### ISSUE THREAD

**Issue by GitMensch** [rr-debugger/rr#3023]
I have no clue where to do this, which is the reason for the missing PR...

1. at beginning of any test: `export LANG=C` (see #3020)
2. when running GDB: do so with `-quiet` to limit output from running verbose test, if/where the version is relevant explicit ask for it with `gdb --version`

**Comment by rocallahan** [comment]
We shouldn't need these, I hope.

**Comment by GitMensch** [comment]
We sadly need the LANG adjustment because the testsuite otherwise fails, see #3020. Exporting `LANG` to `C` fixes this.

**Comment by rocallahan** [comment]
Have you tried https://github.com/rr-debugger/rr/issues/3020#issuecomment-1012915522 though?

**Comment by GitMensch** [comment]
LANG issue seems to be solved with current master (nice done), so the only suggestion left here is to run GDB in quiet mode by default to limit the site of the logs.

**Comment by rocallahan** [comment]
I'd rather just leave it as-is.
