### ISSUE TITLE
Support recording for bpf_lookup_elem

### ISSUE THREAD

**Issue by harjoc** [rr-debugger/rr#3036]
`syscall(__NR_bpf, BPF_MAP_LOOKUP_ELEM, &attr, buffer)` is not supported and there is this comment in https://github.com/rr-debugger/rr/blob/master/src/record_syscall.cc#L2105 :
```
// These are hard to support because we have to track the key_size/value_size :-(
// case BPF_MAP_LOOKUP_ELEM:
```
To record a process that has to call bpf_lookup_elem(), the process could write the known buffer size in `*(size_t *)buffer` and although the kernel won't use it, `prepare_bpf()` could use that size to know how much to record / replay.

I tried doing something similar to how recording of ioctl(SIOCGIFCONF) is handled:
```
case BPF_MAP_LOOKUP_ELEM: {
      auto attrp = syscall_state.reg_parameter<typename Arch::bpf_attr>(2, IN_OUT);
      auto attr = t->read_mem(attrp);

      auto valuep = remote_ptr<size_t>((uintptr_t)attr.value);
      auto bufsize = t->read_mem(valuep);

      syscall_state.mem_ptr_parameter(REMOTE_PTR_FIELD(attrp, value), bufsize);
      return PREVENT_SWITCH;
}
```
but read_mem(attrp) seems to store a "1" into attr.value instead of the process buffer pointer.

Is reading a struct directly using read_mem() like above not supported, or is there something else I'm missing ?

**Comment by rocallahan** [comment]
> To record a process that has to call bpf_lookup_elem(), the process could write the known buffer size in *(size_t *)buffer

We don't want to require program changes for the program to work with rr, if possible.

**Comment by rocallahan** [comment]
The way to go here is to create a BpfMapFileMonitor object derived from FileMonitor and in record_syscall.cc make the bpf(BPF_MAP_CREATE) syscall associate a BpfMapFileMonitor with the returned file descriptor. In BpfMapFileMonitor we would store value_size. Then when we see a successful bpf(BPF_MAP_LOOKUP) we can find the BpfFileMonitor for the fd and we know what the value_size is.
