### ISSUE TITLE
Assumption that no ticks passing between a syscallbuf flush and the succeeding event means the process was SIGKILLed is not backwards compatible

### ISSUE THREAD

**Issue by khuey** [rr-debugger/rr#3041]
We assume that if no ticks pass between a syscallbuf flush and the succeeding event, the succeeding event represents a SIGKILL and is safe to skip. https://github.com/rr-debugger/rr/blob/f99198bc5eb223065de398beced668d2bc801036/src/ReplaySession.cc#L1393-L1399

This is true with the current version of rr because of `force_tick`, but that is not present in older `librrpreload.so`s. This change is not backwards compatible. A Pernosco customer hit this when recording with an rr from June and then uploading to Pernosco (which is on tip). The trace appears to call ptrace(PTRACE_PEEKDATA) repeatedly without intervening conditional branches. Those are handled by the syscallbuf but at some point it fills up and triggers a flush, and then no ticks pass before the next syscall, leading the current rr to believe it can skip the next event. Divergence ensues.

**Comment by khuey** [comment]
Since @rocallahan is on vacation, @Keno what do you think of bumping SYSCALLBUF_PROTOCOL_VERSION (for the first time ever) and gating this new behavior on that?

**Comment by Keno** [comment]
Why not just add a quirk for it in the header like the few other things that changed replay behavior, e.g. https://github.com/rr-debugger/rr/blob/15d418f591224533951278cf77d4f55ffc10d1d7/src/rr_trace.capnp#L108?

**Comment by khuey** [comment]
I suppose that would be the alternative, yeah. Kinda annoying that we have multiple mechanisms for the same thing.
