### ISSUE TITLE
SMI handler execution can appear in rr's tick counts

### ISSUE THREAD

**Issue by khuey** [rr-debugger/rr#3045]
I have observed unreliable conditional branch counts on the `alarm` test on my new i7-1185G7 that render rr unusable.

I suppose the big question at this point is whether this is a kernel issue or a hardware issue.

**Comment by Keno** [comment]
😱 Keep us posted. If need be and I need to help light a fire at Intel, let me know.

**Comment by khuey** [comment]
Downgrading the kernel PMU driver to the Skylake version does *not* fix the problem.

**Comment by khuey** [comment]
Disabling hyper-threading also does not fix the problem.

**Comment by khuey** [comment]
The `alarm` test executes a loop that repeatedly does a calculation and then every N iterations writes a `.` to the terminal. There is a single non-deterministic event, a SIGALRM, that at some point interrupts this loop and exits. The number of retired conditional branches (rcbs) between any two `.` writes should be the same because that part is entirely deterministic. When this fails the recorded number of rcbs is off by arbitrary but potentially vast numbers from what would be expected by simply adding N to the recorded number of rcbs at the previous `.`. (I don't see any obvious patterns in the size of the discrepancy). The value observed during replay does match what would be expected through simple addition.

**Comment by khuey** [comment]
Reached out to a guy we know at Intel to see if we can find an engineer on the relevant stuff.

**Comment by chriselrod** [comment]
```
          Start   16: alarm
  16/2749 Test   #16: alarm .............................................................   Passed    1.87 sec
```
On
```
> head /proc/cpuinfo -n5
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 140
model name      : 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
```
OS is Fedora 35.

However, I did get a few test failures:
```
99% tests passed, 7 tests failed out of 2749

Total Test time (real) = 1946.05 sec

The following tests FAILED:
        450 - x86/pkeys (Failed)
        451 - x86/pkeys-no-syscallbuf (Failed)
        1483 - detach_state-32-no-syscallbuf (Failed)
        1824 - x86/pkeys-32 (Failed)
        1825 - x86/pkeys-32-no-syscallbuf (Failed)
        2296 - crash_in_function-32 (Failed)
        2297 - crash_in_function-32-no-syscallbuf (Failed)
```

**Comment by khuey** [comment]
> [test_failures.txt](https://github.com/rr-debugger/rr/files/7905297/test_failures.txt)
> 
> ```
>           Start   16: alarm
>   16/2749 Test   #16: alarm .............................................................   Passed    1.87 sec
> ```

Can you run it repeatedly. e.g. `ctest -R ^alarm$ --repeat-until-fail 1000`? That should take around half an hour.

> On
> 
> ```
> > head /proc/cpuinfo -n5
> processor       : 0
> vendor_id       : GenuineIntel
> cpu family      : 6
> model           : 140
> model name      : 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
> ```
> 
> OS is Fedora 35.
> 
> However, I did get a few test failures:
> 
> ```
> 99% tests passed, 7 tests failed out of 2749
> 
> Total Test time (real) = 1946.05 sec
> 
> The following tests FAILED:
>         450 - x86/pkeys (Failed)
>         451 - x86/pkeys-no-syscallbuf (Failed)
>         1483 - detach_state-32-no-syscallbuf (Failed)
>         1824 - x86/pkeys-32 (Failed)
>         1825 - x86/pkeys-32-no-syscallbuf (Failed)
>         2296 - crash_in_function-32 (Failed)
>         2297 - crash_in_function-32-no-syscallbuf (Failed)
> ```

These are rr bugs of some sort but they're not (potential) hardware issues.

**Comment by BeastyBlacksmith** [comment]
I ran it on the on a machine with Ubuntu 20.04 and
```
❯ head /proc/cpuinfo -n5
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 140
model name	: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
```
and got 
```
❯ ctest -R ^alarm$ --repeat-until-fail 1000
Test project /home/schrist/projects/rr/obj-rr
    Start 16: alarm
    Test #16: alarm ............................***Failed  Error regular expression found in output. Regex=[FAILED]  0.02 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.06 sec

The following tests FAILED:
	 16 - alarm (Failed)
Errors while running CTest
```

**Comment by khuey** [comment]
> I ran it on the on a machine with Ubuntu 20.04 and
> 
> ```
> ❯ head /proc/cpuinfo -n5
> processor	: 0
> vendor_id	: GenuineIntel
> cpu family	: 6
> model		: 140
> model name	: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
> ```
> 
> and got
> 
> ```
> ❯ ctest -R ^alarm$ --repeat-until-fail 1000
> Test project /home/schrist/projects/rr/obj-rr
>     Start 16: alarm
>     Test #16: alarm ............................***Failed  Error regular expression found in output. Regex=[FAILED]  0.02 sec
> 
> 0% tests passed, 1 tests failed out of 1
> 
> Total Test time (real) =   0.06 sec
> 
> The following tests FAILED:
> 	 16 - alarm (Failed)
> Errors while running CTest
> ```

Can you find /tmp/rr-test-alarm-<random letters and numbers here>/replay.log? What does it say?

**Comment by BeastyBlacksmith** [comment]
```
❯ cat /tmp/rr-test-alarm-1HQoQ7Duz/record.err
rr needs /proc/sys/kernel/perf_event_paranoid <= 1, but it is 4.
Change it to 1, or use 'rr record -n' (slow).
Consider putting 'kernel.perf_event_paranoid = 1' in /etc/sysctl.d/10-rr.conf.
See 'man 8 sysctl', 'man 5 sysctl.d' (systemd systems)
and 'man 5 sysctl.conf' (non-systemd systems) for more details.
```

**Comment by chriselrod** [comment]
> ctest -R ^alarm$ --repeat-until-fail 1000

Okay, now I also got:
```
Test project /home/chriselrod/Documents/libraries/rr/build
    Start 16: alarm
    Test #16: alarm ............................***Failed  Error regular expression found in output. Regex=[FAILED]  0.02 sec

0% tests passed, 1 tests failed out of 1
```

**Comment by khuey** [comment]
> All 1000 tests passed on my i7 1165G7:
> 
> ```
> 1/1 Test #16: alarm ............................   Passed    1.89 sec
> 
> 100% tests passed, 0 tests failed out of 1
> 
> Total Test time (real) = 1899.97 sec
> ```

Great, thanks. What kernel version do you have?

**Comment by chriselrod** [comment]
```
> uname -r
5.15.14-200.fc35.x86_64
```

**Comment by khuey** [comment]
Alright I've been able to reproduce this on Debian 5.15.5-2 so it doesn't seem to be a kernel issue.

**Comment by khuey** [comment]
And someone on Twitter was able to reproduce this on a i7-10610U as well.

**Comment by khuey** [comment]
(which isn't even the same microarchitecture, so that's disturbing)

**Comment by Keno** [comment]
Can you ask people who report errors to include their BIOS/Vendor information? These kinds of things sometimes happens because of SMM interrupts, which is BIOS specific.

**Comment by Keno** [comment]
> These kinds of things sometimes happens because of SMM interrupts, which is BIOS specific.

Might be worth polling `MSR_SMI_COUNT` while you run the tests to see if it correlates with the failure.

**Comment by khuey** [comment]
Hmm, that's an interesting theory. On my machine not all SMIs seem to trigger an overcount but all overcounts seem to be associated with an increase in the value of MSR_SMI_COUNT while rr is running ...

**Comment by Keno** [comment]
Check the kernel setting for this? https://github.com/torvalds/linux/commit/6089327f5424f227bb6a8cf92363c2617e054453

**Comment by khuey** [comment]
I am scared to ask how you know about this stuff :)

**Comment by khuey** [comment]
/sys/device/cpu/freeze_on_smi is 0 by default on this machine and setting it to 1 does appear to make the issue go away. I've run the test 10000 times now with no failures (previously it was failing roughly 1 in 10 times).

**Comment by jkuszmaul** [comment]
My machine (the random twitter user with the i7-10610U also had /sys/devices/cpu/freeze_on_smi defaulted to zero and setting it to 1 seemed to make it stable. Only let it run for a couple hundred iterations of the test, but it had been failing pretty quickly before.

I'm also assuming you meant /sys/devices and not /sys/device, of course.

**Comment by khuey** [comment]
I did mean that. Thanks for testing.

I think we need to add a warning or something to rr when /sys/devices/cpu/freeze_on_smi is 0.

**Comment by GitMensch** [comment]
Looks like I stumbled over this too. Is there any way to warn during cmake?

Should the wiki be adjusted (same place where we mention perf_event_paranoid)?

Is this an RR bug, an Intel/BIOS/Kernel bug or "just an issue that breaks rr"?

**Comment by GitMensch** [comment]
@chriselrod wrote:

> However, I did get a few test failures:
> 
> ```
> 99% tests passed, 7 tests failed out of 2749
> 
> Total Test time (real) = 1946.05 sec
> 
> The following tests FAILED:
>         450 - x86/pkeys (Failed)
>         451 - x86/pkeys-no-syscallbuf (Failed)
>         1483 - detach_state-32-no-syscallbuf (Failed)
>         1824 - x86/pkeys-32 (Failed)
>         1825 - x86/pkeys-32-no-syscallbuf (Failed)
>         2296 - crash_in_function-32 (Failed)
>         2297 - crash_in_function-32-no-syscallbuf (Failed)
> ```

That looks similar to what I currently see (only have more failing tests) but that seems unrelated to this issue - did they still happen (or happen again with current master)? Did you track those down / created separate issues?
