### ISSUE TITLE
Update documentation for zen_workaround.py

### ISSUE THREAD

**Issue by theIDinside** [rr-debugger/rr#3065]
I've solved my issue for not being able to run zen_workaround.py on Ryzen 3700X, and i've seen some other people also encountering this issue (encountering a permission error when trying to run the script)

For my machine, and most likely for theirs as well, UEFI Secure Boot (or rather what AMD boot menu called Windows UEFI, which I set to "Other OS") was turned on and from what I can gather, this makes it so the Linux Kernel prevents writing to MSR; although I have way too little insight to claim this as fact but that's what is suggested online, however, it did solve the problem and now the zen_workaround.py script works.

**Comment by rocallahan** [comment]
Submit a PR that suggests that as a fix when we detect the error?

**Comment by theIDinside** [comment]
Will do!
