### ISSUE TITLE
Should freeze_on_smi message only be there for platforms with vPro?

### ISSUE THREAD

**Issue by sidkshatriya** [rr-debugger/rr#3076]
A fix to prevent performance counters from counting in SMM was recently merged in #3063 . 

I've been running rr on a Tigerlake chip for a few months now. rr runs well and I am able to get 100% (or near it) rr  tests passing. 

Rarely (on long recordings) I have on seen a mysterious over/under count of a few ticks but otherwise I've been quite happy about rr on Tigerlake. (BTW I have `kernel.perf_cpu_time_max_percent=100`)

So I was surprised to see a message urging me to set `freeze_on_smi` to 1 when I compiled rr from master recently.

I'm wondering if this suggestion is necessary for me. My specific chip https://ark.intel.com/content/www/us/en/ark/products/208658/intel-core-i51135g7-processor-8m-cache-up-to-4-20-ghz.html has "Intel vPro Platform Eligibility" as "No" (see link).
 
On https://lore.kernel.org/lkml/7ef1bf66-4184-7f5b-c0bd-351ec743d4e9@linux.intel.com/ Liang Kan wrote:
> I've contacted the author of the white paper. I was told that the change 
is for the client vPro platforms.

So given this fact should I need to make this suggested change at all on my system?

**Comment by rocallahan** [comment]
You probably don't need to, but it won't hurt.

**Comment by rocallahan** [comment]
From the LKML discussion it is likely that freeze_on_smi will be changed to default to 1 on all hardware that supports it.

**Comment by sidkshatriya** [comment]
What I didn't understand fully from the discussion was what exactly does `freeze_on_smi` mean?

Does it mean:
(a) Freeze perf counters on switch to SMM (which sounds benign and useful)
(or more worryingly)
(b) "Freeze" the CPU in some way when you switch to SMM (which sounds a bit more worrying). Because the configuration `/sys/devices/cpu/freeze_on_smi` seems, simply from the naming, to more than just about PMUs. 

I know very little about SMM and SMIs and was wondering if this setting is more than about PMUs only. 

It's tempting to apply this "one weird trick" configuration to the system and just wanted to be more sure...

**Comment by rocallahan** [comment]
It means (a)

**Comment by khuey** [comment]
That the name does not include "perf counters" in it anywhere is unfortunate.

As Andrew Cooper pointed out there's really nothing stopping SMM code from using ring 3 before, so while it's unlikely that non-vPro hardware is affected it's not impossible.
