### ISSUE TITLE
rr replay fails to retrieve interpreter name (saved_ld_path)

### ISSUE THREAD

**Issue by franzpoeschel** [rr-debugger/rr#3082]
After a recent system upgrade (from Ubuntu 21.04 to 21.10), I have no longer been able to use `rr`. Upon invoking `rr replay`, I get the following error message:
```
[FATAL /var/tmp/rr/src/GdbServer.cc:1989:base_addr_from_rendezvous()] Failed to retrieve interpreter name with interpreter_base=0x7f4b3a912000
```
I did some minimal troubleshooting and found out that the function `read_ld_path` (where I think that this value is loaded) does *not* enter the if branch, meaning that the regular return path is invoked: `return t->vm()->mapping_of(interpreter_base).map.fsname()`

After finding out that `interpreter name` refers to something like `/usr/bin/gdb`, I was able to supply that path by hardcoding it into my build, then everything worked without issue again. So, I currently have a functional workaround, but this is still probably a bug.

Further info:

* I observe this in rr 5.4.0, rr 5.5.0 and recent master branch builds
* I use rr inside a [Singularity](https://sylabs.io/guides/3.0/user-guide/quick_start.html) container (similar to Docker containers) based on the `nvidia/cuda:11.1-devel-ubuntu20.04` image

**Comment by rocallahan** [comment]
What does `t->vm()->mapping_of(interpreter_base)` return in `read_ld_path()`?

What does `/proc/<pid>/maps` contain for `t->tid`? and what is the value of `interpreter_base`?

**Comment by franzpoeschel** [comment]
`interpreter_base=0x7f5e4ff08000`

Content at `/proc/837512/maps`:
```
68000000-68200000 rwxp 00000000 00:00 0 
6fffd000-70000000 r-xp 00000000 103:06 115742956                         /home/franzpoeschel/.local/share/rr/ls-3/mmap_hardlink_3_librrpage.so
70000000-70001000 r-xp 00004000 103:06 115742956                         /home/franzpoeschel/src/rr/build/lib/rr/librrpage.so
70001000-70002000 rw-s 00000000 103:02 24551178                          /tmp/franzpoeschel/rr-shared-preload_thread_locals-837512-0 (deleted)
56341cda4000-56341cda8000 r--p 00000000 00:00 0 
56341cda8000-56341cdbc000 r-xp 00004000 103:06 115353148                 /home/franzpoeschel/.local/share/rr/ls-3/mmap_copy_5_ls
56341cdbc000-56341cdc5000 r--p 00000000 00:00 0 
56341cdc6000-56341cdc9000 rw-p 00000000 00:00 0 
7f5e4ff07000-7f5e4ff08000 r-xp 00000000 00:00 0 
7f5e4ff08000-7f5e4ff09000 r--p 00000000 00:00 0 
7f5e4ff09000-7f5e4ff2c000 r-xp 00001000 103:06 115353173                 /home/franzpoeschel/.local/share/rr/ls-3/mmap_copy_11_ld-2.31.so
7f5e4ff2c000-7f5e4ff34000 r--p 00000000 00:00 0 
7f5e4ff35000-7f5e4ff38000 rw-p 00000000 00:00 0 
7fff050a0000-7fff050cb000 rw-p 00000000 00:00 0 
ffffffffff600000-ffffffffff601000 --xp 00000000 00:00 0                  [vsyscall]
```

Output of  `t->vm()->mapping_of(interpreter_base).map.str()`:
```
0x7f5e4ff08000-0x7f5e4ff09000 r--p 00000000 00:00 0          
```
Output of `t->vm()->mapping_of(interpreter_base).recorded_map.str()`:
```
0x7f5e4ff08000-0x7f5e4ff09000 r--p 00000000 00:41 24721479   /usr/lib/x86_64-linux-gnu/ld-2.31.so
```

**Comment by franzpoeschel** [comment]
I tried replacing `return t->vm()->mapping_of(interpreter_base).map.fsname()` with `return t->vm()->mapping_of(interpreter_base).recorded_map.fsname();` (`map` becomes `recorded_map`) and now rr works again for me. Since I'm just toying around without really knowing what I'm doing, I don't know if this can be a general solution for the issue.

**Comment by rocallahan** [comment]
We actually want `/home/franzpoeschel/.local/share/rr/ls-3/mmap_copy_11_ld-2.31.so` to be the result here so that replay works even when the replay machine doesn't have the original file.

**Comment by rocallahan** [comment]
Can you do `rr dump -b -m -p` and put the output somewhere I can read it?

**Comment by rocallahan** [comment]
```
  { map_file:"/usr/lib/x86_64-linux-gnu/ld-2.31.so", addr:0x7f5e4ff08000, length:0x1000, prot_flags:"r--p", file_offset:0x0, device:65, inode:24721479, data_file:"", data_offset:0x0, file_size:0x2ebf0 }
  { map_file:"/usr/lib/x86_64-linux-gnu/ld-2.31.so", addr:0x7f5e4ff09000, length:0x23000, prot_flags:"r-xp", file_offset:0x1000, device:65, inode:24721479, data_file:"/home/franzpoeschel/.local/share/rr/ls-3/mmap_copy_11_ld-2.31.so", data_offset:0x1000, file_size:0x2ebf0 }
```
I wonder why the first line has an empty `data_file` but the second has a reasonable one. On my system, `data_file` is populated in both entries:
```
 { map_file:"/usr/lib64/ld-2.33.so", addr:0x7f6ea95e8000, length:0x1000, prot_flags:"r--p", file_offset:0x0, device:48, inode:17750462, data_file:"/usr/lib64/ld-2.33.so", data_offset:0x0, file_size:0xcdd30 }
  { map_file:"/usr/lib64/ld-2.33.so", addr:0x7f6ea95e9000, length:0x25000, prot_flags:"r-xp", file_offset:0x1000, device:48, inode:17750462, data_file:"/usr/lib64/ld-2.33.so", data_offset:0x1000, file_size:0xcdd30 }
```

**Comment by rocallahan** [comment]
OK, I can reproduce this by setting `RR_COPY_ALL_FILES=1` when recording.

**Comment by rocallahan** [comment]
BTW, whatever your container setup is, it's forcing rr to copy all data into the trace, which can be pretty slow. Maybe all the files are in a tmpfs or something like that? If so `RR_TRUST_TEMP_FILES=1` might help you.

**Comment by franzpoeschel** [comment]
Everything happens in the home directory which is mounted into the container, so normally there should be no tmpfs involved, but I can try if it changes anything. I will also try if the fix solves the issue that I saw.

**Comment by franzpoeschel** [comment]
Yes, I can confirm that this fixed the issue that I saw :)
