### ISSUE TITLE
Documentation request: is `(gdb) call` now allowed?

### ISSUE THREAD

**Issue by DilumAluthge** [rr-debugger/rr#3085]
Currently, the slideshow[^1] on the website says:

> `(gdb) call foo()` can cause replay divergence. 
>
> So you're not allowed to do it … for now. Support coming.

Is this statement still accurate? Or does rr now support `(gdb) call`? If so, it would be useful to document somewhere that `(gdb) call` is now allowed.

[^1]: https://rr-project.org/rr.html#77.0

**Comment by khuey** [comment]
That's wrong, `call Foo()` won't disrupt replay.

**Comment by rocallahan** [comment]
Where did you find a link to that presentation? A lot of it is obsolete. Maybe we should just delete it.

**Comment by DilumAluthge** [comment]
> Where did you find a link to that presentation?

Hmmm, good question. I'm not sure; I think it came up as a Google search result.
