### ISSUE TITLE
Any known rr limitations related to epoll?

### ISSUE THREAD

**Issue by jiridanek** [rr-debugger/rr#3086]
I have a program which can be configured to use either the epoll or libuv event loop. When I use epoll, it misbehaves under rr in about 50% of cases (but runs 100% fine outside of it, or close to 100%, I guess I can be never sure). When I use libuv, the tests run fine with or without rr.

What happens is that the program is started two times, first process opens some listening sockets, and the second instance connects to one of these. What I am observing with epoll is that the first instance often never accepts the connection. (Does not call `accept()`.)

Is there any known issue or gap regarding epoll support in rr, or should I prioritize looking for a bug in my epoll code?

(I saw https://github.com/rr-debugger/rr/issues/3058 and I am hoping to save effort if there is similar limitation for epoll.)

**Comment by Keno** [comment]
libuv uses `epoll` internally, so as far as that surface goes it's well exercised. I don't believe there are any known rr/epoll bugs. Not to say there couldn't be any, but my bet would be on a data race in the epoll code that gets triggered by scheduling differences.

**Comment by Keno** [comment]
Another guess: Are you handling EINTR correctly? There's a general linux issue where attaching a ptracer can cause extra EINTRs that weren't seen before. Maybe see if it fails under `strace`?

**Comment by jiridanek** [comment]
It's running fine under `strace`.

I guess there is no point in leaving this open, since this is work item for me, not for rr, at this point. I'd welcome any suggestions or advice, of course. I'll update this if I figure out anything.

**Comment by khuey** [comment]
Have you tried it with and without syscall buffering (i.e. with `rr record` and `rr record -n` respectively)?

**Comment by jiridanek** [comment]
> with and without syscall buffering

I tried that now. The tests are passing with `rr record -n` and getting stuck with `rr record`. What does that mean?

**Comment by jiridanek** [comment]
Eventually, upon sufficient number of retries, I got the tests stuck with `rr record -n` as well. So, it is lot less likely, but still possible. I'll go investigate that recording in gdb, if maybe I can notice something I did not see before.
