### ISSUE TITLE
More chaos schedules when recording?

### ISSUE THREAD

**Issue by zouyonghao** [rr-debugger/rr#3087]
Recent I am using rr for finding concurrent bugs, and test it with following example code
```
int main()
{
	i = mmap(NULL, sizeof(int), PROT_READ | PROT_WRITE,
			 MAP_SHARED | MAP_ANONYMOUS, -1, 0);
	if (fork() == 0)
	{
		thread_function1(NULL);
		return 0;
	}
	if (fork() == 0)
	{
		thread_function2(NULL);
		return 0;
	}

	return 0;
}

void *thread_function1(void *arg)
{
	for (int j = 0; j < 50; j++)
	{
		(*i)++;
		printf("i = %d!\n", *i);
	}
	return NULL;
}

void *thread_function2(void *arg)
{
	printf("function2 called, *i = %d\n", *i);
	if ((*i) == 30)
	{
		printf("We got a bug!\n");
		exit(-1);
	}
	return NULL;
}
```

Without rr, the bug is triggered for about 200~1000 runs.
But with rr (I test with `rr -h -w -s`), the bug is triggered for more than 3000 runs.

Maybe we should add more chaos schedules with some methods like injecting `sched` call to binary?

**Comment by rocallahan** [comment]
Honestly I think this is probably good enough. We could increase the frequency of catching this race by assigning more weight to very short context switching intervals, but that would hurt other cases.
