### ISSUE TITLE
Can I debug rr using gdb?

### ISSUE THREAD

**Issue by zouyonghao** [rr-debugger/rr#3088]
I know for now rr can not debug itself, but can I debug rr with gdb?
When I try, I got an exception and the breakpoints do not work.
```
Program received signal SIGSEGV, Segmentation fault.
0x0000555555ad45f7 in rr::cpuid (code=0, subrequest=0) at /home/zyh/rr/src/util.cc:861
861                    : "a"(code), "c"(subrequest));
```

**Comment by bernhardu** [comment]
Is it working to just continue from there e.g. `(gdb) cont` ?

**Comment by zouyonghao** [comment]
Hi @bernhardu 
Ah, sry it seems working for me!

**Comment by rocallahan** [comment]
FWIW you can debug rr replay with rr.
