### ISSUE TITLE
Should use FICLONE instead of BTRFS_IOC_CLONE

### ISSUE THREAD

**Issue by khuey** [rr-debugger/rr#3091]
Per `man 2 ioctl_ficlonerange` FICLONE has superseded BTRFS_IOC_CLONE. This first appeared in kernel 4.5 so we'll need to continue to fall back to the old ioctl.

**Comment by rocallahan** [comment]
They're the same ioctl number.

**Comment by khuey** [comment]
Oh, lol, that's a really misleading man page.
