### ISSUE TITLE
Handling applications that expect `rseq` `cpu_id` to fit into an array of size `sysconf(_SC_NPROCESSORS_ONLN)` or `sysconf(_SC_NPROCESSORS_CONF)`

### ISSUE THREAD

**Issue by rocallahan** [rr-debugger/rr#3105]
An application I'm looking at uses `cpu_id` from `struct rseq` to index into an array whose size of determined by `sysconf(_SC_NPROCESSORS_ONLN)`. I think that is a bug in the application. This causes the application to crash immediately when run under rr because rr reports 1 for `_SC_NPROCESSORS_ONLN` and higher index values in `struct rseq`.

If I try to get the application fixed, then one big question is how it should size the array. I don't have a good answer to that :-(. I guess `sysconf(_SC_NPROCESSORS_CONF)` would be better than `_SC_NPROCESSORS_ONLN`; is there anything better than that? (Dynamically resizing the array is probably out of the question; the concurrency issues would be extremely difficult to resolve, if it's possible at all.) Currently we're overriding `sysconf(_SC_NPROCESSORS_CONF)` to return 1 as well, so I think we might have to stop doing that.

We could "fix" rr by scrapping the `sysconf` overrides, and also the override of `"/sys/devices/system/cpu/online"`, but obviously those are there for a reason. I guess I could hack `rseq` emulation to return a `cpu_id` of 0 always, but making that inconsistent with `getcpu` and CPUID and affinity masks etc sounds like a pretty bad idea in the long term.

@Keno any thoughts?

**Comment by khuey** [comment]
I think the most correct answer here is to read the range in  /sys/devices/system/cpu/possible. This is what e.g. BPF_MAP_TYPE_PERCPU_ARRAY uses.

**Comment by rocallahan** [comment]
Latest glibc code implements `_SC_NPROCESSORS_CONF` by enumerating CPUs under `/sys/devices/system/cpu`. If that fails it falls back to `/proc/stat`, and if that fails, `sched_getaffinity`. Linux populates `/sys/devices/system/cpu` based on the number of *present* CPUs (`/sys/devices/system/cpu/present`) which is a superset of `possible`.

**Comment by Keno** [comment]
I pretty much agree with your analysis. CPUs can be offlined at any point so there's no guarantee that `_SC_NPROCESSORS_ONLN` has any relation to cpu numbers. I'm not entirely sure what happens on true hotplug systems (mostly because I've never actually seen one in person), but the man page seems to suggest that `_SC_NPROCESSORS_CONF` is an upper bound for those also (though I'm somewhat skeptical of that). Regardless, it seems reasonable for rr to emulate all but the bound cpu being offlined from the point of view of the tracee.

**Comment by khuey** [comment]
I'm confident that `present` is a subset of `possible`, not a superset.

**Comment by rocallahan** [comment]
You're right of course :-(. So there isn't a `sysconf` value that does what we want here, strictly speaking. Applications would have to parse `/sys/devices/system/cpu/possible`. In Github I see a couple of applications doing that, but only a couple. I think rather than treat every application not parsing `possible` as broken, we should support applications that are using `_SC_NPROCESSORS_CONF` even though it's not technically correct.

**Comment by rocallahan** [comment]
I've filed https://sourceware.org/bugzilla/show_bug.cgi?id=28991 to encourage glibc to use `/sys/devices/system/cpu/possible` to implement `_SC_NPROCESSORS_CONF`.
