### ISSUE TITLE
Instructions for locally reproducing the CI sandbox

### ISSUE THREAD

**Issue by DilumAluthge** [rr-debugger/rr#3115]
```
git clone https://github.com/JuliaCI/rootfs-images.git
cd rootfs-images
julia --project -e 'import Pkg; Pkg.instantiate()'
julia --project test_rootfs.jl --treehash $ROOTFS_TREEHASH --url $ROOTFS_URL
```

You get the values of `ROOTFS_URL` and `ROOTFS_TREEHASH` by looking at the [`pipeline.yaml`](https://github.com/rr-debugger/rr/blob/master/.buildkite/pipeline.yml#L12) file.

Note: if you are looking at the CI run for a PR, you should get the `ROOTFS_URL` and `ROOTFS_TREEHASH` values from the `pipeline.yaml` on the PR branch (instead of the `master` branch).

**Comment by Keno** [comment]
I've moved this to the wiki here: https://github.com/rr-debugger/rr/wiki/Instructions-for-locally-reproducing-the-CI-sandbox. Probably a better place than the issues.

**Comment by rocallahan** [comment]
How do I get a buildkite archive into the sandbox so I can try to replay it? With a local rr build? The host fs doesn't seem to be mounted in the sandbox.

**Comment by Keno** [comment]
There's a `build` directory that is shared between host and sandbox. I just usually dump the rr source tree in there and the unpacked buildkite archive and then build rr inside the sandbox.

**Comment by DilumAluthge** [comment]
So, after you do

```
git clone https://github.com/JuliaCI/rootfs-images.git
cd rootfs-images
```

When you are in the `rootfs-images` folder, do `mkdir -p build`. And then copy the files you want into the `build` directory.

Then, when you run the `test_rootfs.jl` sfropr and enter the sandbox, the folder that was `rootfs-images/build` outside the sandbox will be mounted at `/build` inside the sandbox.

@Keno We should add that to the wiki.

**Comment by rocallahan** [comment]
How do I get root inside the sandbox to install stuff?

**Comment by DilumAluthge** [comment]
Hmmm. I'm not sure if it's possible to be root inside the sandbox.

Some ideas:

1. You can install software on your host system (e.g. in a folder named `/path/to/folder/on/host/system` on your host system), and then map the `/path/to/folder/on/host/system` folder into the sandbox. To do so, you would edit the `test_rootfs.jl` script. Here is an example of how you would edit it: [JuliaCI/rootfs-images#172](https://github.com/JuliaCI/rootfs-images/pull/172)
2. You could make a PR to edit the recipe for building the rootfs image itself, and then the software will be available in the rootfs image itself. Here is an example of such a PR: [JuliaCI/rootfs-images#173](https://github.com/JuliaCI/rootfs-images/pull/173)

@staticfloat Any other recommendations?

**Comment by staticfloat** [comment]
> Hmmm. I'm not sure if it's possible to be root inside the sandbox.

It's quite easy; modify [these two lines](https://github.com/JuliaCI/rootfs-images/blob/9d196ff02711c1a2982c9508499ff6bb01a50a12/test_rootfs.jl#L47-L48) to use `0` instead of the current UID and GID.
