### ISSUE TITLE
CI: Intermittent failure in async_kill_with_syscallbuf

### ISSUE THREAD

**Issue by Keno** [rr-debugger/rr#3119]
https://buildkite.com/julialang/rr/builds/220#f25b96e7-4801-431b-88e7-09871a7c076f

```
280/2761 Test  #854: async_kill_with_syscallbuf ........................................***Failed  Error regular expression found in output. Regex=[FAILED]  6.97 sec

Successfully delivered signal 9 to 'async_kill_with_syscallbuf-3QUc6jWO3'

source_dir/src/test/util.sh: line 245: 116094 Killed                  _RR_TRACE_DIR="$workdir" test-monitor $TIMEOUT record.err $RR_EXE $GLOBAL_OPTIONS record $LIB_ARG $RECORD_ARGS "$exe" $exeargs > record.out 2> record.err

source_dir/src/test/util.sh: line 278: 124304 Aborted                 _RR_TRACE_DIR="$workdir" test-monitor $TIMEOUT replay.err $RR_EXE $GLOBAL_OPTIONS replay -a $replayflags > replay.out 2> replay.err

Test 'async_kill_with_syscallbuf' FAILED: : error during replay:

--------------------------------------------------

[FATAL /cache/build/exclusive-amdci3-0/julialang/rr/src/ReplaySession.cc:667:check_pending_sig()] 

 (task 124357 (rec:116311) at time 658)

 -> Assertion `false' failed to hold. Replaying `SCHED': expecting tracee signal or trap, but instead at `write' (ticks: 37493385)

Tail of trace dump:

{

  real_time:45195640.732518 global_time:638, event:`SYSCALLBUF_ABORT_COMMIT' tid:116311, ticks:35023168

}
```

**Comment by rocallahan** [comment]
`SIGKILL` nuked the tracee at address 0x7000000e, which is the instruction after an untraced syscall (a `write` in this case). We didn't get to add a syscallbuf record for this syscall. So during replay we flush the syscalls that did get recorded, and then try to replay to the `SCHED` at 0x7000000e. That `SCHED` replay fails in `start_commit_buffered_syscall` because the buffer is empty.

Not sure what if anything we can do about this.

**Comment by rocallahan** [comment]
Actually, we should have handled this in `handle_ptrace_exit_event`, by setting `event.Sched().in_syscallbuf_syscall_hook` to indicate that we're in syscallbuf code. But that value is null in the recording :-(. Presumably `RecordTask::is_in_syscallbuf()` return false, but I can't see why that would happen. We should have taken the `is_in_rr_page()` path, read the return address from the stack, and determined that that was in syscallbuf code.

**Comment by rocallahan** [comment]
Maybe we failed to read the stack word...

**Comment by rocallahan** [comment]
ff0d93586650aa2a7f3b209e2be410b11d8a3f0d might fix this. At least it will narrow down the problem if it happens again.
