### ISSUE TITLE
choose_cpu can choose offline CPU

### ISSUE THREAD

**Issue by Keno** [rr-debugger/rr#3122]
In choose_cpu, we read the cgroup config (previously out of the cgroup config itself, now out of `/proc/self/status`).
However, merely being permitted to run on a CPU by cgroup is not sufficient to guarantee that setaffinity will succeed.
In particular, if the CPU is offline (or being offlined), attempting to restrict it to this core by affinity will fail.
We could read the currently online CPUs out of `cat /sys/devices/system/cpu/online`. However that re-introduces
the problem that we don't want to assume that `/sys` is mounted (since it often isn't inside containers).
I think the best way to do it probably is to refactor the code to check if setaffinity succeeds and (in the rare
case that it doesn't, because the CPU is offline), just retry with the next CPU on the list.

**Comment by Keno** [comment]
(I plan to fix this, but won't get to it tonight, so just writing down my thoughts here for when I do get to it).

**Comment by rocallahan** [comment]
Should have been fixed by #3178.
