### ISSUE TITLE
CI: Intermittent failure in blacklist-32

### ISSUE THREAD

**Issue by Keno** [rr-debugger/rr#3124]
https://buildkite.com/julialang/rr/builds/239#9ca4d928-ff17-4a27-beda-e0d9839e167e
```

1956/2761 Test #2254: blacklist-32 ......................................................***Failed  Error regular expression found in output. Regex=[FAILED]  0.20 sec
--
  | source_dir/src/test/util.sh: line 245: 14050 Aborted                 _RR_TRACE_DIR="$workdir" test-monitor $TIMEOUT record.err $RR_EXE $GLOBAL_OPTIONS record $LIB_ARG $RECORD_ARGS "$exe" $exeargs > record.out 2> record.err
  | Test 'blacklist_32' FAILED: : token 'EXIT-SUCCESS' not in record.out:
  | --------------------------------------------------
  | FAILED: errno=2 (No such file or directory)
  | FAILED: !fd < 0
  | --------------------------------------------------
  | Test blacklist_32 failed, leaving behind /cache/build/dockerized-amdci4-7/julialang/rr/obj/my_temp_parent_dir/jl_fYLzrv/rr-test-blacklist_32-HNG84BnE8
  | To replay the failed test, run
  | _RR_TRACE_DIR=/cache/build/dockerized-amdci4-7/julialang/rr/obj/my_temp_parent_dir/jl_fYLzrv/rr-test-blacklist_32-HNG84BnE8 rr replay
  |  


```
Not really sure what's going on here.

**Comment by rocallahan** [comment]
The `open` syscall that succeeded when it shouldn't have:
```
  real_time:45349159.871975 global_time:181, event:`SYSCALL: open' (state:EXITING_SYSCALL) tid:14095, ticks:52048
eax:0x6 ecx:0x0 edx:0x93ab ebx:0x5656a030 esp:0x681ffe00 ebp:0x0 esi:0x0 edi:0x0 eip:0x7000000e eflags:0x246 xcs:0x23 xss:0x2b xds:0x2b xes:0x2b xfs:0x0 xgs:0x63 orig_eax:0x5
```
One thing that's weird is that there's no syscallbuf activity here. Maybe the initial untraced `open()` call was interrupted by a context switch and we ran the deschedule logic and that caused the test to fail?

**Comment by rocallahan** [comment]
Hmm, `check_file_open_ok` returns the file descriptor unmodified if `did_abort` is true...

**Comment by khuey** [comment]
This change is wrong in the presence of seccomp. did_abort will be true and the ret will be an arbitrary value. In Pernosco's `io-viewer` test the open is for a non-existent file and the return value is 2, so `check_file_open` will now close stderr and then fail to reopen it, leaving stderr broken for the rest of the process.

**Comment by rocallahan** [comment]
Ugh.

**Comment by rocallahan** [comment]
https://github.com/rr-debugger/rr/commit/6ae2843e4ca725658fd7b517479ef742c6363d1d should fix that.
