### ISSUE TITLE
feature request: way to start gdb session at end of rr recording

### ISSUE THREAD

**Issue by pm215** [rr-debugger/rr#3131]
Often when I'm recording a failure with rr, there's a relatively long lead-up to the point of failure, which is right at the end of the trace because the debuggee asserts or crashes. When I then use 'rr replay' I have to sit through the debuggee re-running from the start to the point of failure. It would be nice if rr provided a mechanism for "go directly to the last record you have for the debuggee". If I knew the rr event number I could use the replay '-g' option or the optional argument to the gdb 'run' command, but I typically don't. If those commands accepted some syntax for "last event, whatever that is" that would be a time-saver, I think. (It's tempting to suggest a python-style negative-numbers-mean-count-backwards-from-the-end, but that might be a bit confusing.)

Apologies if this functionality already exists, but I didn't find it mentioned in https://github.com/rr-debugger/rr/wiki/Usage

**Comment by pm215** [comment]
Thanks! I updated the wiki usage page to add a brief mention of it:
https://github.com/rr-debugger/rr/wiki/Usage/_compare/5d28ee134f30fd5018d2c658c5cde4793a9445e4...ffe3b58deff15a5cec4732c1eb6c82deb5049961

(let me know if you'd prefer me to revert that or do something else)

**Comment by khuey** [comment]
lgtm. I added https://github.com/rr-debugger/rr/wiki/Usage/_compare/ffe3b58deff15a5cec4732c1eb6c82deb5049961...ed85ee66bc587aa53d07d302cc0a15791ea1481a too.
