### ISSUE TITLE
force32bit: rseq test is timing out

### ISSUE THREAD

**Issue by bernhardu** [rr-debugger/rr#3133]
I was doing yesterday another test run with current git head, and found that `rseq` test started to timeout with a force32bit-built-rr.
This seems to happen on the replay side of the test.
A bisect leads to 86df27c236632a3e5cbb87989c4a2f5aaa2a08dd, but that commit did more or less just add some zlib linking, so this might just trigger some side effect.

Trying to get some more information it looks like having 32-bit code involved increases chances to hit such "aborts" when just recording:
```
64-bit rr with 64-bit rseq:    20 runs,  2 with aborts (maximum 1 aborts/jump aborts)
64-bit rr with 32-bit rseq_32: 20 runs, 10 with aborts (maximum 1 aborts/jump aborts)
32-bit rr with 32-bit rseq:    20 runs, 20 with aborts (maximum 24 aborts/jump aborts, minimum 7)
```

With a force32bit-built-rr with 86df27c236632a3e5cbb87989c4a2f5aaa2a08dd reverted I got the test succeed with :
 `1/1 Test #1068: rseq .............................   Passed   47.07 sec`
While just running the replay interactively without 86df27c236632a3e5cbb87989c4a2f5aaa2a08dd I got still a replay time of `4m31.938s` with the same binary.
So 86df27c236632a3e5cbb87989c4a2f5aaa2a08dd makes it just show up in the test also, while replaying interactively did show it already without it - but I cannot say what causes this different replay behaviour between test and interactive.

With increasing timeout like below I also get ctest pass the test with having 86df27c236632a3e5cbb87989c4a2f5aaa2a08dd applied:
`1/1 Test #1068: rseq .............................   Passed  471.85 sec`
```diff
diff --git a/src/test/rseq.run b/src/test/rseq.run
index 8c50fa26..aa98d05a 100644
--- a/src/test/rseq.run
+++ b/src/test/rseq.run
@@ -1,4 +1,7 @@
 source `dirname $0`/util.sh
+if [[ "$(file $RESOURCE_PATH/lib/rr/librrpage.so | grep 32-bit -c)" == "1" ]]; then
+    if [ $TIMEOUT -lt 600 ]; then TIMEOUT=600; fi
+fi
 compare_test EXIT-SUCCESS
 # Skip debug script test if there were no jumps to abort_ip
 grep -q ", 0 jump aborts" record.out
```

I have tried to leave the test if a few "aborts" are collected, and this made the test also fast enough to stay within unmodified timeout, but I am not certain if this maintains the purpose of the test:
```diff
diff --git a/src/test/rseq.c b/src/test/rseq.c
index 06ff92a2..9232ce00 100644
--- a/src/test/rseq.c
+++ b/src/test/rseq.c
@@ -106,7 +106,7 @@ static int main_child(void) {
   child = fork();
   if (!child) {
     char* exec_argv[] = { passed_argv[0], passed_argv[0], NULL };
-    for (i = 0; i < 300000000; ++i) {
+    for (i = 0; i < 300000000 && aborts < 5; ++i) {
       do_section();
     }
 
```

And this might be somehow related to #3118, but created this issue as I am not sure about this.

I observed this with a current Debian bookworm/testing running at a AMD Ryzen 7 1700, with kernel 5.16.14-1.

**Comment by rocallahan** [comment]
So you're saying it's just really really slow but always passes eventually if we give it long enough?

**Comment by bernhardu** [comment]
Yes, that is the impression I got, if do all 300000000 iterations.

**Comment by rocallahan** [comment]
My hypothesis is:
* There are 1000 `SCHED` events to replay for `main_child_thread`
* Zen has a 10,000 tick skid
* We retire 3 conditional branches per iteration of the loop around `do_section`
* So each replay of a `SCHED` sets a breakpoint at the address where the `SCHED` happens, and then stops at that breakpoint about 10,000/3 times while we march forward looking for the correct state to stop in.
* So that's about 3.3M "continue to breakpoint" operations, which is a lot, and takes a very long time.

Bumping the skid value on my system (Skylake) to 10,000 increase replay time from 2s to 11s. So that is definitely a big slowdown, but not nearly enough to cause the test to fail, so I'm not sure if this is the true explanation.

**Comment by rocallahan** [comment]
Maybe all those context switches are much more expensive on a loaded system due to CPU migrations or something?

**Comment by rocallahan** [comment]
I get similar results when building with force32bit=TRUE.

**Comment by rocallahan** [comment]
> While just running the replay interactively without https://github.com/rr-debugger/rr/commit/86df27c236632a3e5cbb87989c4a2f5aaa2a08dd I got still a replay time of 4m31.938s with the same binary.

@bernhardu so I guess the question is, why is this replay so slow for you? Maybe try some "poor man's profiling" where you attach gdb to `rr replay` and `continue`/ctrl-C several times to get some stacks of what rr is doing?

**Comment by rocallahan** [comment]
Might also be worth posting an `rr dump -b -m -p` somewhere to verify that it doesn't look strange.

**Comment by bernhardu** [comment]
~~Was your experiment with a force32bit-build?~~
I was about to ask, but was not fast enough.

Because with a regular build I also don't get somewhere near the timeout of 120 seconds:
```
real    0m1.619s: time bin/rr record bin/rseq       # 64-bit rr with 64-bit test
real    0m1.681s: time bin/rr replay -a rseq-205

real    0m2.282s: time bin/rr record bin/rseq_32    # 64-bit rr with 32-bit test
real    0m8.240s: time bin/rr replay -a rseq_32-65

real    0m2.542s: time bin/rr record bin/rseq       # force32bit
real   3m44.230s: time bin/rr replay -a rseq-206
```
I tried to run the replay with `perf record -g time bin/rr replay -a rseq-206` and looking at the result with `hotspot`.
But with my untrained eyes I don't see much difference to a the second 64-bit-rr-with-32-bit run.
The function calls below emulate_async_signal are add_breakpoint, remove_breakpoint, so kind of related to your previous hypothesis. But could not identify a single long taking function ...

force32bit:
![grafik](https://user-images.githubusercontent.com/10096970/162071994-b086ce8e-4510-4296-aba7-2ac5c8e46e80.png)

64-bit rr with 64-bit rseg:
![grafik](https://user-images.githubusercontent.com/10096970/162072547-ad5cfb45-a2d2-4655-bf94-343d757e23b3.png)

**Comment by bernhardu** [comment]
I am unsure if this dump is ok because of its small size?
```
$ git describe --always --tag
5.5.0-174-g4d5f0635

$ time bin/rr record bin/rseq    
rr: Saving execution to trace directory `/home/bernhard/data/entwicklung/2022/rr/rr-recordings/rseq-207'.
child 655809
Detected 22 aborts, 22 jump aborts
EXIT-SUCCESS

real    0m2.391s
user    0m2.148s
sys     0m0.211s

$ time bin/rr replay -a rseq-207
child 655809
Detected 22 aborts, 22 jump aborts
EXIT-SUCCESS

real    3m47.605s
user    2m0.560s
sys     1m9.045s

$ bin/rr dump -b -m -p rseq-207 > force32-bit-rseq_test_taking_long_dump.txt

$ zip force32-bit-rseq_test_taking_long_dump.txt.zip force32-bit-rseq_test_taking_long_dump.txt
  adding: force32-bit-rseq_test_taking_long_dump.txt (deflated 94%)

$ ls -lisah for*
151732681 996K -rw-r--r-- 1 bernhard bernhard 993K Apr  6 23:37 force32-bit-rseq_test_taking_long_dump.txt
151732690  56K -rw-r--r-- 1 bernhard bernhard  55K Apr  6 23:41 force32-bit-rseq_test_taking_long_dump.txt.zip
```

[force32-bit-rseq_test_taking_long_dump.txt.zip](https://github.com/rr-debugger/rr/files/8431999/force32-bit-rseq_test_taking_long_dump.txt.zip)

**Comment by rocallahan** [comment]
> I tried to run the replay with perf record -g time bin/rr replay -a rseq-206

This is sampling according to CPU cycles in rr, so it doesn't show time spent waiting for the tracee or in context switching.

Try `perf record -a` to record all CPUs? Or do the gdb thing I suggested.

**Comment by rocallahan** [comment]
> [force32-bit-rseq_test_taking_long_dump.txt.zip](https://github.com/rr-debugger/rr/files/8431999/force32-bit-rseq_test_taking_long_dump.txt.zip)

On my machine, recording `rseq_32` records about 35 `SCHED` events. This recording has 722. That's about 20x more. My replay takes 12s so multiplying by 20 gives 240s, which is about how long your replays take.

**Comment by rocallahan** [comment]
On my system, we're processing about 25M ticks between each `SCHED`. This is because the spinning thread is being run in "unlimited ticks mode" which is only being interrupted when the other thread wakes up from `sched_yield()`; apparently we're about to do 25M ticks before that notification arrives, on my system!

On your system, we're only doing 2.5M ticks between each `SCHED`.

**Comment by bernhardu** [comment]
Thank you, with current tip 4aca8b4d all tests with a regular and force32bit build succeed again.
