### ISSUE TITLE
Intel CPU type 0x806c0 unknown

### ISSUE THREAD

**Issue by ChachaMarwa** [rr-debugger/rr#3134]
using rr on a VM in my computer throws an error seems like the cpu isn't supported.

~/v8$ rr record '/home/pwner/Desktop/UAFs/1/sampleS' 

[FATAL /build/rr-S0CLEN/rr-5.3.0/src/PerfCounters.cc:252:get_cpu_microarch()] Intel CPU type 0x806c0 unknown

cat /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 140
model name	: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
stepping	: 1
cpu MHz		: 2803.202
cache size	: 12288 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq monitor ssse3 cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single fsgsbase avx2 invpcid rdseed clflushopt md_clear flush_l1d arch_capabilities
bugs		: spectre_v1 spectre_v2 spec_store_bypass swapgs
bogomips	: 5606.40
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

**Comment by khuey** [comment]
You need to update rr. 5.3 is several years old and support for this CPU was added back in early 2021 in fd11f49f943f13bdd0a158735f610ad4cd183348
