### ISSUE TITLE
documentation: AMD conditionals seem to be missing

### ISSUE THREAD

**Issue by GitMensch** [rr-debugger/rr#3135]
Also in the link [Will rr work on my system?](https://github.com/rr-debugger/rr/wiki/Will-rr-work-on-my-system), this does not work on Ryzen 3700X, because that stat does not exist:
```bash
perf stat -e br_inst_retired.conditional true
```
But when I look this up, this basically counts, if I'm not mistaken, retired conditional branch instructions. It seems as though, the real command for this on AMD (or Zen architectures, or perhaps this is specific to different Linuxes? I am uninformed on the subject) is:

```bash
perf stat -e ex_ret_cond true
```

Right? Because that exists as a command on this machine with a Ryzen 3700X *and* gives a non-zero value. Also says in the description that it is "Retired condtional branch instructions"

_Originally posted by @theIDinside in https://github.com/rr-debugger/rr/issues/2933#issuecomment-954006338_

---------------------------------

https://indico.cern.ch/event/980497/contributions/4130271/attachments/2161581/3647235/linux-systems-performance.pdf notes on page 8 that there are different perf events for Intel and AMD.

> perf – Intel Skylake events (from `perf list pipeline`)
br_inst_retired.conditional
[Conditional branch instructions retired Spec update: SKL091 (Precise event)]

> perf – AMD Ryzen events (from `perf list core`)
ex_ret_cond
[Retired Conditional Branch Instructions]

As we already have people that reported Zen processors to work I guess they won't have the Intel perf event and `ex_ret_cond` is the equivalence.

Can anyone comment on this? If the later is the correct thing to inspect for AMD I'd adjust the docs.

**Comment by rocallahan** [comment]
That sounds right to me. Thanks!

**Comment by GitMensch** [comment]
Done with https://github.com/rr-debugger/rr/wiki/Will-rr-work-on-my-system/35d1a7ab50947decd1473d5cb0e9db8fc9f26b5b.
