### ISSUE TITLE
Hard coded 4k page size

### ISSUE THREAD

**Issue by yuyichao** [rr-debugger/rr#3143]
I'm trying to see if I can get rr running on apple m1. I've identified some perf counters that could be useful based on blind testing but I've hit a few issues when I try to record a trace. Some/most of the issues seems to be caused by rr hardcoding 4k page sizes in various places (mmap failure for unaligned offset/address) and it seems that the current one (unexpected SIGBUS) could be related as well.

It seems that some of the rr internal objects are hard coded map to certain addresses so I assume changing this naively would break backward compatibility. Should this be done on a per-uarch basis? Or maybe it could be fixed without breaking old traces?

**Comment by Keno** [comment]
> It seems that some of the rr internal objects are hard coded map to certain addresses so I assume changing this naively would break backward compatibility. Should this be done on a per-uarch basis? Or maybe it could be fixed without breaking old traces?

I don't think anybody is relying on replaying old aarch64 traces. I'd welcome patches to fix the page size assumptions. Of course if something breaks on x86 as a result that's a different story, but we can cross that bridge when we get there.

**Comment by khuey** [comment]
aarch64 is still super experimental so break away

**Comment by yuyichao** [comment]
> Of course if something breaks on x86 as a result that's a different story, but we can cross that bridge when we get there.

well, I’m currently trying to change this on x86 to check if I’ve got all the places but I guess I don’t have to keep the changes on x86.

**Comment by rocallahan** [comment]
> It seems that some of the rr internal objects are hard coded map to certain addresses so I assume changing this naively would break backward compatibility. 

Which ones are we talking about specifically?

We definitely must not break compatibility with old x86 traces but I agree we can break aarch64 traces. To prevent further breakage in the future we should store relevant page-size assumption data in rr_trace.capnp header fields.

**Comment by yuyichao** [comment]
> Which ones are we talking about specifically?

See https://github.com/rr-debugger/rr/pull/3144. I've only tried it on super simple programs so far so I'm not sure if there's anything else that I've missed but since this particular one is about the preloaded library, I'm actually not sure how much changing the reply format could help... (unless we compile the library for different page sizes or maybe play some trick at runtime).

**Comment by yuyichao** [comment]
Apart from that, a few tests also assume 4k pages but those should be fairly easy to fix if they are applicable to aarch64...

**Comment by rocallahan** [comment]
> since this particular one is about the preloaded library, I'm actually not sure how much changing the reply format could help.

It does look like it would be difficult to have the preload library support variable page sizes at runtime. So we will want to set the page size for recording at rr build time and bake that into the preload library. I think we should store that page size in a new header field even if we're don't need that for now, so we can use it later if we need to. E.g. if we want to increase the page size later for the same hardware architecture family we'll be able to do so and still support replaying old traces if we want to.

What are the chances of replaying Graviton traces on M1 or vice versa?

**Comment by yuyichao** [comment]
> What are the chances of replaying Graviton traces on M1 or vice versa?

What does that require? Matching counter semantics? Or can rr bridge difference between counters provided by different hardware vendors?

**Comment by rocallahan** [comment]
Graviton is counting taken branches. It sounds like that's an option for M1 too?

**Comment by rocallahan** [comment]
It also requires that the instructions used in the trace exist and have the same semantics on the replay machine.

**Comment by khuey** [comment]
We could also switch counters on Graviton perhaps, if necessary. But what we need is 

1) a counter that exists on both machines
and 2) a counter that is actually accurate on both machines

rr doesn't care about the second normally as long as the same machine is inaccurate in a deterministic way. But it is important for trace portability.

**Comment by rocallahan** [comment]
If making traces portable between Graviton/M1 is a lot of extra work we don't need to support that, but if we can make some decisions now that make it possible, then we should.

**Comment by Keno** [comment]
Just mentioning here that we have a line to the M1 engineering team from when we did the Julia port, so if we need specs on the counters, I can probably get some info on that.

**Comment by rocallahan** [comment]
We should probably discuss non-page-size stuff over in #3134.
