### ISSUE TITLE
Change usage / build instructions to remind of optimizations

### ISSUE THREAD

**Issue by theIDinside** [rr-debugger/rr#3203]
Currently the build instructions just instructs the user to build the default. 

After discussion on the elements chat, I found out that default (cmake debug) builds only librrpreload and brotli with `-O2`.

As this confused me, since I had glanced at the compile commands and seen `-O2` I thought the entirety of rr was built with optimizations in default, perhaps it would be good to remind users to add `-DCMAKE_BUILD_TYPE=Release` (or `-DCMAKE_BUILD_TYPE=RelWithDebInfo` for those who want debug information) for a pretty massive performance difference (almost 2x) when recording.

Now this might be more of a "me" problem than anything else, but figured I would file an issue none the less, as not everybody are well versed in CMake, and some who are some what used to it (like myself) might be fooled by the compile commands output.

**Comment by rocallahan** [comment]
Sure, I think that's a reasonable change. Just make it in the wiki.

**Comment by theIDinside** [comment]
Changed the wiki to contain the following (under the title Project building):

```
A fully optimized rr build requires the CMake parameter -DCMAKE_BUILD_TYPE=Release. If you intend to work on rr this can be omitted, alternatively you can use -DCMAKE_BUILD_TYPE=RelWithDebInfo if you want optimizations and debug info.:
```

As well as adding the `-DCMAKE_BUILD_TYPE=Release` to all the examples on that page. If this is satisfactory, this issue can be closed.
