### ISSUE TITLE
Support AMD Ryzen 7 5700U

### ISSUE THREAD

**Issue by rdrpenguin04** [rr-debugger/rr#3230]
Hello! When trying to run `rd` (port of this to Rust) on my relatively new laptop, I got an error:
```
[FATAL src/perf_counters.rs:199] AMD CPUs not supported.
For Ryzen, see https://github.com/rr-debugger/rr/issues/2034.
For post-Ryzen CPUs, please file a Github issue.
```
As I'm on Ryzen, I followed some links, read some issues, and figured out I should report a new issue, probably here.

Let me know if you'd like any additional information or testing support; thank you!

**Comment by Keno** [comment]
Welcome. AMD is supported in upstream `rr`. I assume the `rd` port is incomplete. I'd recommend filing this issue there.

**Comment by rdrpenguin04** [comment]
Moving this to the `rd` repository, since I just tested `rr` itself and it works fine.
