### ISSUE TITLE
Cannot reverse-step when called from script

### ISSUE THREAD

**Issue by RCoeurjoly** [rr-debugger/rr#3243]
- Error
When trying to execute reverse-step from a script, I get the following:

> Python Exception <class 'gdb.error'>: Target native does not support this command.
> Python Exception <class 'gdb.error'>: Error occurred in Python: Target native does not support this command.
> .gdbinit:5: Error in sourced command file:
> Error occurred in Python: Error occurred in Python: Target native does not support this command.
> Thread-specific breakpoint 6 deleted - thread 1 no longer in the thread list.
> Thread-specific breakpoint 7 deleted - thread 1 no longer in the thread list.

However, once the script finishes and I'm inside the rr interpreter, I can issue that command (reverse-step) without issue.

- Steps to reproduce
nix is used to get the tools.
To install nix: https://nixos.org/download.html

```
git clone git@github.com:RCoeurjoly/DDC.git
cd DDC
nix develop
nix build
rr record result/bin/quicksort
rr replay
```
- Expected result
Script makes rr execute until the end and exit gracefully.
- Hypothesis
This error happens when executing from plain gdb.
I think the script gets executed by gdb and not by rr.
- version
rr, 5.5.0

**Comment by rocallahan** [comment]
"Target native does not support this command" means you're not using rr.

**Comment by RCoeurjoly** [comment]
Well, the thing is I am absolutely 100% using rr. The proof of that I can reproduce this issue by executing a rr replay and that the command works once the gdbinit script finishes.

**Comment by rocallahan** [comment]
What's at .gdbinit line 5?

**Comment by RCoeurjoly** [comment]
The command til-the-end, which is a custom command, which executes continue
until the end of inferior.
I have already found the line that makes rr complain. It is
gdb.execute("reverse-step"), which is located at
https://github.com/RCoeurjoly/DDC/blob/ff2206b3926f1d1d8ff069c4b8c0f92ad30f7450/declarative_debugger.py#L217

**Comment by rocallahan** [comment]
I don't see how the code at line 427 can trigger the code at line 217. Did you get a Python stack trace showing this?

**Comment by rocallahan** [comment]
Thanks. rr spawns a gdb instance that attaches to rr's gdbserver using a `-ex` option, e.g.
```
gdb -l 10000 -ex set sysroot / -x /proc/1659227/fd/4 -ex target extended-remote 127.0.0.1:20828 /home/roc/.local/share/rr/main-0/mmap_clone_4_main
```
But all `.gdbinit` processing happens before the processing of `-ex` options. (See https://sourceware.org/gdb/onlinedocs/gdb/Startup.html for a summary of what gdb does during startup.) So your `.gdbinit` runs before gdb has connected to rr, hence the error.

**Comment by rocallahan** [comment]
We could alter `rr replay` to use `-ix`/`-iex` to run its commands earlier, but basically I think it's a mistake to put commands in `.gdbinit` like `start` that assume the target is already connected.

**Comment by RCoeurjoly** [comment]
When I pass the script file like:
`rr replay -x <filename>`
I still get the same error.
I have updated the repo to move .gdbinit to rr_script.

**Comment by rocallahan** [comment]
This is because of this hack: https://github.com/rr-debugger/rr/issues/2098
I don't remember why I didn't just make all `-ex`/`-x` options happen after the target has been initialized.

**Comment by rocallahan** [comment]
Alright, let's just try removing that hack.
