### ISSUE TITLE
'BLKGETDISKSEQ’ was not declared in this scope

### ISSUE THREAD

**Issue by cielonet** [rr-debugger/rr#3262]
rr/src/record_syscall.cc: In function ‘rr::Switchable rr::prepare_ioctl(rr::RecordTask*, rr::TaskSyscallState&)’:
rr/src/record_syscall.cc:2032:26: error: ‘BLKGETDISKSEQ’ was not declared in this scope; did you mean ‘BLKGETSIZE’?
 2032 |     case IOCTL_MASK_SIZE(BLKGETDISKSEQ):
      |                          ^~~~~~~~~~~~~
rr/src/record_syscall.cc:1421:30: note: in definition of macro ‘IOCTL_MASK_SIZE’
 1421 | #define IOCTL_MASK_SIZE(v) ((v) & ~(_IOC_SIZEMASK << _IOC_SIZESHIFT))
      |                              ^
make[2]: *** [CMakeFiles/rr.dir/build.make:741: CMakeFiles/rr.dir/src/record_syscall.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:2661: CMakeFiles/rr.dir/all] Error 2
make: *** [Makefile:166: all] Error 2

-----------------
FAILED: CMakeFiles/ioctl_blk.dir/src/test/ioctl_blk.c.o 
/opt/llvm-15/bin/clang -DEXECINFO_H=1 -DFANOTIFY_H=1 -DMQUEUE_H=1 -DPROC_SERVICE_H=1 -DRR_VERSION=\"5.5.0\" -Irr/include -Irr/third-party/proc-service -Irr/third-party/brotli/include -Itools/obj -Irr/src/preload -D__USE_LARGEFILE64 -pthread -msse2 -D__MMX__ -D__SSE__ -D__SSE2__ -fmacro-prefix-map=rr/= -Wstrict-prototypes -std=gnu11 -Wno-unused-command-line-argument    -O3 -DNDEBUG -Wall -Wextra -DDEBUG -UNDEBUG -g3 -O0 -MD -MT CMakeFiles/ioctl_blk.dir/src/test/ioctl_blk.c.o -MF CMakeFiles/ioctl_blk.dir/src/test/ioctl_blk.c.o.d -o CMakeFiles/ioctl_blk.dir/src/test/ioctl_blk.c.o -c rr/src/test/ioctl_blk.c
rr/src/test/ioctl_blk.c:51:16: error: use of undeclared identifier 'BLKGETDISKSEQ'
  CHECK_GETTER(BLKGETDISKSEQ, u64_val);
               ^
1 error generated.

**Comment by cielonet** [comment]
Previous commit-- 9e52bd252de0723f89b226685303681192cd0d6a -- builds fine for me...

**Comment by khuey** [comment]
Yeah this is new in 5.15

**Comment by cielonet** [comment]
Just built! It works thank you!! :-)
