### ISSUE TITLE
vfork_32 with syscallbuf enabled is failing for me

### ISSUE THREAD

**Issue by khuey** [rr-debugger/rr#3270]
It appears to me what happens is we vfork(2), then execl the simple_32 binary. *That* triggers an openat of /home/khuey/dev/obj-rr/bin/../lib/rr/librrpreload_32.so at some point, which blocks, and that causes the scheduler to attempt to resume the parent that's currently in the vfork(2), which explodes.

**Comment by Keno** [comment]
If it's trying to load the preload library, hasn't the exec completed and thus the parent is no longer in vfork?

**Comment by khuey** [comment]
Hmm, yes, that would seem to be true.

Unsurprisingly this bisects to 9e52bd252de0723f89b226685303681192cd0d6a

**Comment by khuey** [comment]
The vfork returns in the child on the same syscallbuf stack that the parent is using and it wipes out the high bytes of the return address with a pushfw/popfw pair, then when the parent goes to return it runs off into the weeds.

**Comment by khuey** [comment]
I meant pushw/popfw, of course.

**Comment by khuey** [comment]
pushw (saved_flags) is the only instruction in _syscall_hook_trampoline that writes to the stack after syscall_hook afaict, which explains why we haven't seen this before.

It's probably 32 bit only because it hits the upper two bytes of a 64 bit pointer or something.

saved_flags is also wrong here because the new task has a new set of thread locals that's all zero-initialized

**Comment by khuey** [comment]
Fixed by b3a1a3e3d06fbd7616324712dd67929b95c24c8a
