### ISSUE TITLE
close_range syscall unsupported

### ISSUE THREAD

**Issue by raphCode** [rr-debugger/rr#3303]
I tried running rr on [zellij](https://github.com/zellij-org/zellij) and got a failed assertion about an unsupported syscall:

```
(task 2338274 (rec:2338274) at time 1714)
 -> Assertion `t->regs().syscall_result_signed() == -syscall_state.expect_errno' failed to hold. Expected ENOSYS for '<unknown-syscall-436>' but got result 0 (errno SUCCESS); execution of syscall unsupported by rr
```

If I interpret the 436 as syscall number, I think this is close_range.

**Comment by Keno** [comment]
This was ENOSYS'd in #3140, so you'll need to get an rr newer than that.

**Comment by raphCode** [comment]
I see, my bad. I will use a current build since the most recent release is older than the PR.
