### ISSUE TITLE
replay divergence (check_ticks_consistency assert, Assertion `ticks_now == trace_ticks' failed to hold. ticks mismatch for 'SYSCALL: epoll_wait') replaying linux-chromeos recording

### ISSUE THREAD

**Issue by dbaron** [rr-debugger/rr#3341]
Now that #3324 is fixed, I'm again trying to record [a bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1341219) in a debug [build of linux-chromeos](https://chromium.googlesource.com/chromium/src/+/HEAD/docs/chromeos_build_instructions.md#Chromium-OS-on-Linux-linux_chromeos).

I've had three recordings (one before the #3324 fix that I somehow managed to get without hitting it), and two with the fix.  All three have had what I believe is a replay divergence problem.

The oldest one manifested as a hang during replay, which @khuey diagnosed a little bit (he wrote "The hang is caused by a divergence that ends up in a FUTEX_WAIT.").  The two I recorded today with the fix for #3324 both took the form of:
```
[FATAL src/ReplaySession.cc:1173:check_ticks_consistency()] 
 (task 482916 (rec:482475) at time 187084)
 -> Assertion `ticks_now == trace_ticks' failed to hold. ticks mismatch for 'SYSCALL: epoll_wait'; expected 2724015, got 2723586
```
or
```
[FATAL src/ReplaySession.cc:1173:check_ticks_consistency()] 
 (task 488317 (rec:484291) at time 202025)
 -> Assertion `ticks_now == trace_ticks' failed to hold. ticks mismatch for 'SYSCALL: epoll_wait'; expected 3104487, got 3104058
```

The steps I was using for the two occurrences today were to debug this were to build Linux-ChromeOS (see instructions link above) at revision ff61e54621ad6e836909b04eed184be45b037703 with the gn args:
```
target_os="chromeos"
is_debug=true
is_component_build=true
use_goma=true
enable_nacl=false
is_chrome_branded=false  # Adds internal features and branded art assets.
is_official_build=false  # Turns on many optimizations, slower build.
```
and with the patch (probably not relevant):
```diff
diff --git a/chrome/browser/chromeos/fileapi/recent_model.cc b/chrome/browser/chromeos/fileapi/recent_model.cc
index 69f1ea21bee33..0943c5d704a92 100644
--- a/chrome/browser/chromeos/fileapi/recent_model.cc
+++ b/chrome/browser/chromeos/fileapi/recent_model.cc
@@ -14,6 +14,7 @@
 #include "base/memory/ptr_util.h"
 #include "base/metrics/histogram_macros.h"
 #include "base/time/time.h"
+#include "base/threading/platform_thread.h"
 #include "chrome/browser/ash/file_manager/path_util.h"
 #include "chrome/browser/chromeos/fileapi/recent_arc_media_source.h"
 #include "chrome/browser/chromeos/fileapi/recent_disk_source.h"
@@ -175,6 +176,8 @@ void RecentModel::OnGetRecentFilesCompleted(FileType file_type) {
   DCHECK(!cached_files_.has_value());
   DCHECK(!build_start_time_.is_null());
 
+  base::PlatformThread::Sleep(base::Seconds(10));
+
   std::vector<RecentFile> files;
   while (!intermediate_files_.empty()) {
     files.emplace_back(intermediate_files_.top());
```

I then ran `./out/ChromeOS-Debug/chrome`, hit the "Files" icon at the bottom, made the window short so that it could be scrolled vertically, scrolled the view up and down, chose "Recent Files", and kept trying to scroll up and down until the assert.  (Probably not all of this is needed since the replay didn't make it through to the end of the recording.)

**Comment by dbaron** [comment]
And the end of the trace dump for the latter failure was:
```
{
  real_time:148458.357039 global_time:202023, event:`SYSCALL: epoll_wait' (state:EXITING_SYSCALL) tid:484291, ticks:3092331
rax:0x1 rbx:0x7fdb0416afa0 rcx:0xffffffffffffffff rdx:0x20 rsi:0x7fdaf8002b90 rdi:0x244 rbp:0x7fdb0416afa0 rsp:0x7fdb0416adb0 r8:0x0 r9:0x4 r10:0xffffffff r11:0x246 r12:0x0 r13:0x7fdb0326a206 r14:0x7fdb0326a216 r15:0x7fdb0326a396 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xe8 fs_base:0x7fdb0496b640 gs_base:0x0
  { tid:484291, addr:0x7fdaf8002b90, length:0x180 }
}
{
  real_time:148458.357315 global_time:202024, event:`SYSCALLBUF_FLUSH' tid:484291, ticks:3104487
  { syscall:'clock_gettime', ret:0x0, size:0x20 }
  { syscall:'gettid', ret:0x4, size:0x10 }
  { syscall:'recvmsg', ret:0x70, size:0x2d8, desched:1 }
  { syscall:'gettid', ret:0x4, size:0x10 }
  { syscall:'gettid', ret:0x4, size:0x10 }
  { syscall:'clock_gettime', ret:0x0, size:0x20 }
  { syscall:'clock_gettime', ret:0x0, size:0x20 }
  { syscall:'epoll_wait', ret:0x0, size:0x10 }
  { syscall:'clock_gettime', ret:0x0, size:0x20 }
  { syscall:'clock_gettime', ret:0x0, size:0x20 }
  { syscall:'epoll_wait', ret:0x0, size:0x10 }
  { syscall:'clock_gettime', ret:0x0, size:0x20 }
  { syscall:'gettid', ret:0x4, size:0x10 }
  { syscall:'clock_gettime', ret:0x0, size:0x20 }
  { syscall:'epoll_wait', ret:0x0, size:0x10 }
}
{
  real_time:148458.357324 global_time:202025, event:`SYSCALL: epoll_wait' (state:ENTERING_SYSCALL) tid:484291, ticks:3104487
rax:0xffffffffffffffda rbx:0x7fdb0416afa0 rcx:0xffffffffffffffff rdx:0x20 rsi:0x7fdaf8002b90 rdi:0x244 rbp:0x7fdb0416afa0 rsp:0x7fdb0416adb0 r8:0x0 r9:0x4 r10:0xffffffff r11:0x246 r12:0x0 r13:0x7fdb0326a436 r14:0x7fdb0326a446 r15:0x7fdb0326a5c6 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xe8 fs_base:0x7fdb0496b640 gs_base:0x0
}
{
  real_time:148458.357332 global_time:202026, event:`SYSCALLBUF_RESET' tid:484291, ticks:3104487
}
```

**Comment by khuey** [comment]
Does this happen with `record -n` (I expect it will, and it may help narrow down the diverging section)?

**Comment by dbaron** [comment]
If `record -n` is expected to be 10x slower... then I'm still waiting for it to start up.  If not, then it doesn't seem to work...

**Comment by khuey** [comment]
It will be significantly slower yes.

**Comment by dbaron** [comment]
100x slower?  I'm still looking at a blank window that hasn't painted yet.

**Comment by khuey** [comment]
That is more slowdown than I would expect to see.

**Comment by khuey** [comment]
Can you upload a trace that fails (no need for -n) to Pernosco?

**Comment by dbaron** [comment]
Done.

**Comment by khuey** [comment]
I think this might be graphics related. David's trace is using OpenGL in direct mode (I determined this by manually running Pernosco on the part of the trace that doesn't explode and then using the built in x11 decoder on it) so the program is talking directly to the GPU stuff. If there's any sort of writing happening from the GPU driver into Chromium's address space that will be unrecorded and potentially cause diversions.

Is it possible to run this with software GL?

**Comment by dbaron** [comment]
By starting `chrome` with the `--disable-gpu` command line flag **and** applying the following patch:

```diff
diff --git a/content/browser/compositor/viz_process_transport_factory.cc b/content/browser/compositor/viz_process_transport_factory.cc
index 0e3af0f9280ab..8dbd8d744f652 100644
--- a/content/browser/compositor/viz_process_transport_factory.cc
+++ b/content/browser/compositor/viz_process_transport_factory.cc
@@ -269,12 +269,6 @@ ui::ContextFactory* VizProcessTransportFactory::GetContextFactory() {
 
 void VizProcessTransportFactory::DisableGpuCompositing(
     ui::Compositor* guilty_compositor) {
-#if BUILDFLAG(IS_CHROMEOS_ASH)
-  // A fatal error has occurred and we can't fall back to software compositing
-  // on CrOS. These can be unrecoverable hardware errors, or bugs that should
-  // not happen. Crash the browser process to reset everything.
-  LOG(FATAL) << "Software compositing fallback is unavailable. Goodbye.";
-#else
   if (base::CommandLine::ForCurrentProcess()->HasSwitch(
           switches::kDisableSoftwareCompositingFallback)) {
     // Some tests only want to run with a functional GPU Process. Fail out here
@@ -323,7 +317,6 @@ void VizProcessTransportFactory::DisableGpuCompositing(
     if (visible)
       compositor->SetVisible(true);
   }
-#endif
 }
 
 void VizProcessTransportFactory::OnGpuProcessLost() {
diff --git a/content/browser/gpu/gpu_data_manager_impl_private.cc b/content/browser/gpu/gpu_data_manager_impl_private.cc
index 54e4a915263ea..b5a239ac54b90 100644
--- a/content/browser/gpu/gpu_data_manager_impl_private.cc
+++ b/content/browser/gpu/gpu_data_manager_impl_private.cc
@@ -623,11 +623,9 @@ void GpuDataManagerImplPrivate::InitializeGpuModes() {
   // Android and Chrome OS can't switch to software compositing. If the GPU
   // process initialization fails or GPU process is too unstable then crash the
   // browser process to reset everything.
-#if !BUILDFLAG(IS_ANDROID) && !BUILDFLAG(IS_CHROMEOS_ASH)
   fallback_modes_.push_back(gpu::GpuMode::DISPLAY_COMPOSITOR);
   if (SwiftShaderAllowed())
     fallback_modes_.push_back(gpu::GpuMode::SWIFTSHADER);
-#endif  // !BUILDFLAG(IS_ANDROID) && !BUILDFLAG(IS_CHROMEOS)
 
   base::CommandLine* command_line = base::CommandLine::ForCurrentProcess();
   if (command_line->HasSwitch(switches::kDisableGpu)) {
@@ -639,11 +637,6 @@ void GpuDataManagerImplPrivate::InitializeGpuModes() {
     fallback_modes_.push_back(gpu::GpuMode::DISPLAY_COMPOSITOR);
 #endif  // BUILDFLAG(IS_CAST_AUDIO_ONLY)
 #endif  // BUILDFLAG(IS_CASTOS)
-
-#if (BUILDFLAG(IS_ANDROID) && !BUILDFLAG(IS_CAST_ANDROID)) || \
-    BUILDFLAG(IS_CHROMEOS_ASH)
-    CHECK(false) << "GPU acceleration is required on certain platforms!";
-#endif
   } else {
     // On Fuchsia Vulkan must be used when it's enabled by the WebEngine
     // embedder. Falling back to SW compositing in that case is not supported.
```

I was able to run with something that's presumably software, I think?  ChromeOS starts up... although the Files app won't start, so I can't actually reproduce my bug.

Furthermore, if I try to replay the recording, I made when doing so, I get:

```
[ERROR src/ReplaySession.cc:789:guard_overshoot()] Replay diverged; target registers mismatched: 
[FATAL src/ReplaySession.cc:793:guard_overshoot()] 
 (task 775764 (rec:774959) at time 185549)
 -> Assertion `false' failed to hold. overshot target ticks=5151587 by 76
```

**Comment by rocallahan** [comment]
When I was playing with STR yesterday I was using `--use-gl=angle --use-angle=swiftshader`. Performance wasn't too bad. I did not get around to trying a replay.

**Comment by rocallahan** [comment]
Without any special options, the build wouldn't even start due to GPU issues.

**Comment by dbaron** [comment]
With `--use-gl=angle --use-angle=swiftshader` I think the performance under `rr` recording is substantially better than without it.

I was able to reproduce the bug with that configuration, and replay the recording successfully.

**Comment by khuey** [comment]
It seems that the immediate problem is solved (David's upload to Pernosco worked fine) but it would be nice if somehow we could do an equivalent of what we do to turn off DRI so this would just work.

**Comment by rocallahan** [comment]
Yeah but I think the most practical way forward is to land a Chromium patch that sets the right flags by default when `RUNNING_UNDER_RR`.

**Comment by dbaron** [comment]
Seems reasonable.  I'll work on that at https://chromium-review.googlesource.com/c/chromium/src/+/3787592 although my initial attempt wasn't (so far) successful.  The command line processing is rather complicated...

**Comment by dbaron** [comment]
I do have a [working change pending review](https://chromium-review.googlesource.com/c/chromium/src/+/3787592) now.

However, I'd note that, in my local testing, rr recording of ChromeOS-Linux is still pretty unreliable.  (When I do get a good recording, though, replay now does seem to be reliable, with the above change.)  I've gotten a few rr assertions (not the same one twice, though), and more frequently hangs (requiring `killall -9 rr`) during recording.  I'm not entirely sure how it's useful to report those problems, although probably in a new issue if I can figure out some useful set of information to provide...

**Comment by rocallahan** [comment]
If you can come up with steps to reproduce with reasonably high probability, I'll look into it.

**Comment by dbaron** [comment]
OK, filed #3359 as a followup.
