### ISSUE TITLE
recording of linux-chromeos fails in various ways

### ISSUE THREAD

**Issue by dbaron** [rr-debugger/rr#3359]
This is essentially a continuation of #3341.

I'm again trying to record [a bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1341219) in a debug [build of linux-chromeos](https://chromium.googlesource.com/chromium/src/+/HEAD/docs/chromeos_build_instructions.md#Chromium-OS-on-Linux-linux_chromeos) using the `args.gn` from https://github.com/rr-debugger/rr/issues/3324#issue-1300788182 .

It does occasionally work.  However, more often it fails, and in different ways each time, although most frequently with rr hanging.

My steps to reproduce, given a build, are:

1. start up (`rr record --disable-avx-512 ./out/ChromeOS-Debug/chrome --use-gl=angle --use-angle=swiftshader`)
2. when it starts, click on the files manager (the middle of the 3 icons at the bottom)
3. when it opens, scroll it up and down
4. close it
5. use the button in the lower right corner to open the menu and then click the power icon to shut down.

I just attempted doing this 5 times, and failed to get a complete recording any of the five times (though I have gotten good recordings a few times):

On the first try, the recording crashed (after step 2 above... though I'd walked away from the machine to do something else so it had been sitting there a bit):
```
[FATAL src/RecordTask.cc:2157:read_pid_ns() errno: ENOENT] 
 (task 842714 (rec:842714) at time 548123)
 -> Assertion `ret >= 0' failed to hold. 
```

On the second try, I again left it sitting for a bit after step 2, and rr had hung (not responsive to Ctrl+C or `kill`, needed `kill -9`).

On the third try, similar hang of rr, except it hung before the file manager opened.

On the fourth try, I got through all the steps, but hit the same type of rr hang during shutdown.

The fifth try had the same results as the fourth try.

I'm using rr 5f38cf31a9f973c921ad5391e9842c0e208792e0 and chromium 66d4b0b6a6ef805b5b838764d770aecdcbbbcf46.

I'd note that I've gotten other errors; for example a few days ago (possibly with slightly different steps, and I think with rr 882fae038436d6a68c8531bc64cd79c67d9ae427), I got:
```
[FATAL src/PerfCounters.cc:309:start_counter() errno: ESRCH] Failed to initialize counter
=== Start rr backtrace:
rr(_ZN2rr13dump_rr_stackEv+0x38)[0x5565f3afd715]
rr(_ZN2rr15notifying_abortEv+0x12)[0x5565f3afd696]
rr(_ZN2rr12FatalOstreamD1Ev+0x2d)[0x5565f3955ccb]
rr(+0x41a82c)[0x5565f398782c]
rr(_ZN2rr12PerfCounters5resetEl+0x310)[0x5565f398aecc]
rr(_ZN2rr4Task16resume_executionENS_13ResumeRequestENS_11WaitRequestENS_12TicksRequestEi+0x1e3)[0x5565f3abd867]
rr(_ZN2rr13RecordSession13task_continueERKNS0_9StepStateE+0x6ca)[0x5565f399dc02]
rr(_ZN2rr13RecordSession11record_stepEv+0x5fb)[0x5565f39a550d]
rr(+0x42b7b4)[0x5565f39987b4]
rr(_ZN2rr13RecordCommand3runERSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EE+0x3e3)[0x5565f39994bb]
rr(main+0x265)[0x5565f3b1a764]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xcd)[0x7fe769dd47fd]
rr(_start+0x2a)[0x5565f387771a]
=== End rr backtrace
```

cc @rocallahan

**Comment by rocallahan** [comment]
The shutdown logic has been totally overhauled and we seem to have fixed intermittent errors relating to kernel pid namespaces, so if this bug has not been fixed, it's obsolete.
