### ISSUE TITLE
replay fails at async signal delivery in XMM/YMM-only code

### ISSUE THREAD

**Issue by rocallahan** [rr-debugger/rr#3383]
Google has some code where an inner loop body makes a series of function calls (some of which are the same function); these functions only manipulate XMM/YMM registers and do not perform conditional branches, and between these function calls there is only code that manipulates XMM/YMM registers and does no conditional branches. Also, an asynchronous signal with a handler is delivered during the loop. Because rr only checks that the conditional branch count and the general-purpose registers match for the async signal delivery, when this signal is delivered inside one of those callee functions, we often deliver the signal at the wrong time during replay.

**Comment by rocallahan** [comment]
I think the only reasonable way to handle this is to store the XMM/YMM register values at async signal delivery and match on them during replay.

**Comment by khuey** [comment]
I assume "modify the code to have a dummy conditional branch" isn't acceptable? That's what we did for remix.

**Comment by rocallahan** [comment]
That's probably not an easy sell.

**Comment by rocallahan** [comment]
Storing ExtraRegisters for signal events doesn't sound *too* bad to me.
