### ISSUE TITLE
6.1-rc1 no longer allows SIGKILL to advance a tracee out of PTRACE_EVENT_EXIT

### ISSUE THREAD

**Issue by khuey** [rr-debugger/rr#3385]
See torvalds/linux@e572410e47a4e9647d5d7a49ca699a1497378707

This causes the detach_sigkill test to hang. @Keno do we actually care about this test?

**Comment by Keno** [comment]
I had asked for this kernel change, so I can hardly complain now ;). We should fix the test by looking at the kill pid and seeing if it's one of the detached proxies. That way SIGKILL will keep working if done from inside the trace, but we'll just ignore with from outside the trace, which is fine.

**Comment by khuey** [comment]
Can you do that? :)

**Comment by bernhardu** [comment]
Recently a linux-image 6.1.4-1 arrived in Debian testing and this hang did show up in my casual tests run today.

**Comment by rocallahan** [comment]
@Keno wouldn't it be cleaner to keep the proxy paused in a non-exiting state and handle PTRACE_EVENT_EXIT by killing the detached process? That way we wouldn't have to intercept SIGKILL being sent by the tracee and we would handle kills coming from non-tracees.

**Comment by Keno** [comment]
That seems reasonable to me.

**Comment by Keno** [comment]
I guess the only downside is that we'd be holding on to some resources, but probably not a huge deal since we usually detach processes early in their lifespans.
