### ISSUE TITLE
AMD Ryzen 9 7950X support?

### ISSUE THREAD

**Issue by jw3126** [rr-debugger/rr#3390]
Thanks for rr it is awesome! I cannot use `rr` on `AMD Ryzen 9 7950X`: 
```
[FATAL src/PerfCounters_x86.h:114:compute_cpu_microarch()] AMD CPU type 0x60f10 (ext family 0xa) unknown
```
Is there some workaround?

**Comment by khuey** [comment]
Zen 4 is just too new to be present in rr (I think it launched last month?). Try adding the `0x60f10` value as a case to https://github.com/rr-debugger/rr/blob/master/src/PerfCounters_x86.h#L103 and see if make check works.

**Comment by DarkArc** [comment]
Using the existing Zen workaround script, having upgraded from a 3950X, I see the following failures (on master -- 05b8393c3eefef3dba96c42915d442a47a1d1308):

```
        460 - x86/pkeys (Failed)
        461 - x86/pkeys-no-syscallbuf (Failed)
        968 - exclusion_region (Failed)
        1884 - x86/pkeys-32 (Failed)
        1885 - x86/pkeys-32-no-syscallbuf (Failed)
```

All other tests pass. I see the master build is failing so I'm going to check back on commit 23f0faeddd93cf274de647d7465a3d9227098448.

At that commit this is down to just the following tests:

```
        460 - x86/pkeys (Failed)
        461 - x86/pkeys-no-syscallbuf (Failed)
        1880 - x86/pkeys-32 (Failed)
        1881 - x86/pkeys-32-no-syscallbuf (Failed)
```

Dropping back to the 5.6 release tag + the build fixes d12f8ffb004ba2d42792ecb9d035c630764d874d and 2979c60ef8bbf7c940afd90172ddc5d8863f766e, I get the same result:

```
        456 - x86/pkeys (Failed)
        457 - x86/pkeys-no-syscallbuf (Failed)
        1870 - x86/pkeys-32 (Failed)
        1871 - x86/pkeys-32-no-syscallbuf (Failed)
```

Test logs of that last run are attached.
[test.log](https://github.com/rr-debugger/rr/files/9904606/test.log)

**Comment by khuey** [comment]
The pkeys stuff is a Linux kernel bug in 5.15+

**Comment by DarkArc** [comment]
I'm running Kernel 6.0, so that tracks, looks like this is "working as is" then with this change :)

```
diff --git a/src/PerfCounters_x86.h b/src/PerfCounters_x86.h
index 13a0c856..bc199443 100644
--- a/src/PerfCounters_x86.h
+++ b/src/PerfCounters_x86.h
@@ -103,6 +103,7 @@ static CpuMicroarch compute_cpu_microarch() {
     case 0x20f10: // Vermeer (Zen 3)
     case 0x50f00: // Cezanne (Zen 3)
     case 0x40f40: // Rembrandt (Zen 3+)
+    case 0x60f10: // Zen 4
       if (ext_family == 0xa) {
         return AMDZen;
       }
```

**Comment by khuey** [comment]
Great, please send that in PR form :)

**Comment by jw3126** [comment]
Awesome! Right now I cannot switch to 6.0 kernel, but on 5.15.74 most tests pass and I could use rr on a small toy example.

```
99% tests passed, 9 tests failed out of 2849

Total Test time (real) = 2414.35 sec

The following tests FAILED:
	198 - futex_exit_race_sigsegv (Failed)
	199 - futex_exit_race_sigsegv-no-syscallbuf (Failed)
	460 - x86/pkeys (Failed)
	461 - x86/pkeys-no-syscallbuf (Failed)
	1541 - detach_sigkill_exit-32-no-syscallbuf (Failed)
	1622 - futex_exit_race_sigsegv-32 (Failed)
	1623 - futex_exit_race_sigsegv-32-no-syscallbuf (Failed)
	1884 - x86/pkeys-32 (Failed)
	1885 - x86/pkeys-32-no-syscallbuf (Failed)
```
