### ISSUE TITLE
record git sha or CI build ID somewhere in the build output?

### ISSUE THREAD

**Issue by DanAlbert** [rr-debugger/rr#3393]
Right now `rr --version` prints something like `rr version 5.6.0`. For Android we'd like to be able to determine the exact source (or even build ID) that generated that binary. This could probably be done with the ELF buildid in the binary itself, but it's cumbersome to map that back to the build that produced it.

A few options:

1. Add the git SHA to the string printed by `rr --version`
2. Add a `versioninfo.md` or similar to the output that can be installed alongside the binary that includes that info
3. Add a cmake option for passing arbitrary version information to add it to the `--version` output, update https://github.com/rr-debugger/rr/tree/master/.android to pass the cloud build UUID or git sha

WDYT?

**Comment by rocallahan** [comment]
For option 1, what would distro builds output? I think option 3 is probably the best.

**Comment by DanAlbert** [comment]
Option 3 is probably my favorite as well since it's the most flexible (and is probably required for the implementation of 1 anyway).

A potential option 4: use the git tag of the build (if defined) in `rr --version` instead of https://github.com/rr-debugger/rr/blob/f26dca4e157d8b3f4390315a84f94a9a184a60b0/CMakeLists.txt#L33-L38 (lol at the comment). I suspect that's the least preferred option though since it's different from the established behavior?

**Comment by khuey** [comment]
I think in general assuming that rr is being built from a git repository (as opposed to e.g. a source tarball) is kind of brittle and should be avoided if possible.

**Comment by DanAlbert** [comment]
Option 3 is I think the only one that avoids requiring that. Does that sound good to you, or should we be thinking up option 5?

**Comment by khuey** [comment]
It sounds good to me. Do you want to do it or should I?

**Comment by DanAlbert** [comment]
Have at it :) If you update the android build config to pass `BUILD_ID` (https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values) for that value, I think I can update our mirror and it will Just Work?

**Comment by khuey** [comment]
Ok I think the combo of ccfab1965b673445ebe69f0ccdd52b53cc26b58f and 4ce5a49dc15ff48703a8bc8003a305a6a31d9f92 will do what you want here automatically. Let me know if it doesn't.
