### ISSUE TITLE
Intel CPU type 0xb0670 unknown

### ISSUE THREAD

**Issue by ofersadgat** [rr-debugger/rr#3397]
I built rr from commit f03d1c361dcc6edc38e309d108bf66a6dba2b31f on a Windows 10 PC with an Intel Core i9 13900K under 5.15.74.2-microsoft-standard-WSL2 running Ubuntu 22.04.1 LTS. There didnt appear to be any issues during build/install. After that I ran `rr record ls` and that produced:
```
[FATAL src/PerfCounters_x86.h:118:compute_cpu_microarch()] Intel CPU type 0xb0670 unknown
```
Does some support need to be added for this new CPU?

**Comment by khuey** [comment]
Fixed by #3398
