### ISSUE TITLE
Intel CPU type unknown

### ISSUE THREAD

**Issue by nsheff** [rr-debugger/rr#3410]
Getting this error:

```
[FATAL /build/rr-S0CLEN/rr-5.3.0/src/PerfCounters.cc:252:get_cpu_microarch()] Intel CPU type 0x906a0 unknown
```

This is my CPU:

Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          16
On-line CPU(s) list:             0-15
Thread(s) per core:              1
Core(s) per socket:              12
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           154
Model name:                      12th Gen Intel(R) Core(TM) i5-12600H

**Comment by khuey** [comment]
You need to upgrade your rr, 5.3.0 is 3 years old now. This issue has been fixed for some time.

**Comment by nsheff** [comment]
Thanks, I had just installed the one from the repos, so those must be outdated. Sorry about that.
