### ISSUE TITLE
pid_ns_reap test hangs because of <defunct> processes

### ISSUE THREAD

**Issue by GitMensch** [rr-debugger/rr#3436]
Run with today's master on `Linux instance-20230210-0110 5.15.0-6.80.3.1.el9uek.aarch64 #2 SMP Tue Jan 10 11:35:24 PST 2023 aarch64 aarch64 aarch64 GNU/Linux` (building worked like a charm giving the installation notes in the wiki, only capnp needed to be built from source for Oracle Linux 9, which was no problem).

"hangs" means that nothing happens, also no timeout.

~~~
 354715 opc       20   0   34968  15568   9864 S   0.0   0.1   0:00.03 ctest -R pid_ns_reap -VV --output-on-failure
 354716 opc       20   0  222372   3460   2968 S   0.0   0.0   0:00.00 /usr/bin/bash source_dir/src/test/basic_test.run pid_ns_reap  bin_dir 120
 354728 opc       20   0    5476   2552   2288 S   0.0   0.0   0:00.00 test-monitor 120 record.err rr --suppress-environment-warnings --fatal-errors -+
 354729 opc       20   0  450328  20888   8320 S   0.0   0.2   0:00.08 rr --suppress-environment-warnings --fatal-errors --check-cached-mmaps --resour+
 354736 opc       20   0    5692   3148    856 S   0.0   0.0   0:00.03 ./pid_ns_reap-LgQyYIsfh
 354738 opc       20   0       0      0      0 Z   0.0   0.0   0:00.00 [pid_ns_reap-LgQ] <defunct>
 354739 opc       20   0       0      0      0 Z   0.0   0.0   0:00.00 [pid_ns_reap-LgQ] <defunct>
 354740 opc       20   0   14908   3080    764 t   0.0   0.0   0:00.00 ./pid_ns_reap-LgQyYIsfh
 354751 opc       20   0  222108   3088   2828 S   0.0   0.0   0:00.00 /bin/sh -c gdb '-l' '10000' '-ex' 'set sysroot /' '-ex' 'target extended-remote+
 354752 opc       20   0  581448  58400  25720 S   0.0   0.5   0:00.09 gdb -l 10000 -ex set sysroot / -ex target extended-remote 127.0.0.1:27061 -ex s+
~~~

The only thing that helps is to send 11 to the running GDB instance.

Side note: other than this test only the following [already tracked in #3435] failed there:

~~~
        958 - ignore_nested (Failed)
        959 - ignore_nested-no-syscallbuf (Failed)
~~~

and, vanishing on re-run (in single test mode)

~~~
        109 - detach_sigkill-no-syscallbuf (Failed)
        977 - madvise_fracture_flags-no-syscallbuf (Failed)
~~~

**Comment by rocallahan** [comment]
What happens if you run `bash pid_ns_reap.run` from rr's test directory?

**Comment by GitMensch** [comment]
> bash pid_ns_reap.run

There is no such file. Not sure if you've meant the following:

```bash
$ bin/pid_ns_reap
EXIT-SUCCESS
```

**Comment by rocallahan** [comment]
Sorry, I meant `bash basic_test.run pid_ns_reap` (from the `test` directory)

**Comment by GitMensch** [comment]
... 

```bash
$ cd ~/rr/src/test
$ bash basic_test.run pid_ns_reap
FAILED: objdir missing
$ cd ../../build/
$ bash ../src/test/basic_test.run pid_ns_reap
FAILED: objdir missing
$ bash ../src/test/basic_test.run pid_ns_reap "" .  # same defunct processes
```

**Comment by GitMensch** [comment]
Just to recheck: is there anything more I can help with inspecting?

**Comment by rocallahan** [comment]
This is going to be pretty hard to debug via Github comments. We'd need to reproduce it on a machine some rr developer has access to.

**Comment by GitMensch** [comment]
That should be easy as this can be reproduced with an Oracle free cloud tier:
* go to https://www.oracle.com/cloud/free/
* register + login
* create a new A1 VM with Oracle Linux
* build capnp from source + install
* get other dependencies (64bit only) via package manager
* export LD_LIBRARY_PATH for the installed capnp if you did not install it manually to /usr instead of /usr/local
* build (works fine)
* run the tests (actually: run only this test is enough)

**Comment by GitMensch** [comment]
Do you need me to provide ssh access for one of you or is the above "how to get that without any cost" 'good enough'?

**Comment by rocallahan** [comment]
I can reproduce this locally. The problem is that this code is really sensitive and really needs a lot of refactoring, which is a large, hard project.

**Comment by rocallahan** [comment]
Actually I was wrong, it's a simple fix.
