### ISSUE TITLE
Divergence on Firefox (A/V related?)

### ISSUE THREAD

**Issue by khuey** [rr-debugger/rr#3444]
@karlt reports that a workload involving disconnecting an audio device fails to record/replay successfully on his machine, but does record/replay successfully on another machine.

The bad/good recordings were submitted to Pernosco as avGDyD0k0zM/itVVBSw98sQ, respectively.

The machine that does not work is running a 4.19 series kernel, the machine that does is running a 5.19 series kernel. The version of rr that is being used does not appear to affect the outcome (both revs from November and 25e6edc550ed6e89e03b669d175aa942b4845bf6 have been observed to fail).

**Comment by karlt** [comment]
The divergence reproduces without disconnecting an audio device.  Reproduction seems to be triggered by playing https://philips.s3.eu-central-1.amazonaws.com/Rudolf/VfE_html5.mp4 and occurs even when muted.

**Comment by khuey** [comment]
But it still only reproduces on your machine?

**Comment by karlt** [comment]
> But it still only reproduces on your machine?

Yes, the same video didn't reproduce on the machine running a 5.19 series kernel.

**Comment by khuey** [comment]
That's using h264? It wouldn't surprise me if the h264 plugin is doing something weird.

**Comment by karlt** [comment]
Yes, and plausibly.  ffmpeg is being used to decode.
However, another quirk is that optimized builds of Firefox are replaying fine, while debug builds do not, with the same ffmpeg builds.

**Comment by khuey** [comment]
I tested this on a 5.15 series kernel and while the playback under rr was terrible it did record and replay properly.

I'll see if I can test with an older kernel.

**Comment by karlt** [comment]
Similar divergence occurs here with a 5.15 kernel, so the kernel version doesn't seem to be the crucial factor.

**Comment by khuey** [comment]
If you can reproduce this in the future with the latest rr on Intel hardware we have tooling now that can help.

**Comment by karlt** [comment]
Thank you. I don't recall this occurring again since https://github.com/rr-debugger/rr/issues/3468 was fixed (even without `-n`).
Please feel free to close.
