### ISSUE TITLE
SIGTERM'ing rr is broken on master with detached children

### ISSUE THREAD

**Issue by Keno** [rr-debugger/rr#3464]
Sending SIGTERM to an rr process that has two nested processes that were launched with `--nested=detach`, I see:

```
 (task 667396 (rec:667396) at time 10214)
 -> Assertion `result.code == WAIT_NO_CHILD' failed to hold. 
[FATAL src/Task.cc:161:wait_exit() errno: EINTR] 
 (task 671796 (rec:671796) at time 2378840)
 -> Assertion `result.code == WAIT_NO_CHILD' failed to hold. 
Tail of trace dump:
Tail of trace dump:
[snip]
Received SIGTERM while an earlier one was pending.  We're probably wedged.
=== Start rr backtrace:
````

I'll try to write something for the testsuite that reproduces this and see if I can fix it.

**Comment by rocallahan** [comment]
The signal-masking/handling changes I made, no doubt.

**Comment by Keno** [comment]
That's what I was thinking, but we do actually have a test for this and it's passing for me locally (though I see it failing intermittently on CI). I'm trying to come up with a minimal test case that actually shows this.
