### ISSUE TITLE
AArch64 CI started hanging

### ISSUE THREAD

**Issue by Keno** [rr-debugger/rr#3471]
There seems to be something seriously wrong with AArch64 CI on current master.

See e.g. https://buildkite.com/julialang/rr/builds/1028#0187255d-7f84-4d65-bd70-4503bb586b93 and aarch64 builds on recent PRs. 

I sampled some kernel stacks and saw a lot of this:

```
[<0>] __switch_to+0x100/0x150
[<0>] reserve_bp_slot+0x30/0x58
[<0>] register_perf_hw_breakpoint+0x40/0xb8
[<0>] hw_breakpoint_event_init+0x38/0x68
[<0>] perf_try_init_event+0x50/0x100
[<0>] perf_event_alloc+0x5e0/0x920
[<0>] perf_event_create_kernel_counter+0x38/0x148
[<0>] register_user_hw_breakpoint+0x44/0x58
[<0>] ptrace_hbp_create+0xac/0x198
[<0>] ptrace_hbp_set_addr+0xdc/0xe8
[<0>] hw_break_set+0xf8/0x540
[<0>] ptrace_regset.isra.0+0x104/0x1b0
[<0>] ptrace_request+0x440/0xc10
[<0>] arch_ptrace+0x40/0x58
[<0>] __arm64_sys_ptrace+0x80/0x178
[<0>] el0_svc_common.constprop.0+0xf4/0x200
[<0>] el0_svc_handler+0x38/0xa8
[<0>] el0_svc+0x10/0x180
```

The only thing I can think of is @rocallahan's recent change at https://github.com/rr-debugger/rr/commit/d7e5f89a20d5f9a949fdf97a541df45066f41925 which touched watchpoints.

Environmentally, I did also set `ptrace_scope` to `0` (from `1`) on the CI machine to try to get better stack traces on failure. I don't think this should affect it, but just in case.

**Comment by Keno** [comment]
I reran the master build making sure that it's the only CI job running and it ran fine. I think that gives credence to the theory that this is because of contention on that lock in the kernel.

**Comment by Keno** [comment]
I just ran a series of test jobs and even if this is a kernel bug, it does appear that d7e5f89a20d5f9a949fdf97a541df45066f41925 is the proximate cause of this appearing on CI for us. @rocallahan If I'm reading that commit correctly, the issue may be that we're now executing the the syscall also during record, not just replay, causing additional contention on this lock.

**Comment by rocallahan** [comment]
36b02f036d70a255bc877fe2df34df76b2943e46 should fix this.
