### ISSUE TITLE
Finding the program file from a trace directory?

### ISSUE THREAD

**Issue by fbrosseau** [rr-debugger/rr#3507]
Hello,

When capturing a trace, the resulting directory will contain hardlinks to various files, including the entrypoint program. Debuggers typically want to know the program they are about to debug ahead of time - in fact rr itself already does this when it suggests to the user to connect an external gdb:
gdb '-l' '10000' '-ex' 'set sysroot /' '-ex' 'target extended-remote 127.0.0.1:7953' _**/home/u/.local/share/rr/myprogram-0/mmap_hardlink_4_myprogram**_

Would it be possible to add a way to reliably find which of the files within the trace directory is the entry program?
~~I see two simple ideas:~~
~~- At recording time, create a symlink with a well-known name within the trace folder, pointing to mmap_hardlink_4_myprogram~~
~~- Add a commandline option to rr that makes it echo the entrypoint, given a trace.~~

It will be added to the `rr traceinfo` command that outputs json about a trace.

My usecase here is I have a tool programmatically using LLDB, consuming RR, and LLDB also needs to know the program being debugged, ideally without having to guess.

I can send a PR if you think one of these options would make sense.

**Comment by rocallahan** [comment]
You can get this information from the trace by replaying up to the exec. I would add this to `TraceInfoCommand`.

**Comment by rocallahan** [comment]
(which already replays up to the exec to extract the environment variables)

**Comment by fbrosseau** [comment]
Ah, I completely missed that existing feature : )
Ok will look into sending PR that adds it to that output.
