### ISSUE TITLE
Under QEMU: AMD CPU type 0x60fb0 (ext family 0) unknown

### ISSUE THREAD

**Issue by wsiok** [rr-debugger/rr#3514]
On Apple Silicon laptop in QEMU (command attached):
$ rr record -n a.out
[FATAL /home/roc/rr/rr/src/PerfCounters_x86.h:114:compute_cpu_microarch()] AMD CPU type 0x60fb0 (ext family 0) unknown
$ rr --version
rr version 5.6.0

With rr in 5.5.0:
Intel CPU type 0x60fb0 unknown

$ cat /proc/cpuinfo
processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 15
model		: 107
model name	: QEMU Virtual CPU version 2.5+
stepping	: 1
microcode	: 0x1000065
cpu MHz		: 999.961
cache size	: 512 KB
physical id	: 0
siblings	: 12
core id		: 0
cpu cores	: 12
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm rep_good nopl cpuid extd_apicid pni cx16 hypervisor lahf_lm cmp_legacy svm 3dnowprefetch vmmcall
bugs		: fxsave_leak sysret_ss_attrs null_seg swapgs_fence amd_e400 spectre_v1 spectre_v2
bogomips	: 1999.92
TLB size	: 1024 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:

QEMU is run by UTM - command attached.
[command.txt](https://github.com/rr-debugger/rr/files/11395764/command.txt)

**Comment by khuey** [comment]
Without an incredibly detailed emulation of the hardware performance monitoring unit rr will not work. An emulated x86 chip running on Apple silicon is almost certainly not capable of it. You'll need x86 hardware.

**Comment by vt-alt** [comment]
@khuey Is it possible to run rr in QEMU **KVM** on one supported CPUs? (AMD Zen2 host for example),

**Comment by rocallahan** [comment]
It is, but you have to use "host passthrough".

**Comment by vt-alt** [comment]
@rocallahan Thanks for the hint! Really some tests are working. 👍  [ps, But still this is not very usable (for distributions to `make test` after build) because of so many obscure failures.]

**Comment by rocallahan** [comment]
You would need to run the Zen workaround script in the host.
