### ISSUE TITLE
Unrecorded signal in replay at cont_syscall_boundary()

### ISSUE THREAD

**Issue by pchintalapudi** [rr-debugger/rr#3519]
Running on Linux 5.15.0-71-generic, I want to break on a function inside a yet-to-be-loaded shared object in a child process, but rr aborts between setting the breakpoint and reaching the breakpoint. Not setting the breakpoint results in a successful replay. 

Commands + backtrace are located here: https://gist.github.com/pchintalapudi/784d24c729f903b38d22d584a4b88315

I can provide the rr trace if it would be helpful.

**Comment by rocallahan** [comment]
I apologize for dropping this on the floor.

What usually happens in a bug like this is that gdb has set the breakpoint in a weird place that causes a crash when the code at the breakpoint is reached.

I'll close this. Reopen if you're still interested.
