### ISSUE TITLE
Raising SYSCALLBUF_FDS_DISABLED_SIZE is not backwards compatible

### ISSUE THREAD

**Issue by khuey** [rr-debugger/rr#3521]
#3511 increased the value of SYSCALLBUF_FDS_DISABLED_SIZE. That changed the size of the syscallbuf_fd_class member in preload_globals, and the offsets of all the following members. And that results in at least some old traces failing to replay.

**Comment by rocallahan** [comment]
Bad, sorry :-(.

I believe this breaks the use of `mprotect_records` and `reserved_legacy_breakpoint_value` only. So we could fix this by adjusting the offsets used to access those fields in replay.

**Comment by khuey** [comment]
I needed 7edebaea061cbafb85bc0cd4205457d820d60840 too.
