### ISSUE TITLE
rr ls: Add option to show trace exit status

### ISSUE THREAD

**Issue by 3v1n0** [rr-debugger/rr#3527]
I'm often launching multiple parallel execution of tests using `rr` (with meson it's quite convenient when using `--wrapper "rr record" --repeat=10`) where some of them may fail because of race conditions or so.

Now when I want to debug them with `rr replay` there's no an easy way to find which execution failed, so adding the exit code to `rr ls` would help to filter them.

**Comment by rocallahan** [comment]
`rr ps` has this information so you could script this. But yes, `rr ls` could show the exit code for the initial tracee.
