### ISSUE TITLE
Does 'BFD: warning: system-supplied DSO at 0x6fffd000 has a section extending past end of file' influence program debugging?

### ISSUE THREAD

**Issue by czg-sci-42ver** [rr-debugger/rr#3530]
I have used `set debuginfod enabled on` to download `/lib64/ld-linux-x86-64.so.2` debug info which is seen located at  `0x6fffd000` when downloading debuginfod.

And I have seen many issues showing this warning, but it seems no issue care about it. Also, when debugging, I haven't encountered problems so far.

So I want to know what influence the warning will result in.

**Comment by rocallahan** [comment]
It should be harmless. We put a special library there, but it includes its own debuginfo.
