### ISSUE TITLE
Recording GDB that sets breakpoints in multi-threaded code fails

### ISSUE THREAD

**Issue by theIDinside** [rr-debugger/rr#3537]
How to reproduce:

- Build gdb (or if you have a gdb with debug build of gdb installed)

Create the following application:

```bash
cat > stupid_threads.cpp << EOL
#include <thread>
#include <mutex>
#include <iostream>
#include <vector>

void thread_fn() {
  std::cout << "interleaved stdout is fun" << std::endl;
}


int main() {
  std::vector<std::thread> threads;
  for(auto i = 0; i < 4; i++) {
    threads.push_back(std::thread{thread_fn});
  }

  for(auto&& t : threads) {
    t.join();
  }
}
EOL

g++ -std=c++20 stupid_threads.cpp -o stupid -g3 
```

Then `rr record gdb stupid --batch -ex 'break 7' -ex 'run'` - when GDB has spawned and you're at the prompt set a breakpoint inside `thread_fn`, then `run`. GDB will fail with this error:

```
Program terminated with signal SIGTRAP, Trace/breakpoint trap.
The program no longer exists.
```

This behavior can not be observed when just running gdb.

**Comment by dzaima** [comment]
small note - equivalent behavior can be observed with
```c
void thread_fn() {
  __asm__("int3");
  std::cout << "interleaved stdout is fun" << std::endl;
}
```
instead of the manual breakpointing.

**Comment by khuey** [comment]
The root cause of this is #3524 (specifically gdb wants PTRACE_O_TRACEVFORKDONE, rr rejects the PTRACE_SETOPTIONS call with that flag, gdb doesn't check the return value, PTRACE_O_TRACECLONE doesn't end up being set, and gdb never sees the non-thread-group-leader threads).
