### ISSUE TITLE
Checkpoint fails in function with Unicode string argument

### ISSUE THREAD

**Issue by dzaima** [rr-debugger/rr#3538]
`utf.c`:
```
int f(char* s) {
  
}

int main() {
  f("↓∘⊑⊸≡ \"\"\"\"‿\"\"\n0\177\367\377");
}
```

`gcc utf.c -g3; rr record a.out; rr replay`

```
0x00007f8cb471d2b0 in _start () from /lib64/ld-linux-x86-64.so.2
(rr) checkpoint
Checkpoint 1 at   0x00007f8cb471d2b0 in _start () from /lib64/ld-linux-x86-64.so.2
(rr) b f
Breakpoint 1 at 0x55ad13042135: file utf.c, line 3.
(rr) c
Continuing.

Breakpoint 1, f (s=0x55ad13043008 "↓∘⊑⊸≡ \"\"\"\"‿\"\"\n0\177\367\377") at utf.c:3
3	}
(rr) checkpoint
(rr) checkpoint
(rr) info checkpoints
Traceback (most recent call last):
  File "<string>", line 69, in invoke
  File "<string>", line 84, in rr_cmd
ValueError: embedded null character
Error occurred in Python: embedded null character
(rr) bt
#0  f (s=0x55ad13043008 "↓∘⊑⊸≡ \"\"\"\"‿\"\"\n0\177\367\377") at utf.c:3
#1  0x000055ad1304214f in main () at utf.c:6
(rr)
```

Have traced it down to [gdb_escape](https://github.com/rr-debugger/rr/blob/8d357fffb367595939d3a6b41ceea92161a68ebb/src/GdbCommandHandler.cc#L59-L64) not handling Unicode characters, hit through [`checkpoint`s `rr-where` call](https://github.com/rr-debugger/rr/blob/8d357fffb367595939d3a6b41ceea92161a68ebb/src/GdbCommand.cc#L164).

Making it just give `?`s for non-ASCII works, but maybe it'd be better to make it properly support Unicode?

**Comment by rocallahan** [comment]
Isn't the problem gdb_unescape?

**Comment by dzaima** [comment]
`ord(curr_char)` in `gdb_escape` would be a number above 256, meaning that `format(num, '02x')` is longer than the expected two characters. Of course, if you wanted to handle unicode properly, `gdb_unescape` would need to be changed too, but `gdb_escape` is definitely also broken on it.

**Comment by rocallahan** [comment]
OK, then I think gdb_escape should produce hex-encoded UTF-8 (and gdb_unescape should consume hex-encoded UTF-8).

**Comment by dzaima** [comment]
Alright, I'll look into getting that to work.
