### ISSUE TITLE
`rr` causes Linux perf to fail

### ISSUE THREAD

**Issue by vext01** [rr-debugger/rr#3541]
Hi,

I'd like to use `rr` on a crash I'm currently debugging (I've never used `rr` before).

When naively using `rr record` on the crashy program using `rr` from the Debian 11 repo, `rr` outright crashed, so I built today's `master` branch (73cab514).

With `master`, no `rr` crash, but it caused a routine in the program to raise an error. The routine in question uses `perf_event_open()` to record a trace using Intel PT.

To dig deeper, I tried using `rr` on various `perf` invocations to see if that works:

A basic `rr` invocation works:
```
$  ~/source/rr/obj/bin/rr record  ls
rr: Saving execution to trace directory `/home/vext01/.local/share/rr/ls-1'.
file1 file2 file3
```

A basic `perf` invocation works too:
```
$ perf record ls
file1 file2 file3
[ perf record: Woken up 1 times to write data ]
[ perf record: Captured and wrote 0.012 MB perf.data (9 samples) ]
```

But `perf` doesn't work under `rr`:
```
$ ~/source/rr/obj/bin/rr record perf record ls
rr: Saving execution to trace directory `/home/vext01/.local/share/rr/perf-3'.
failed to mmap with 19 (No such device)
```

FWIW, using Intel PT with perf gives the same result:
```
$ ~/source/rr/obj/bin/rr record perf record -e intel_pt// /bin/ls
rr: Saving execution to trace directory `/home/vext01/.local/share/rr/perf-4'.
failed to mmap with 19 (No such device)
```

Is this a bug, or a known limitation of `rr`? Should it work?

Thanks

**Comment by rocallahan** [comment]
We don't support `perf_event_open` with the mmap feature. That creates data races between the kernel and the tracee that are difficult to replay correctly in rr.

We *could* implement something here but it would be a lot of work.

**Comment by vext01** [comment]
Thanks for the clarification.

Is it worth writing this somewhere in the docs/wiki in case someone else has the same issue?

**Comment by rocallahan** [comment]
I'm not sure. People who hit this probably won't find it in the documentation.

**Comment by vext01** [comment]
Your call :)

**Comment by vext01** [comment]
@rocallahan Out of curiosity, could you give a brief description of the nature of the mmap race please?

**Comment by rocallahan** [comment]
See "MMAP layout" in https://man7.org/linux/man-pages/man2/perf_event_open.2.html. The kernel writes samples to a ring buffer; the application maps that buffer into userspace and can read from the ring buffer without additional synchronization. The writes performed by the kernel to populate this buffer are not visible to rr and there is no easy way to record and replay them.

**Comment by rocallahan** [comment]
We could make this work using a technique similar to what I've proposed for handling `io_uring`: https://github.com/rr-debugger/rr/issues/2613. But it's a significant amount of work.

**Comment by vext01** [comment]
Ah, I think I get it. Because there is no syscall involved in reading the buffer, there is no opportunity to replay the contents deterministically?

It's a real shame. We are working on a JIT compiler that uses Intel PT to collect traces and we routinely have to debug JIT crashes. `rr` would have been really useful.

(Something about our system also upsets valgrind)

**Comment by rocallahan** [comment]
> Because there is no syscall involved in reading the buffer, there is no opportunity to replay the contents deterministically?

Right.

> rr would have been really useful.

FWIW if you have money I'm sure @khuey could implement this for you.
