### ISSUE TITLE
can't  find symbols 

### ISSUE THREAD

**Issue by xiashunhan** [rr-debugger/rr#3546]
![image](https://github.com/rr-debugger/rr/assets/40055704/5295989d-8dea-426f-b7f7-eb7618e649bb)

**Comment by dzaima** [comment]
This is at the very start of the executable, where there's nothing yet on the stack to symbolize. You'd want to `break main` & `continue` to get to `main()`, at which point the stack is in a more sane format and symbols should be found.

**Comment by xiashunhan** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
