### ISSUE TITLE
gdb prints on breakpoints don't show up

### ISSUE THREAD

**Issue by Hi-Angel** [rr-debugger/rr#3547]
When you set `print foo` command to be automatically executed upon reaching a breakpoint, the `print` output doesn't show up. That only happens when used with `rr` — without `rr` gdb prints everything as expected.

# Steps to reproduce

```
 λ cat -n test.c
     1  #include <stdio.h>
     2
     3  int main() {
     4      for (size_t i = 0; i < 10; ++i)
     5          puts("hi");
     6  }
 λ gcc test.c -o a -g3 -O0
 λ rr record ./a
[…]
 λ rr replay
[…]
gdb λ br test.c:5
Breakpoint 1 at 0x564f868f814b: file test.c, line 5.
gdb λ commands
Type commands for breakpoint(s) 1, one per line.
End with a line saying just "end".
>silent
>print i
>continue
>end
gdb λ c
Continuing.
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi

Program received signal SIGKILL, Killed.
0x0000000070000002 in syscall_traced ()
gdb λ
```

## Expected

The `hi` prints should be interspersed with numeric prints from `print i` gdb command

## Actual

There's no output from `print i` gdb command

# Additional information

* rr version: latest master as of 328d65f

**Comment by rocallahan** [comment]
This is really weird. It works properly if we run `rr replay -s <port>` and then connect gdb to that gdbserver. It also works without `silent`. So `silent` does something weird when we're running `gdb` under rr.

**Comment by rocallahan** [comment]
It's this:
```
def history_push(p):
    gdb.execute("rr-history-push", to_string=True)
```
If I set `to_string` to `False`, it works. It seems that when `history_push` is called by gdb for the stop event, this `gdb.execute()` call consumes the breakpoint command output into the resulting string. Indeed, gdb's `execute_fn_to_ui_file()` gets called, which just redirects a bunch of gdb internal output handles to point to a string sink while the command runs. And it looks like pending breakpoint actions (including commands) are queued up internally and then polled by `bpstat_do_actions()`, which gets called all over the place including during `gdb.execute()`, which is called in the `RRCmd` implementing `rr-history-push` :-(.

**Comment by rocallahan** [comment]
There are various ways to patch around this, but doing anything in the Python stop event that could potentially trigger `bpstat_do_actions()` is inherently dangerous and could interact poorly with breakpoint commands :-(.

**Comment by Hi-Angel** [comment]
Thank you for looking into this!

So, does that mean some change in the gdb itself is required? I may create a report to gdb if necessary.

**Comment by rocallahan** [comment]
Thanks for the offer, but I found a reasonable safe workaround for it.
