### ISSUE TITLE
Using rr on Google Cloud Compute ?

### ISSUE THREAD

**Issue by Ahmad45123** [rr-debugger/rr#3548]
Hello!

I'm trying to use rr on a GCP Compute Instance but it's complaining about a missing counter thing: 
```
[FATAL /build/rr-7fqooc/rr-5.4.0/src/PerfCounters.cc:215:start_counter() errno: ENOENT] Unable to open performance counter with 'perf_event_open'; are perf events enabled? Try 'perf record'.
```

However when I do `perf record` it does work correctly. Giving this output when I press terminate: 
```
[ perf record: Woken up 57 times to write data ]
[ perf record: Captured and wrote 17.591 MB perf.data (320263 samples) ]
```

Did anyone have success running it on google machines?

**Comment by dzaima** [comment]
`rr` requires perf counters, which some cloud platforms do not provide access to. See https://github.com/rr-debugger/rr/wiki/Will-rr-work-on-my-system and https://github.com/rr-debugger/rr/issues/1433#issuecomment-85016111
