### ISSUE TITLE
Unknown aarch64 CPU type implementer on M1

### ISSUE THREAD

**Issue by AlienKevin** [rr-debugger/rr#3550]
I'm trying to record a Rust test by running `rr record -n target/release/deps/main-dsiwfi328925d`. However, I got the following error:
```
[FATAL src/PerfCounters_aarch64.h:89:compute_cpu_microarch()] Unknown aarch64 CPU type implementer: 0x61, variant: 0x2 part: 0x28
```

Environment:
Latest Asahi Linux on an M1 MacBook Pro

**Comment by Keno** [comment]
Probably just needs to be added to the list: https://github.com/rr-debugger/rr/blob/master/src/PerfCounters_aarch64.h#L80

**Comment by AlienKevin** [comment]
@Keno Thanks for the swift response! I added a line `case 0x28` to the file you linked and rebuilt rr. However, I got a similar error with a different part number. Instead of missing 0x28, I got missing 0x29. Should I also add 0x29 to the header file?
```
[FATAL src/PerfCounters_aarch64.h:90:compute_cpu_microarch()] Unknown aarch64 CPU type implementer: 0x61, variant: 0x2 part: 0x29
```

**Comment by Keno** [comment]
Presumably one of them is the updated icestorm and the other one is the updated firestorm, so add them appropriately.

**Comment by AlienKevin** [comment]
I added `0x28` and `0x29` both under Firestorm and error is gone. Though you seemed to point out that one is for Icestorm while the other is for Firestorm? I'm not familiar with the hardware parts so not sure whether I made the correct fix.
```
case 0x61: // Apple
    switch (cpuid.part) {
    case 0x22:
    case 0x24:
      return AppleM1Icestorm;
    case 0x23:
    case 0x25:
    case 0x28:
    case 0x29:
      return AppleM1Firestorm;
    case 0x32:
      return AppleM2Blizzard;
    case 0x33:
      return AppleM2Avalanche;
    }
    break;
  }
```

**Comment by Keno** [comment]
0x28 is Icestorm: https://github.com/apple-oss-distributions/xnu/blob/rel/xnu-8792/osfmk/arm64/proc_reg.h#L2015-L2016

**Comment by AlienKevin** [comment]
That makes sense. Should I make a PR to include those two part numbers?

**Comment by rocallahan** [comment]
Yes

**Comment by AlienKevin** [comment]
PR submitted.
