### ISSUE TITLE
C/C++ API to access/manipulate the trace

### ISSUE THREAD

**Issue by xusheng6** [rr-debugger/rr#3555]
I am wondering whether there is a C/C++ API for rr so that I can directly access/manipulate the trace (e.g., to read the memory, register values, etc), which allows me to skip the GDB MI. Below is a bit background:

I am a Binary Ninja developer working on our debugger. As you may or may not notice, we are exploring the possibilities of integrating time-travel debugging capacities into our debugger. And we have already released WinDbg TTD support as a beta feature (https://dev-docs.binary.ninja/guide/dbgeng-ttd.html).

We are also adding other TTD backends and rr is a top candidate (https://github.com/Vector35/debugger/issues/487). The initial plan is to integrate with rr just like those IDEs, i.e., communicating via GDB MI. This is good enough for interactive usage. However, sometimes people might wish to do some analysis (e.g., taint tracking) on the entire trace or a major part of it. In that case, the time wasted on assembling and parsing the textual output used by the MI can be considerable.

**Comment by khuey** [comment]
You can speak the gdbserver protocol to rr.

**Comment by xusheng6** [comment]
> You can speak the gdbserver protocol to rr.

We previously tried to communicate with gdbserver using the rsp protocol, but it is a bit tricky to work with and we have largely disabled that part of code in our product. Moreover, I think rsp protocol is likely not going to have a profound performance improvement since it still requires communication over either a network connection or pipe. It is going to be faster than GDB MI since it skips the generation and parsing of the protocol text, but it is still much slower than a C/C++ API that we can call directly. This is my guess, though, I have not did solid experiments to confirm it.

I am not asking such an API to be added for our purpose. Just wish to know about it if it exists or can be created with few effort. If it is not easy to implement, we are fine with the GDB MI and interactive usage for now.

**Comment by khuey** [comment]
The only way to get data out of rr in general today is via the gdbserver protocol. You could try to unwrap that into your own C++ API that you could call directly if you don't want to talk through a socket.

**Comment by xusheng6** [comment]
> The only way to get data out of rr in general today is via the gdbserver protocol. You could try to unwrap that into your own C++ API that you could call directly if you don't want to talk through a socket.

I will look into that. Thanks for the info!

I think this issue can be closed if there is no extra input to it.

**Comment by rocallahan** [comment]
What are the performance-sensitive scenarios where you think communicating with the debugger could be a bottleneck?

**Comment by xusheng6** [comment]
> What are the performance-sensitive scenarios where you think communicating with the debugger could be a bottleneck?

There are several potential cases:

1. The user wishes to export the full trace and feed into another tool, e.g., https://github.com/gaasedelen/lighthouse
2. The user wishes to do some automated analysis on the trace, e.g., taint analysis

**Comment by rocallahan** [comment]
If you want an instruction-level execution trace using rr alone then it's inherently fairly slow because rr needs to singlestep the process.

For Pernosco we built [remix](https://robert.ocallahan.org/2020/12/rr-remix-efficient-replay-only-binary.html), which makes it possible to do this sort of thing much much faster, but that's not open source.
