### ISSUE TITLE
`ioctl` KVM_CREATE_DEVICE (0xc00caee0) causes assertion failure

### ISSUE THREAD

**Issue by paulzzy** [rr-debugger/rr#3557]
I think I'm running into the same problem as #2091, but with KVM_CREATE_DEVICE (pretty sure it matches 0xc00caee0 because of [this](https://android.googlesource.com/platform/system/sepolicy/+/master/public/ioctl_defines#1255)). Can it also be whitelisted?

For context, I'm running `rr record -F qemu-system-aarch64 --arg1 --arg2  [...]`. My host machine uses an Arm64 CPU. The `-F` is because of `strex` instructions in QEMU—I built with `-march=armv8-a+lse`, but there's some hardcoded `strex` instructions in QEMU. I'm hoping those don't affect `rr` too much.

**Comment by rocallahan** [comment]
> there's some hardcoded strex instructions in QEMU. I'm hoping those don't affect rr too much.

I suspect that's going to be a problem.

> KVM_CREATE_DEVICE

Are you actually using KVM for virtualization? That won't work under rr. If not, what's this `KVM_CREATE_DEVICE` for? I don't know anything about it. I guess it's only one of a family of calls that will be used?

**Comment by paulzzy** [comment]
>Are you actually using KVM for virtualization? That won't work under rr.

Unfortunately I am using KVM. `KVM_CREATE_DEVICE` is indeed [part of a family](https://www.kernel.org/doc/html/latest/virt/kvm/api.html). Does rr explicitly not support KVM?

**Comment by rocallahan** [comment]
Yeah, supporting KVM is infinitely hard. See #2254
