### ISSUE TITLE
vfork_done fails on ARM CI

### ISSUE THREAD

**Issue by rocallahan** [rr-debugger/rr#3560]
This seems to be 100%: https://buildkite.com/julialang/rr/builds/1271#01895e8f-6c7b-4b17-b4b8-be5e620490a5
```
Test 'vfork_done' FAILED: : token 'EXIT-SUCCESS' not in record.out:
--------------------------------------------------
FAILED at src/test/vfork_done.c:79: !(ws >> 8 == (SIGTRAP | (PTRACE_EVENT_VFORK_DONE << 8))) errno:0 (Success)
--------------------------------------------------
```

**Comment by rocallahan** [comment]
Debug logging shows that `ws` is 0x27f when we fail here. https://buildkite.com/julialang/rr/builds/1272#01896288-8d5e-47bd-a22e-b1d1c3d5290b

**Comment by rocallahan** [comment]
It looks like on x86 kernels when both `PTRACE_EVENT_VFORK_DONE` and `SIGINT` are pending they're reported in that order, but on ARM they can be reported in the other order.

**Comment by rocallahan** [comment]
Ah, the problem of course is that AArch64 doesn't have a vfork syscall at all, it uses clone with flags.

**Comment by GitMensch** [comment]
The current revision fails on both vfork_done_clone and vfork_done_clone-no-syscallbuf on Oracle's A1 computing environment, can you reproduce that failure locally on ARM, too?
Should I create a new issue for that?

**Comment by rocallahan** [comment]
It's not happening on CI. If you can still reproduce on A1, please file a new issue.
