### ISSUE TITLE
Intel CPU type 0xb06a0 unknown

### ISSUE THREAD

**Issue by pyoor** [rr-debugger/rr#3565]
Similar to https://github.com/rr-debugger/rr/issues/2614.

```
➜ rr record ls                         
[FATAL src/PerfCounters_x86.h:123:compute_cpu_microarch()] Intel CPU type 0xb06a0 unknown
```

```
➜  rr git:(master) lscpu
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         46 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  20
  On-line CPU(s) list:   0-19
Vendor ID:               GenuineIntel
  Model name:            13th Gen Intel(R) Core(TM) i9-13900H
    CPU family:          6
    Model:               186
    Thread(s) per core:  2
    Core(s) per socket:  14
    Socket(s):           1
    Stepping:            2
    CPU max MHz:         5400.0000
    CPU min MHz:         400.0000
    BogoMIPS:            5990.40
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_t
                         sc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg
                          fma cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb ssbd ibrs ibpb sti
                         bp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb intel_pt sha
                         _ni xsaveopt xsavec xgetbv1 xsaves avx_vnni dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req hfi umip pku ospke waitpkg gfni vaes vpcl
                         mulqdq tme rdpid movdiri movdir64b fsrm md_clear serialize pconfig arch_lbr ibt flush_l1d arch_capabilities
Virtualization features: 
  Virtualization:        VT-x
Caches (sum of all):     
  L1d:                   544 KiB (14 instances)
  L1i:                   704 KiB (14 instances)
  L2:                    11.5 MiB (8 instances)
  L3:                    24 MiB (1 instance)
NUMA:                    
  NUMA node(s):          1
  NUMA node0 CPU(s):     0-19
Vulnerabilities:         
  Itlb multihit:         Not affected
  L1tf:                  Not affected
  Mds:                   Not affected
  Meltdown:              Not affected
  Mmio stale data:       Not affected
  Retbleed:              Not affected
  Spec store bypass:     Mitigation; Speculative Store Bypass disabled via prctl
  Spectre v1:            Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:            Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
  Srbds:                 Not affected
  Tsx async abort:       Not affected
```

**Comment by khuey** [comment]
Looks like that value needs to be added to the `IntelRaptorLake` case in src/PerfCounters_x86.h

**Comment by prochac** [comment]
Same problem on Alder Lake
```
➜  ~ rr record ls   
[FATAL src/PerfCounters_x86.h:117:compute_cpu_microarch()] Intel CPU type 0xb06a0 unknown
```
```
➜  ~ head -n5 /proc/cpuinfo  
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 186
model name      : 13th Gen Intel(R) Core(TM) i7-1355U
```

**Comment by khuey** [comment]
> Looks like that value needs to be added to the `IntelRaptorLake` case in src/PerfCounters_x86.h

This issue needs someone with the relevant CPU to do this, run the test suite `make check` and verify that things look good, and send a PR.

**Comment by GitMensch** [comment]
@pyoor @prochac Please [build from source](https://github.com/rr-debugger/rr/wiki/Building-And-Installing) using https://github.com/GitMensch/rr/tree/patch-3 (or pull its recent commit into a newer version) and run `ctest -j$(nproc)` and tell us if that works; if yes then we can integrate those cpu types "with confidence".

**Comment by GitMensch** [comment]
Sadly the linked PR did not make it into the 5.7 release because of missing feedback by people with those processors, but as I've read releases are expected to be more often now... friendly ping @pyoor @prochac as you've showed those cpu types - can you please give that a try?

**Comment by prochac** [comment]
Sorry, missed the first call. I will give a look.

**Comment by prochac** [comment]
@GitMensch I'm running the test suite and many of them are failing. What would help you the best? Output from `ctest -j$(nproc) -VV`?

**Comment by khuey** [comment]
Are you pinning the test suite to the P-cores? (e.g. `taskset -c 0 make check`)

**Comment by prochac** [comment]
> Are you pinning the test suite to the P-cores? (e.g. `taskset -c 0 make check`)

Cool, so far the first 500 tests have passed. Why it isn't mentioned in wiki instructions, if it's important?
https://github.com/rr-debugger/rr/wiki/Building-And-Installing#tests

**Comment by prochac** [comment]
Some have failed
```
➜  obj cat Testing/Temporary/LastTestsFailed.log 
112:detach_state
113:detach_state-no-syscallbuf
128:dup
129:dup-no-syscallbuf
922:block_clone_interrupted
923:block_clone_interrupted-no-syscallbuf
924:block_clone_syscallbuf_overflow
925:block_clone_syscallbuf_overflow-no-syscallbuf
1584:detach_state-32
1585:detach_state-32-no-syscallbuf
1600:dup-32
1601:dup-32-no-syscallbuf
2394:block_clone_interrupted-32
2395:block_clone_interrupted-32-no-syscallbuf
2396:block_clone_syscallbuf_overflow-32
2397:block_clone_syscallbuf_overflow-32-no-syscallbuf
```

**Comment by khuey** [comment]
None of those look like tests that would be related to the CPU (the failures are probably related to the precise kernel version/features you're running).

**Comment by GitMensch** [comment]
I'll rebase the PR to get it integrated easily and we can then close this issue by merging the PR. In the meantime @prochac please output `uname -a && gdb --version`, along with `ctest --rerun-failed -VV`, so we get a clue where the problem is; in the end this should be moved out to separate issue(s).

**Comment by GitMensch** [comment]
> > Are you pinning the test suite to the P-cores? (e.g. `taskset -c 0 make check`)
> 
> Cool, so far the first 500 tests have passed. Why it isn't mentioned in wiki instructions, if it's important?

I've [just added that note](https://github.com/rr-debugger/rr/wiki/Building-And-Installing/_compare/add172d886a03518fb41d1a69af4052052c30ed4...c1e42646c7b16ee8fe2fd083df46c127f5ac6ac5) to https://github.com/rr-debugger/rr/wiki/Building-And-Installing#supported-hardware.

Not sure if it is reasonable to additional add a link to https://github.com/rr-debugger/rr/wiki/Building-And-Installing#hardwaresoftware-configuration from https://github.com/rr-debugger/rr/wiki/Building-And-Installing#tests.

**Comment by pyoor** [comment]
Sorry for the slow response.  I applied the patch and the following tests failed:
```
	115 - detach_threads-no-syscallbuf (Failed)
	216 - futex_restart_race (Failed)
	217 - futex_restart_race-no-syscallbuf (Failed)
	1104 - x86/rdtsc_interfering (Failed)
	1584 - detach_state-32 (Failed)
	1585 - detach_state-32-no-syscallbuf (Failed)
```

**Comment by GitMensch** [comment]
@pyoor I suggest to open a new issue that contains the results of `ctest --rerun -vv`, along with `uname -a && cat /etc/*release*.
