### ISSUE TITLE
Jasper lake n5095: "perf stat -e r5101c4 true" reports non-zero, added 0x906c0 to IntelGoldmont - rr crashes

### ISSUE THREAD

**Issue by ttsiodras** [rr-debugger/rr#3571]
Following the lead from other similar reports, I added this patch for my Celeron n5095:

    @ src/PerfCounters_x86.h:68 @ static CpuMicroarch compute_cpu_microarch() {
     case 0x506f0:
     case 0x706a0:
     case 0x506c0:
    + case 0x906c0:
      return IntelGoldmont;
     case 0x706e0:
     case 0x606a0:

...but even though perf reports non-zero events:

    # perf stat -e r5101c4 true

            48,826      r5101c4                                                               

       0.003324480 seconds time elapsed

       0.000000000 seconds user
       0.003362000 seconds sys

...rr crashes with:

    === Start rr backtrace:
    rr(_ZN2rr13dump_rr_stackEv+0x5b)[0x55740257ec4b]
    rr(_ZN2rr15notifying_abortEv+0x15)[0x55740257ecb5]
    rr(_ZN2rr12FatalOstreamD1Ev+0x63)[0x5574024398b3]
    rr(_ZN2rr12PerfCounters5resetEl+0xfee)[0x55740246d54e]
    rr(_ZN2rr4Task16resume_executionENS_13ResumeRequestENS_11WaitRequestENS_12TicksRequestEi+0xadc)[0x55740255992c]
    rr(_ZN2rr13RecordSession13task_continueERKNS0_9StepStateE+0x38f)[0x55740247bd0f]
    rr(_ZN2rr13RecordSession11record_stepEv+0x33a)[0x55740248333a]
    rr(_ZN2rr13RecordCommand3runERSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EE+0x18cd)[0x55740247682d]
    rr(main+0x1b6)[0x5574023b8c16]
    /usr/lib/libc.so.6(+0x23850)[0x7f4fe7039850]
    /usr/lib/libc.so.6(__libc_start_main+0x8a)[0x7f4fe703990a]
    rr(_start+0x25)[0x5574023ba2b5]
    === End rr backtrace
    Aborted (core dumped)

Ideas? Anything else I can try?

**Comment by rocallahan** [comment]
What was the full rr output?

**Comment by ttsiodras** [comment]
Re-tested just now, with the patch shown above applied on commit 99a5e6addd6ba1b4ecf3d08c23cb0d4e74223c66 ( current master) - and it works :-)

Should I send a PR for the patch? It's just a one-liner, but if you want me to I'll submit it.

Many thanks for your work on rr!

**Comment by rocallahan** [comment]
Sure, please send a PR!

**Comment by ttsiodras** [comment]
Here you go:

https://github.com/rr-debugger/rr/pull/3624
