### ISSUE TITLE
XSAVE offset/size/alignment differs for feature 5

### ISSUE THREAD

**Issue by maleadt** [rr-debugger/rr#3573]
... H. Peter Anvin said this would never happen!

---

I have a user-submitted trace, recorded using rr 5.6[^1] on an AMD 7950X (Zen 4), that fails with the above message when I try to replay on an Intel Xeon Silver 4114 (Skylake) running Linux 5.6[^2]. A similar trace, recorded on a AMD Ryzen 7 2700X (Zen+) replays fine on that same system, as do many other traces that have been submitted to us in the past.

1: including a couple of patches by @Keno, https://github.com/JuliaLang/rr/commits/release-5.6, most notably to mask XCR0 so that we can replay on a different system
2: the kernel is patched to support XCR0 masking

Here's the traces:

- failing (7950x): https://julialang-dumps.s3.amazonaws.com/reports/2023-07-21T19-00-54-lcw.tar.zst
- working (2700x): https://julialang-dumps.s3.amazonaws.com/reports/2023-07-21T20-50-35-lcw.tar.zst

I tried replaying on rr#master (including the XCR0 patch), which fails with the same error. @Keno suggested filing an issue if it did; I don't have much to add otherwise as I'm not really familiar with rr.

Let me know if I need to provide any other information, or try anything out on the system I was replaying on. I should also be able to ask the user that submitted the trace for more details, if needed.

**Comment by khuey** [comment]
AMD skipped the (defunct) BNDREG/BNDCSR XSAVE components when they added AVX-512 support to Zen 4, so the XSAVE layouts on AMD and Intel are no longer compatible. You can work around this by disabling AVX-512 on the Zen 4 system (e.g. booting with the `clearcpuid=304` kernel boot param).

The real fix here is to use remix to replay these traces across microarchitectures (this will mean something to @Keno).

**Comment by Keno** [comment]
Oh yikes. I guess this will change again with the extended gpr xsave component in APX. This is all really quite a mess.

**Comment by khuey** [comment]
Yeah. APX is going to reuse the defunct BNDREG/BNDCSR space on Intel. I'll be curious to see where AMD inserts the APX XSAVE component.

**Comment by khuey** [comment]
This isn't actionable on our end so I'm going to close this.
