### ISSUE TITLE
Expected EINVAL for 'bpf' but got result -1 (errno EPERM); unknown bpf(cmd=18)

### ISSUE THREAD

**Issue by DuncanSands** [rr-debugger/rr#3596]
rr version 5.6.0 
Ubuntu 23.04
Linux version 6.2.0-31-generic

While tracing a call to bpf_object.load_skeleton in libbpf, rr crashed with:

[FATAL src/record_syscall.cc:6381:rec_process_syscall_arch()] 
 (task 1209588 (rec:1209588) at time 6432)
 -> Assertion `t->regs().syscall_result_signed() == -syscall_state.expect_errno' failed to hold. Expected EINVAL for 'bpf' but got result -1 (errno EPERM); unknown bpf(cmd=18)
Tail of trace dump:
{
  real_time:612800.828069 global_time:6412, event:`SYSCALLBUF_FLUSH' tid:1209588, ticks:293
  { syscall:'gettid', ret:0x1274f4, size:0x10 }
  { syscall:'prctl', ret:0x0, size:0x10, replay_assist:1 }
  { syscall:'sigaltstack', ret:0x0, size:0x10 }
}
{
  real_time:612800.828071 global_time:6413, event:`SYSCALL: mmap' (state:ENTERING_SYSCALL) tid:1209588, ticks:293
rax:0xffffffffffffffda rbx:0x7f96b92c2fa0 rcx:0xffffffffffffffff rdx:0x3 rsi:0x2000 rdi:0x0 rbp:0x7f96b93ba2d0 rsp:0x7f96b92c2df0 r8:0xffffffff r9:0x0 r10:0x4022 r11:0x246 r12:0xffffffffffff7f28 r13:0x0 r14:0x7ffdd26f2950 r15:0x7f96b92c3000 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x9 fs_base:0x7f96b93c7680 gs_base:0x0
}
{
  real_time:612800.828072 global_time:6414, event:`SYSCALLBUF_RESET' tid:1209588, ticks:293
}
{
  real_time:612800.828085 global_time:6415, event:`SYSCALL: mmap' (state:EXITING_SYSCALL) tid:1209588, ticks:293
rax:0x7f96bc512000 rbx:0x7f96b92c2fa0 rcx:0xffffffffffffffff rdx:0x3 rsi:0x2000 rdi:0x0 rbp:0x7f96b93ba2d0 rsp:0x7f96b92c2df0 r8:0xffffffff r9:0x0 r10:0x4022 r11:0x246 r12:0xffffffffffff7f28 r13:0x0 r14:0x7ffdd26f2950 r15:0x7f96b92c3000 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x9 fs_base:0x7f96b93c7680 gs_base:0x0
  { map_file:"<ZERO>", addr:0x7f96bc512000, length:0x2000, prot_flags:"rw-p", file_offset:0x0, device:0, inode:0, data_file:"", data_offset:0x0, file_size:0x2000 }
}
{
  real_time:612800.828144 global_time:6416, event:`SYSCALLBUF_FLUSH' tid:1209588, ticks:7474
  { syscall:'getrandom', ret:0x20, size:0x30 }
  { syscall:'gettimeofday', ret:0x0, size:0x20 }
}
{
  real_time:612800.828158 global_time:6417, event:`PATCH_SYSCALL' tid:1209588, ticks:7474
rax:0x1b7 rbx:0x200 rcx:0xffffffffffffffff rdx:0x4 rsi:0x7f96c6d7b35c rdi:0xffffff9c rbp:0x4 rsp:0x7f96b93b6bf0 r8:0x6a0af8 r9:0x7f96bc512fb0 r10:0x200 r11:0x246 r12:0x0 r13:0x0 r14:0x200240501c0 r15:0x6a0b28 rip:0x7f96c5d0bc40 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xffffffffffffffff fs_base:0x7f96b93c7680 gs_base:0x0
  { tid:1209588, addr:0x7f96c6e197b6, length:0x5e }
  { tid:1209588, addr:0x7f96c5d0bc40, length:0x8 }
}
{
  real_time:612800.828159 global_time:6418, event:`SYSCALLBUF_RESET' tid:1209588, ticks:7474
}
{
  real_time:612800.828170 global_time:6419, event:`SYSCALL: faccessat2' (state:ENTERING_SYSCALL) tid:1209588, ticks:7484
rax:0xffffffffffffffda rbx:0x7f96b92c2fa0 rcx:0xffffffffffffffff rdx:0x4 rsi:0x7f96c6d7b35c rdi:0xffffff9c rbp:0x4 rsp:0x7f96b92c2df0 r8:0x6a0af8 r9:0x7f96bc512fb0 r10:0x200 r11:0x246 r12:0x0 r13:0x0 r14:0x200240501c0 r15:0x6a0b28 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x1b7 fs_base:0x7f96b93c7680 gs_base:0x0
}
{
  real_time:612800.828182 global_time:6420, event:`SYSCALL: faccessat2' (state:EXITING_SYSCALL) tid:1209588, ticks:7484
rax:0x0 rbx:0x7f96b92c2fa0 rcx:0xffffffffffffffff rdx:0x4 rsi:0x7f96c6d7b35c rdi:0xffffff9c rbp:0x4 rsp:0x7f96b92c2df0 r8:0x6a0af8 r9:0x7f96bc512fb0 r10:0x200 r11:0x246 r12:0x0 r13:0x0 r14:0x200240501c0 r15:0x6a0b28 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x1b7 fs_base:0x7f96b93c7680 gs_base:0x0
}
{
  real_time:612800.828270 global_time:6421, event:`SYSCALLBUF_FLUSH' tid:1209588, ticks:27895
  { syscall:'openat', ret:0x32, size:0x10, desched:1 }
  { syscall:'readlinkat', ret:0x17, size:0x27 }
  { syscall:'fstatat', ret:0x0, size:0xa0 }
  { syscall:'read', ret:0x22, size:0x32, desched:1 }
  { syscall:'read', ret:0x0, size:0x10, desched:1 }
  { syscall:'close', ret:0x0, size:0x10 }
}
{
  real_time:612800.828273 global_time:6422, event:`SYSCALL: bpf' (state:ENTERING_SYSCALL) tid:1209588, ticks:27895
rax:0xffffffffffffffda rbx:0x7f96b92c2fa0 rcx:0xffffffffffffffff rdx:0x74 rsi:0x7f96b93b6e10 rdi:0x5 rbp:0x7f96c6d92188 rsp:0x7f96b92c2df0 r8:0x6 r9:0xa000000085 r10:0x1 r11:0x246 r12:0x7f96c6d92020 r13:0x6566f0 r14:0x20024040050 r15:0x0 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x141 fs_base:0x7f96b93c7680 gs_base:0x0
}
{
  real_time:612800.828274 global_time:6423, event:`SYSCALLBUF_RESET' tid:1209588, ticks:27895
}
{
  real_time:612800.828520 global_time:6424, event:`SYSCALL: bpf' (state:EXITING_SYSCALL) tid:1209588, ticks:27895
rax:0x32 rbx:0x7f96b92c2fa0 rcx:0xffffffffffffffff rdx:0x74 rsi:0x7f96b93b6e10 rdi:0x5 rbp:0x7f96c6d92188 rsp:0x7f96b92c2df0 r8:0x6 r9:0xa000000085 r10:0x1 r11:0x246 r12:0x7f96c6d92020 r13:0x6566f0 r14:0x20024040050 r15:0x0 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x141 fs_base:0x7f96b93c7680 gs_base:0x0
}
{
  real_time:612800.828549 global_time:6425, event:`SYSCALLBUF_FLUSH' tid:1209588, ticks:27951
  { syscall:'close', ret:0x0, size:0x10 }
}
{
  real_time:612800.828552 global_time:6426, event:`SYSCALL: bpf' (state:ENTERING_SYSCALL) tid:1209588, ticks:27951
rax:0xffffffffffffffda rbx:0x7f96b92c2fa0 rcx:0xffffffffffffffff rdx:0x80 rsi:0x7f96b93b6e50 rdi:0x5 rbp:0x7f96c6d7b1e1 rsp:0x7f96b92c2df0 r8:0x0 r9:0x2 r10:0x2 r11:0x246 r12:0x80 r13:0x7f96b93b6e50 r14:0x7f96b93b6e50 r15:0x0 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x141 fs_base:0x7f96b93c7680 gs_base:0x0
}
{
  real_time:612800.828553 global_time:6427, event:`SYSCALLBUF_RESET' tid:1209588, ticks:27951
}
{
  real_time:612800.828699 global_time:6428, event:`SYSCALL: bpf' (state:EXITING_SYSCALL) tid:1209588, ticks:27951
rax:0x32 rbx:0x7f96b92c2fa0 rcx:0xffffffffffffffff rdx:0x80 rsi:0x7f96b93b6e50 rdi:0x5 rbp:0x7f96c6d7b1e1 rsp:0x7f96b92c2df0 r8:0x0 r9:0x2 r10:0x2 r11:0x246 r12:0x80 r13:0x7f96b93b6e50 r14:0x7f96b93b6e50 r15:0x0 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x141 fs_base:0x7f96b93c7680 gs_base:0x0
}
{
  real_time:612800.828717 global_time:6429, event:`SYSCALLBUF_FLUSH' tid:1209588, ticks:29043
  { syscall:'close', ret:0x0, size:0x10 }
}
{
  real_time:612800.828718 global_time:6430, event:`SYSCALL: bpf' (state:ENTERING_SYSCALL) tid:1209588, ticks:29043
rax:0xffffffffffffffda rbx:0x7f96b92c2fa0 rcx:0xffffffffffffffff rdx:0x1c rsi:0x7f96b93b6d90 rdi:0x12 rbp:0x2d rsp:0x7f96b92c2df0 r8:0x7f96bc512fb0 r9:0x200240004a8 r10:0x7f96bc512c20 r11:0x246 r12:0x200241100c0 r13:0x7f96b93b6d90 r14:0x2d r15:0x0 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x141 fs_base:0x7f96b93c7680 gs_base:0x0
}
{
  real_time:612800.828719 global_time:6431, event:`SYSCALLBUF_RESET' tid:1209588, ticks:29043
}

**Comment by khuey** [comment]
I think that's `BPF_BTF_LOAD` which rr doesn't yet support. I don't think it would be that hard to support, the handling of e.g. `BPF_PROG_LOAD` is pretty simple.

**Comment by CunningBaldrick** [comment]
It works - thanks very much.
