### ISSUE TITLE
Does rr work on any model of raspberry-pi?

### ISSUE THREAD

**Issue by zhongweiy** [rr-debugger/rr#3598]

**Comment by Keno** [comment]
I don't think anybody has tried, but I believe the answer is no. In particular, rr generally only works on systems with LSE atomics, which are only found on higher-end aarch64 processors.

**Comment by zhongweiy** [comment]
Thanks for your reply! Do you mind share which exactly LSE feature rr depends? If they depends on instructions like load acquire/store release, I think they can be done by other none LSE instructions with worse performance. So it seems not a hard blocker.

**Comment by Keno** [comment]
No, the issue is that ll/sc fails in ways that usually there are no hardware counters to observe, so rr can't record any application that uses ll/sc atomics, which is usually all of them unless lse is available.

**Comment by zhongweiy** [comment]
Got it, thanks!
