### ISSUE TITLE
WaitManager led to outdated docs

### ISSUE THREAD

**Issue by GitMensch** [rr-debugger/rr#3604]
With ea1d4f2b6d1f58c71b369b75c64fb90754b4b615 [`Task::wait_exit()`](https://github.com/rr-debugger/rr/commit/ea1d4f2b6d1f58c71b369b75c64fb90754b4b615#diff-f0f690a2d3f8bbc1568eb999cb842fbc011e3caabc444f7a2695d7c0ccc36c18) got severely changed, effectively moving the code the comment still talks about https://github.com/rr-debugger/rr/blob/5817b78d83eb78b05f618813a95cdf54cff01b5b/src/Task.cc#L130-L144 to the new WaitManager.cc.

@rocallahan As this is your code, can you please move the relevant part of the comments (most seem to apply to `WaitManager::wait()` called by `WaitManager::wait_stop()`, but not in its caller) and leave only in what is relevant?

**Comment by rocallahan** [comment]
The comment still belongs here.
