### ISSUE TITLE
How to debug multiple inferiors simultaniously?

### ISSUE THREAD

**Issue by robertu94** [rr-debugger/rr#3608]
`rr` is a neat tool.  I was trying to use it in the context of distributed MPI programs in order to add support to my tool [mpigdb](https://github.com/robertu94/mpigdb). Unlike traditional multi-process programs, MPI programs are started by an external process manager (possibly on another node in a cluster by a process that we do not have rights over).  I figured out how to get `rr` to output to a programmatically defined trace location (e.g. `-o $PROGRAM_NAME-$MPI_COMM_RANK`), and I figured out how to load a specific replay with `rr replay -s $PORT_FOR_RANK $TRACE_FILE` which I do for each rank separately, followed by calls to `gdb` with `add-inferior`, `target extended-remote` etc... to connect each process, and finally, I run source on the file created by `rr gdbinit`.  However, when I do so I run into a few challenges:

1. `rr` doesn't support gdb's `non-stop` mode terminating with an error message when attempting to use it.  Not using `no-stop` mode makes things hang and/or are really slow making difficult to control multiple processes at once.  I think this issue was raised before in #488 but the last update to this was almost a decade ago, and I was wondering if this situation has changed.
2. I can get assertion failures in GDB, but I haven't figured out how to reproduce this, and this could just be an issue in GDB non-stop mode itself.
3. Once I issue `thread apply all continue &` rr seems to hang indefinitely and I am unable to issue `interrupt` to the remotes.

I see that some similar issues were brought up in #2710.  I was wondering if @Keno could comment more on how he was able to run rr at scale in HPC.

**Comment by rocallahan** [comment]
1: No, we haven't done anything to implement non-stop mode or gdb multiprocess support. Basically Kyle Huey and I decided to focus our efforts for better debugger UI on https://pernos.co and no-one else has stepped up. If someone wanted to do it, we'd take it (assuming code and tests are adequate of course).

3: Not sure what's happening there. Is it possible to reproduce the bug in a plain gdb session?

It sounds like your tool does something clever to coordinate multiple processes so they don't get "out of order" with respect to happens-before relationships induced by MPI communication? That sounds cool.

**Comment by robertu94** [comment]
> 1.  decided to focus ... on pernos.co ...

understandable

> 3. possible to reproduce in a plain gdb session?

Yes. I actually prototyped this with plain GDB before trying to implement in MPIGDB.  MPIGDB is essentially a startup script that collaborates with the MPI process launcher. So nothing here is "special" yet.

> It sounds like your tool does something clever to coordinate multiple processes so they don't get "out of order" with respect to happens-before relationships induced by MPI communication. That sounds cool.

My interest in `rr` in the distributed context is primarily to serve as a comparison to our approach which leverages knowledge of an application-level checkpoint restart library in the application.  In our approach, we know we can safely rewind or fast forward to any checkpoint because the application needs to support this to perform checkpoint-restart.  Since at the tool level we only export a collective rewind/fast forward, in principle, we shouldn't get out of order unless a user invokes underlying commands.  We then add a series of extensions to diff between the current state and checkpoints.  

Doing what you are suggesting where we allow individual process re-wind is interesting, but I suspect very difficult absent a full trace and preprocessing to resolve arguments like MPI_ANY_SOURCE or MPI_ANY_TAG on sends and receives.  With this trace, you could look up the corresponding "required" states and force rewind/fast-forward the other states after solving for a consistent state which I expect but have not proven requires a SAT solver.

**Comment by rocallahan** [comment]
> Yes.

If you've got steps to reproduce that you can share, we can investigate this as an rr bug.

**Comment by robertu94** [comment]
Here is the application:

https://github.com/robertu94/mpigdb/blob/main/play/heatdist.cc

It requires only MPI and https://github.com/kokkos/mdspan as dependencies.  I used MPICH, and compiled with RelWithDebInfo (-O2 -g)

```bash
mpiexec -np 2 rr record ./heatdist
```

To replay, I ran

```bash
for i in {0..1}; do
rr replay -s $(( i + 8000)) heatdist-$i & 
done
wait
```
Then I used the following GDB script:
```gdb
target extended-remote 127.0.0.1:8000
add-inferior -no-connection
inferior 2
target extended-remote 127.0.0.1:8001
thread apply all continue &
```

**Comment by rocallahan** [comment]
OK this fails because MPI uses shared memory to communicate between a process in the recording and a process outside the recording (which happens to be in another recording, but that doesn't help us). rr doesn't support that.

Running with `MPICH_NO_LOCAL=1` fixes it. You could also run the entire `mpiexec` under rr, which has different tradeoffs.

**Comment by robertu94** [comment]
Thanks @rocallahan for looking into these failures. I'll give these a try.
