### ISSUE TITLE
different lines in `reverse-step` (gdb bug?) 

### ISSUE THREAD

**Issue by GitMensch** [rr-debugger/rr#3628]
when doing a `step` I get through the code as expected, doing a `reverse-step`/`rs` gdb stops in at least the following two functions:

`_dl_runtime_resolve_xsavec () at ../sysdeps/x86_64/dl-trampoline.h:153
`__memset_evex_unaligned_erms () at ../sysdeps/x86_64/multiarch/memset-vec-unaligned-erms.S:268`

Where is the actual issue? RR, gdb, something else? Is it possible to do anything about that? 
Note: This is `GNU gdb (Debian 10.1-1.7) 10.1.90.20210103-git`.

Workaround: Start each replay with ` rr replay -o -q -o -ex -o "skip -gfile */sysdeps/x86_64/*"` (yes, the `-o -q` is not needed, not sure if it is possible to shorten that line)

**Comment by rocallahan** [comment]
This is a gdb issue. rr doesn't know anything about source lines.
