### ISSUE TITLE
[Question] The relationship between rr's scheduler and the system's scheduler

### ISSUE THREAD

**Issue by zouyonghao** [rr-debugger/rr#3640]
Hi rrers,

I am confused about the scheduler and determinism of recording in rr, especially when thinking it with the system's scheduler together.

For my current understanding, rr's scheduler can only affect the execution when an event is received. Some events are deterministic, like syscalls. Some events are not, like the PERF_COUNT_SW_CONTEXT_SWITCHES, which is triggered by the system's scheduler. For any given time, there is only one thread whose status is not "stop", while others are stopped by a ptrace event. So, the recording is not deterministic even we have our own scheduler in rr, because the system's scheduler may interrupt the execution process. But if we do not switch for the event that is interrupting by system's scheduler, then the recording process is deterministic.

I want to know if I am correct, or I missed something?

**Comment by khuey** [comment]
The system scheduler can interrupt the tracee to schedule non-tracee execution (e.g. a hardware interrupt, or another task that's not part of the recording). But we only allow one tracee task to execute at a time, so there's no danger of the system scheduler interrupting a tracee task to schedule another tracee task.

One of the assumptions of rr is that intervening non-tracee execution won't affect tracee execution. This is not true in all cases. Hardware interrupts affecting the LL/SC pattern instructions is why rr doesn't support AArch32. This is also why tracee tasks cannot share memory with tasks outside the trace (e.g. X11's DRI has to be disabled). But it is true in the vast majority of cases.

**Comment by rocallahan** [comment]
What exactly do you mean by "deterministic execution"? There are many sources of nondeterminism beyond just the scheduler. rr tries to capture them all so it can replay the recording faithfully, but it doesn't try to make different recordings behave in the same way.

**Comment by zouyonghao** [comment]
I mean the deterministic execution during recording, though it is beyond the original goal of rr. During recording, if I write a new scheduler in rr that tries to control the thread switching, e.g. switching the thread deterministically by every 50 ticks, then the execution is deterministic. For my current understanding, it is not possible to do that, right?

**Comment by rocallahan** [comment]
Right.

One problem is that "50 ticks" does not identify a specific program point. That's partly because each tick is a conditional branch execution, not an individual instruction, and also when you ask the hardware to interrupt after 50 ticks the actual interrupt doesn't happen until many ticks later.

**Comment by zouyonghao** [comment]
Thank you very much!
