### ISSUE TITLE
`rr` calls virtual method of base class?

### ISSUE THREAD

**Issue by k-sareen** [rr-debugger/rr#3641]
Okay this is a weird bug. The gist is that `rr` seems to be calling the virtual method of the base class instead of the derived class (in C++). This results in all sorts of wonky behaviour when trying to debug. Here's a minimum working example: [rr_bug.zip](https://github.com/rr-debugger/rr/files/13234725/rr_bug.zip)

Output:
```console
$ g++ rr_bug.cc -O0 -o rr_bug -std=c++17
$ ./rr_bug
Calling Run function for 0x561ef4a0eeb0
Called Derived::Run function for 0x561ef4a0eeb0
$ rr record ./rr_bug
rr: Saving execution to trace directory `/home/$USER/.local/share/rr/rr_bug-1'.
Calling Run function for 0x55843e3efeb0
Called Base::Run function for 0x55843e3efeb0
$ rr --version
rr version 5.6.0
```

The context is that code similar to the above is used in threading code. There's a base worker thread class and then specialized worker classes which override the `Run` function. What is occurring is that the specialized worker classes are calling the `Run` function for the base worker class which leads to internal consistency issues.

I'm unsure why this is happening for `rr`. For what it's worth, this does not occur on `gdb` (but `gdb` is not as powerful as `rr` which makes debugging painful).

**Comment by k-sareen** [comment]
Actually never mind. I realized I'm not using the latest `rr` version. It seems to be fixed in the latest `rr` version. Apologies. Rookie mistake.

**Comment by Keno** [comment]
Your C++ code has a race condition and/or undefined behavior (depending on how you read the C++ standard). The vtable of the derived class is not set up until its constructor runs, but you're spawning a thread in the base class constructor. If the thread gets scheduled before that, things blow up. The behavior observed under rr is a different (but valid) schedule. You could see the same without rr also depending on the kernel schedule.

**Comment by khuey** [comment]
You're calling a virtual function from a constructor on another thread. Your code is inherently racy as to which wins.

**Comment by k-sareen** [comment]
Ah I see. Thanks for the input! I'll have to rewrite the threading code to remove the race then.
