### ISSUE TITLE
tick mismatch in `rr replay` which was `rr pack`ed on another machine

### ISSUE THREAD

**Issue by GitMensch** [rr-debugger/rr#3642]
This was seen by @rocallahan in and is "show-stopping" the analyze of https://github.com/rr-debugger/rr/issues/3618.
Packed recording from there: [STR.tar.gz](https://github.com/rr-debugger/rr/files/12742617/STR.tar.gz)

**Expectation:** `rr pack` includes everything so that a `rr replay` is possible on other machines.

**Note:** I'm not sure if this actually _should_ work, given the likely not matching kernel version.
If this is unlikely, then `rr replay` should do some checking instead of running into a known tick mismatch, as is done with:

> [FATAL src/ReplaySession.cc:209:ReplaySession()] Trace was recorded on a machine with different CPUID values and CPUID faulting is not enabled; replay will not work.

**Comment by khuey** [comment]
WFM.

**Comment by GitMensch** [comment]
What works for you?
You don't get the ticks mismatch or you get a nice error (but not the CPUID one)?

In the first case  - checking the referenced issue would be _very_ helpful to me as this is the biggest issue I face with using rr for application debugging.

**Comment by khuey** [comment]
It replays fine for me.

**Comment by GitMensch** [comment]
@rocallahan Do you still get a tick mismatch with that? If not, then we can close it?

**Comment by khuey** [comment]
In general traces are not necessarily portable across microarchitectures, so even if he does see a divergence it may well be in something that rr can't do anything about.

**Comment by GitMensch** [comment]
Wouldn't it be reasonable to then record and compare the cpu code?

**Comment by khuey** [comment]
> compare the cpu code

I don't know what that means.
