### ISSUE TITLE
`info threads` corrupts `when-ticks` when not in main thread

### ISSUE THREAD

**Issue by dzaima** [rr-debugger/rr#3643]
```c
#include<pthread.h>
#include<unistd.h>

void foo() { }

static void* start_thread(__attribute__((unused)) void* p) {
  foo();
  sleep(1000);
  return NULL;
}

int main(void) {
  pthread_t thread;
  pthread_create(&thread, NULL, start_thread, NULL);
  sleep(1);
  return 0;
}
```
and `rr replay` session:
```c
(rr) b foo
Breakpoint 1 at 0x55dd591f6154
(rr) c
Continuing.
[New Thread 232997.232998]
[Switching to Thread 232997.232998]

Thread 2 hit Breakpoint 1, 0x000055dd591f6154 in foo ()
(rr) when-ticks
Current tick: 47
(rr) info threads
  Id   Target Id                    Frame
  1    Thread 232997.232997 (a.out) 0x00007f01e08e57f8 in clock_nanosleep () from /lib/x86_64-linux-gnu/libc.so.6
* 2    Thread 232997.232998 (a.out) 0x000055dd591f6154 in foo ()
(rr) when-ticks
Current tick: 36801
```
seems it switches to the tick count of thread 1

**Comment by khuey** [comment]
This seems to be a gdb bug unfortunately.

```
(rr) info thread
[remote] Sending packet: $qfThreadInfo#bb
[remote] Packet received: mp12b7f.12b7f,p12b7f.12b80
[remote] Sending packet: $qsThreadInfo#c8
[remote] Packet received: l
[remote] Sending packet: $qThreadExtraInfo,p12b7f.12b7f#e7
[remote] Packet received: 7465737400
[remote] Sending packet: $qThreadExtraInfo,p12b7f.12b80#b2
[remote] Packet received: 7465737400
  Id   Target Id                 Frame
[remote] Sending packet: $Hgp12b7f.12b7f#11
[remote] Packet received: OK
[remote] Sending packet: $g#67
[remote] Packet received: daffffffffffffff01fffffffffffffffffffffffffffffff00d438dfc7f0000000000000000000000000000000000000000000000000000600d438dfc7f0000000000000000000040f63fe40f7f0000f00d438dfc7f00004602000000000000f00d438dfc7f00000000000000000000f00d438dfc7f000040907de40f7f0000f8574ee40f7f000046020000330000002b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007f0300000000000000000000 [1128 bytes omitted]
  1    Thread 76671.76671 (test) 0x00007f0fe44e57f8 in __GI___clock_nanosleep ([remote] Sending packet: $m7ffc8d430dc0,40#8d
[remote] Packet received: bf41d517eb550000b06dd517eb55000040907de40f7f000077a64ee40f7f00000000000000000000aea54ee40f7f000001000000000000000000000000000000
[remote] Sending packet: $m7ffc8d430d40,40#5e
[remote] Packet received: 000000000000000000000000000000000000000000000000e1574ee40f7f00000000000000000000000000000000000000000000000000000000000000000000
clock_id=clock_id@entry=0, flags=flags@entry=0, [remote] Sending packet: $m7ffc8d430e00,40#5b
[remote] Packet received: 400e438dfc7f000000a1b517c23e9a4abf41d517eb5500000000000000000000400e438dfc7f00000142d517eb55000040f63fe40f7f000000a1b517c23e9a4a
[remote] Sending packet: $m7ffc8d430e40,40#5f
[remote] Packet received: 0100000000000000909d42e40f7f00000000000000000000bf41d517eb5500000000000001000000580f438dfc7f00000000000000000000a9b130bec668052b

    req=req@entry=0x7ffc8d430df0, rem=rem@entry=0x7ffc8d430df0) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:78
* 2    Thread 76671.76672 (test) foo () at test.c:4
```

That `$Hgp12b7f.12b7f#11` sets the current thread to thread 76671 (thread 1). gdb likely does this to get the registers for that thread so it can figure out the current stack frame on it. But it doesn't switch the current thread back afterwards. You might be able to work around it. Executing `up` seems sufficient to get gdb to switch to the correct thread, for instance.

**Comment by dzaima** [comment]
Is GDB required to keep the current thread proper always? A first `up` gives a `Hgp[whatever]` switching the thread back, but after that it doesn't; perhaps it has a mechanism to delay switching to actual-current-thread, but thinks rr's `qRRCmd:7768656e2d7469636b73` doesn't need it?

**Comment by khuey** [comment]
The remote target (rr here) remembers the current thread last set via the protocol (the `H` packet), so gdb only needs to send a packet to set the current thread if its changed from the previous command. After `info threads` the thread last set via the protocol is different from what gdb thinks the current thread is. Based on `up` working it appears gdb will send another `H` packet before it does something that needs the current thread to be right. But gdb doesn't know anything about `qRRCmd`.

The potential fixes here would be for gdb to eagerly reset the current thread after `info threads` or for the `qRRCmd` implementation to force the current thread to be updated. Not sure there's any means that's side effect free to accomplish the latter though (e.g. running `up` before every `qRRCmd` would leave the stack in the wrong place, in addition to generating visual clutter).

**Comment by dzaima** [comment]
The gdb code responsible for generating `Hg` events is https://sourceware.org/git/?p=binutils-gdb.git;a=blob;f=gdb/remote.c;h=69271048da24ddaea1556e1b0780410fe9d77977;hb=HEAD#l3104 I believe? (more specifically, the following `set_general_thread`, with `record_currthread` also updating the `rs->general_thread` cache from e.g. `thread 1`'s `T` packet)

Indeed doesn't seem like there's any intent for the current thread to be in a consistent state outside of operations directly requiring its correctness, nor do I see anything that'd allow explicitly switching it.

Perhaps what could be done is making the generated `qRRCmd` request include the intended thread itself (via python `gdb.selected_thread().ptid`) and the remote then temporarily switches to it as needed?

**Comment by rocallahan** [comment]
In https://buildkite.com/julialang/rr/builds/1588#018cc2eb-68be-4626-aee4-5293ee9c4be0/294-6334 the `maintenance flush register-cache` seems to not have worked :-(.

**Comment by rocallahan** [comment]
Fixing that with https://github.com/rr-debugger/rr/commit/d142cc9dd2f9b576ee0f80a4dfe87f721b75729a
