### ISSUE TITLE
 fatal error: linux/openat2.h: No such file or directory

### ISSUE THREAD

**Issue by MadhuriPatil1694** [rr-debugger/rr#3655]
Getting error after doing following steps
$ uname -r
5.10.104-tegra
$git clone https://github.com/rr-debugger/rr.git
$mkdir obj && cd obj
$cmake -DCMAKE_BUILD_TYPE=Release ../rr
make -j8
[  0%] Built target test-monitor
[  0%] Built target Generated
[  0%] Built target tick0
[  1%] Built target starvation_multithreaded
[  0%] Built target mmap_bits
[  1%] Built target starvation_singlethreaded
[  1%] Built target mmap_adjacent
[  1%] Built target getaffinity_core_count
Scanning dependencies of target close_range
Scanning dependencies of target clone_untraced
Scanning dependencies of target dup
Scanning dependencies of target ioctl_tty
Scanning dependencies of target sync
[  1%] Built target counters
[  1%] Built target ftrace_helper
[  2%] Built target core_count
[  3%] Building C object CMakeFiles/clone_untraced.dir/src/test/clone_untraced.c.o
[  3%] Building C object CMakeFiles/close_range.dir/src/test/close_range.c.o
[  3%] Building C object CMakeFiles/dup.dir/src/test/dup.c.o
Scanning dependencies of target pid_ns_kill_child_threads
Scanning dependencies of target grandchild_threads_main_running
Scanning dependencies of target clone_fail
[  3%] Building C object CMakeFiles/ioctl_tty.dir/src/test/ioctl_tty.c.o
[  3%] Building C object CMakeFiles/sync.dir/src/test/sync.c.o
[  3%] Building C object CMakeFiles/pid_ns_kill_child_threads.dir/src/test/pid_ns_kill_child_threads.c.o
[  3%] Building C object CMakeFiles/grandchild_threads_main_running.dir/src/test/grandchild_threads_main_running.c.o
[  3%] Building C object CMakeFiles/clone_fail.dir/src/test/clone_fail.c.o
[  3%] Linking C executable bin/clone_untraced
[  3%] Linking C executable bin/dup
[  3%] Linking C executable bin/close_range
[  3%] Linking C executable bin/sync
[  3%] Linking C executable bin/grandchild_threads_main_running
[  3%] Linking C executable bin/clone_fail
[  3%] Linking C executable bin/pid_ns_kill_child_threads
[  3%] Linking C executable bin/ioctl_tty
[  3%] Built target clone_untraced
[  3%] Built target dup
[  3%] Built target close_range
Scanning dependencies of target flock2
[  3%] Built target sync
Scanning dependencies of target clone_vfork_pidfd
Scanning dependencies of target no_mask_timeslice
[  3%] Building C object CMakeFiles/flock2.dir/src/test/flock2.c.o
Scanning dependencies of target sigaltstack
[  3%] Built target grandchild_threads_main_running
[  3%] Building C object CMakeFiles/no_mask_timeslice.dir/src/test/no_mask_timeslice.c.o
[  3%] Building C object CMakeFiles/clone_vfork_pidfd.dir/src/test/clone_vfork_pidfd.c.o
[  3%] Built target clone_fail
Scanning dependencies of target pid_ns_shutdown
[  3%] Built target pid_ns_kill_child_threads
Scanning dependencies of target mprotect_stack
[  3%] Building C object CMakeFiles/sigaltstack.dir/src/test/sigaltstack.c.o
[  3%] Built target ioctl_tty
Scanning dependencies of target futex_exit_race
[  3%] Building C object CMakeFiles/pid_ns_shutdown.dir/src/test/pid_ns_shutdown.c.o
[  3%] Building C object CMakeFiles/mprotect_stack.dir/src/test/mprotect_stack.c.o
[  3%] Building C object CMakeFiles/futex_exit_race.dir/src/test/futex_exit_race.c.o
[  4%] Built target tick0_less
Scanning dependencies of target signal_deferred
[  4%] Building C object CMakeFiles/signal_deferred.dir/src/test/signal_deferred.c.o
[  5%] Linking C executable bin/flock2
[  5%] Built target flock2
Scanning dependencies of target getsid
[  5%] Linking C executable bin/clone_vfork_pidfd
[  5%] Building C object CMakeFiles/getsid.dir/src/test/getsid.c.o
[  5%] Linking C executable bin/sigaltstack
[  5%] Linking C executable bin/mprotect_stack
[  5%] Built target clone_vfork_pidfd
[  5%] Built target sigaltstack
Scanning dependencies of target cwd_inaccessible
Scanning dependencies of target orphan_process
[  5%] Building C object CMakeFiles/cwd_inaccessible.dir/src/test/cwd_inaccessible.c.o
[  5%] Building C object CMakeFiles/orphan_process.dir/src/test/orphan_process.c.o
[  5%] Linking C executable bin/pid_ns_shutdown
[  5%] Built target mprotect_stack
[  5%] Linking C executable bin/futex_exit_race
[  5%] Linking C executable bin/signal_deferred
[  5%] Linking C executable bin/no_mask_timeslice
Scanning dependencies of target futex_restart_race
[  5%] Building C object CMakeFiles/futex_restart_race.dir/src/test/futex_restart_race.c.o
[  5%] Built target pid_ns_shutdown
[  5%] Built target signal_deferred
Scanning dependencies of target clock
[  5%] Built target futex_exit_race
[  5%] Built target no_mask_timeslice
Scanning dependencies of target io
Scanning dependencies of target samask
Scanning dependencies of target shared_monitor
[  5%] Building C object CMakeFiles/clock.dir/src/test/clock.c.o
[  5%] Linking C executable bin/getsid
[  5%] Building C object CMakeFiles/io.dir/src/test/io.c.o
[  5%] Building C object CMakeFiles/samask.dir/src/test/samask.c.o
[  5%] Building C object CMakeFiles/shared_monitor.dir/src/test/shared_monitor.c.o
[  5%] Built target getsid
Scanning dependencies of target clone_immediate_exit
[  5%] Linking C executable bin/cwd_inaccessible
[  6%] Linking C executable bin/orphan_process
[  6%] Building C object CMakeFiles/clone_immediate_exit.dir/src/test/clone_immediate_exit.c.o
[  6%] Built target cwd_inaccessible
Scanning dependencies of target mremap_private_grow_under_map
[  6%] Linking C executable bin/futex_restart_race
[  6%] Built target orphan_process
Scanning dependencies of target chew_cpu
[  6%] Building C object CMakeFiles/mremap_private_grow_under_map.dir/src/test/mremap_private_grow_under_map.c.o
[  6%] Building C object CMakeFiles/chew_cpu.dir/src/test/chew_cpu.c.o
[  6%] Linking C executable bin/clock
[  6%] Linking C executable bin/samask
[  6%] Linking C executable bin/io
[  6%] Built target futex_restart_race
[  6%] Linking C executable bin/shared_monitor
Scanning dependencies of target ptrace_syscall
[  6%] Built target clock
[  6%] Building C object CMakeFiles/ptrace_syscall.dir/src/test/ptrace_syscall.c.o
[  6%] Built target samask
Scanning dependencies of target ioprio
Scanning dependencies of target many_yields
[  6%] Built target io
[  6%] Built target shared_monitor
[  6%] Building C object CMakeFiles/ioprio.dir/src/test/ioprio.c.o
Scanning dependencies of target acct
[  6%] Linking C executable bin/clone_immediate_exit
[  7%] Building C object CMakeFiles/many_yields.dir/src/test/many_yields.c.o
Scanning dependencies of target ioctl_br
[  7%] Building C object CMakeFiles/acct.dir/src/test/acct.c.o
[  7%] Building C object CMakeFiles/ioctl_br.dir/src/test/ioctl_br.c.o
[  7%] Built target clone_immediate_exit
[  8%] Linking C executable bin/mremap_private_grow_under_map
Scanning dependencies of target crash
[  8%] Building C object CMakeFiles/crash.dir/src/test/crash.c.o
[  8%] Linking C executable bin/chew_cpu
[  8%] Built target mremap_private_grow_under_map
Scanning dependencies of target prctl
[  8%] Building C object CMakeFiles/prctl.dir/src/test/prctl.c.o
[  9%] Linking C executable bin/ptrace_syscall
[  9%] Built target chew_cpu
[  9%] Linking C executable bin/ioprio
[  9%] Linking C executable bin/many_yields
[  9%] Built target pipe_wakeup
[  9%] Linking C executable bin/acct
Scanning dependencies of target intr_ptrace_decline
[  9%] Built target ptrace_syscall
[  9%] Linking C executable bin/ioctl_br
[  9%] Building C object CMakeFiles/intr_ptrace_decline.dir/src/test/intr_ptrace_decline.c.o
[  9%] Built target ioprio
Scanning dependencies of target arch_prctl
Scanning dependencies of target sched_attr
[  9%] Built target many_yields
[  9%] Building C object CMakeFiles/arch_prctl.dir/src/test/arch_prctl.c.o
[  9%] Building C object CMakeFiles/sched_attr.dir/src/test/sched_attr.c.o
[  9%] Linking C executable bin/crash
[  9%] Built target acct
[ 12%] Built target brotli
[ 12%] Built target ioctl_br
Scanning dependencies of target mmap_write_complex
Scanning dependencies of target exec_self
[ 12%] Built target rrpage
[ 12%] Building C object CMakeFiles/mmap_write_complex.dir/src/test/mmap_write_complex.c.o
[ 12%] Building C object CMakeFiles/exec_self.dir/src/test/exec_self.c.o
Scanning dependencies of target fcntl_sig
[ 12%] Built target crash
[ 13%] Building C object CMakeFiles/fcntl_sig.dir/src/test/fcntl_sig.c.o
[ 13%] Built target rraudit
[ 13%] Linking C executable bin/prctl
Scanning dependencies of target pid_ns_segv
[ 13%] Building C object CMakeFiles/pid_ns_segv.dir/src/test/pid_ns_segv.c.o
[ 13%] Linking C executable bin/intr_ptrace_decline
[ 13%] Built target prctl
Scanning dependencies of target vsyscall_reverse_next
[ 13%] Linking C executable bin/arch_prctl
[ 13%] Linking C executable bin/sched_attr
[ 13%] Building C object CMakeFiles/vsyscall_reverse_next.dir/src/test/vsyscall_reverse_next.c.o
[ 13%] Built target intr_ptrace_decline
[ 13%] Linking C executable bin/exec_self
[ 13%] Built target arch_prctl
Scanning dependencies of target invalid_ioctl
Scanning dependencies of target sigrt
[ 13%] Built target sched_attr
[ 13%] Linking C executable bin/fcntl_sig
[ 14%] Linking C executable bin/mmap_write_complex
[ 14%] Building C object CMakeFiles/invalid_ioctl.dir/src/test/invalid_ioctl.c.o
Scanning dependencies of target scratch_read
[ 14%] Building C object CMakeFiles/sigrt.dir/src/test/sigrt.c.o
[ 15%] Building C object CMakeFiles/scratch_read.dir/src/test/scratch_read.c.o
[ 15%] Built target exec_self
Scanning dependencies of target exec_no_env
[ 15%] Built target mmap_write_complex
[ 15%] Linking C executable bin/pid_ns_segv
[ 15%] Built target fcntl_sig
Scanning dependencies of target read_big_struct
[ 16%] Building C object CMakeFiles/exec_no_env.dir/src/test/exec_no_env.c.o
Scanning dependencies of target alarm
[ 16%] Building C object CMakeFiles/read_big_struct.dir/src/test/read_big_struct.c.o
[ 16%] Building C object CMakeFiles/alarm.dir/src/test/alarm.c.o
[ 16%] Linking C executable bin/vsyscall_reverse_next
[ 16%] Built target pid_ns_segv
Scanning dependencies of target getpwnam
[ 16%] Building C object CMakeFiles/getpwnam.dir/src/test/getpwnam.c.o
[ 16%] Linking C executable bin/invalid_ioctl
[ 16%] Built target vsyscall_reverse_next
[ 16%] Linking C executable bin/sigrt
[ 16%] Linking C executable bin/scratch_read
Scanning dependencies of target alsa_ioctl
[ 16%] Building C object CMakeFiles/alsa_ioctl.dir/src/test/alsa_ioctl.c.o
[ 16%] Built target invalid_ioctl
[ 16%] Built target sigrt
[ 16%] Linking C executable bin/exec_no_env
Scanning dependencies of target async_segv_ignored
Scanning dependencies of target stack_growth
[ 16%] Built target scratch_read
Scanning dependencies of target ptrace_singlestep
[ 16%] Linking C executable bin/read_big_struct
[ 16%] Building C object CMakeFiles/async_segv_ignored.dir/src/test/async_segv_ignored.c.o
[ 16%] Building C object CMakeFiles/stack_growth.dir/src/test/stack_growth.c.o
[ 16%] Linking C executable bin/alarm
[ 16%] Building C object CMakeFiles/ptrace_singlestep.dir/src/test/ptrace_singlestep.c.o
[ 16%] Built target exec_no_env
[ 16%] Built target read_big_struct
[ 16%] Linking C executable bin/getpwnam
Scanning dependencies of target detach_huge_mmap
[ 16%] Built target alarm
Scanning dependencies of target execve_loop
Scanning dependencies of target stack_overflow_altstack
[ 16%] Building C object CMakeFiles/detach_huge_mmap.dir/src/test/detach_huge_mmap.c.o
[ 16%] Building C object CMakeFiles/execve_loop.dir/src/test/execve_loop.c.o
[ 16%] Building C object CMakeFiles/stack_overflow_altstack.dir/src/test/stack_overflow_altstack.c.o
[ 16%] Built target getpwnam
[ 16%] Linking C executable bin/alsa_ioctl
Scanning dependencies of target prctl_deathsig
[ 16%] Building C object CMakeFiles/prctl_deathsig.dir/src/test/prctl_deathsig.c.o
[ 16%] Linking C executable bin/async_segv_ignored
[ 16%] Built target alsa_ioctl
Scanning dependencies of target setitimer
[ 16%] Linking C executable bin/stack_growth
[ 16%] Building C object CMakeFiles/setitimer.dir/src/test/setitimer.c.o
[ 16%] Linking C executable bin/ptrace_singlestep
[ 16%] Built target async_segv_ignored
[ 16%] Built target stack_growth
Scanning dependencies of target watchpoint_size_change
[ 16%] Linking C executable bin/execve_loop
Scanning dependencies of target threaded_syscall_spam
[ 16%] Building C object CMakeFiles/watchpoint_size_change.dir/src/test/watchpoint_size_change.c.o
[ 16%] Linking C executable bin/detach_huge_mmap
[ 16%] Built target ptrace_singlestep
[ 16%] Linking C executable bin/stack_overflow_altstack
Scanning dependencies of target netlink_mmap_disable
[ 16%] Building C object CMakeFiles/threaded_syscall_spam.dir/src/test/threaded_syscall_spam.c.o
[ 16%] Building C object CMakeFiles/netlink_mmap_disable.dir/src/test/netlink_mmap_disable.c.o
[ 16%] Built target execve_loop
[ 16%] Linking C executable bin/prctl_deathsig
Scanning dependencies of target mmap_write_private
[ 16%] Built target detach_huge_mmap
[ 16%] Built target stack_overflow_altstack
[ 16%] Building C object CMakeFiles/mmap_write_private.dir/src/test/mmap_write_private.c.o
Scanning dependencies of target ioctl
Scanning dependencies of target msg_trunc
[ 16%] Building C object CMakeFiles/msg_trunc.dir/src/test/msg_trunc.c.o
[ 16%] Building C object CMakeFiles/ioctl.dir/src/test/ioctl.c.o
[ 16%] Linking C executable bin/setitimer
[ 16%] Built target prctl_deathsig
Scanning dependencies of target int3
[ 16%] Building C object CMakeFiles/int3.dir/src/test/int3.c.o
[ 16%] Linking C executable bin/watchpoint_size_change
[ 16%] Built target setitimer
Scanning dependencies of target fork_stress
[ 16%] Linking C executable bin/threaded_syscall_spam
[ 16%] Building C object CMakeFiles/fork_stress.dir/src/test/fork_stress.c.o
[ 16%] Linking C executable bin/netlink_mmap_disable
[ 16%] Built target watchpoint_size_change
Scanning dependencies of target _llseek
[ 17%] Building C object CMakeFiles/_llseek.dir/src/test/_llseek.c.o
[ 17%] Built target threaded_syscall_spam
[ 17%] Linking C executable bin/mmap_write_private
Scanning dependencies of target sigill
[ 17%] Built target netlink_mmap_disable
[ 17%] Building C object CMakeFiles/sigill.dir/src/test/sigill.c.o
Scanning dependencies of target sysconf
[ 17%] Linking C executable bin/ioctl
[ 17%] Building C object CMakeFiles/sysconf.dir/src/test/sysconf.c.o
[ 17%] Built target mmap_write_private
Scanning dependencies of target bad_syscall
[ 17%] Building C object CMakeFiles/bad_syscall.dir/src/test/bad_syscall.c.o
[ 17%] Linking C executable bin/msg_trunc
[ 17%] Built target ioctl
[ 17%] Linking C executable bin/int3
[ 17%] Linking C executable bin/fork_stress
[ 18%] Built target rrpreload
[ 18%] Built target msg_trunc
[ 18%] Built target seccomp_signals
[ 18%] Built target int3
[ 18%] Linking C executable bin/_llseek
[ 18%] Built target fork_stress
[ 18%] Built target mmap_ro
[ 18%] Built target nanosleep
[ 19%] Built target wait_for_all
[ 19%] Linking C executable bin/sigill
[ 19%] Built target block
[ 19%] Built target big_buffers
[ 19%] Built target mmap_private
[ 19%] Built target futex_exit_race_sigsegv
[ 19%] Linking C executable bin/sysconf
[ 19%] Built target _llseek
[ 19%] Built target mmap_recycle
[ 20%] Built target elapsed_time
[ 20%] Built target watchpoint_no_progress
[ 20%] Built target search
[ 20%] Built target cont_race
[ 21%] Built target save_data_fd
[ 21%] Built target sigill
[ 21%] Linking C executable bin/bad_syscall
[ 22%] Built target clone_cleartid_coredump
[ 22%] Built target block_open
[ 22%] Built target rr_exec_stub
[ 22%] Built target mmap_shared_grow
[ 23%] Built target checkpoint_dying_threads
[ 23%] Built target exec_many
[ 23%] Built target sysconf
[ 23%] Built target remove_latest_trace
[ 23%] Built target io_uring
[ 23%] Built target sigprocmask_evil
[ 23%] Built target unexpected_exit_execve_twice
[ 24%] Built target detach_state
[ 24%] Built target membarrier
Scanning dependencies of target big_select
[ 24%] Building C object CMakeFiles/openat2.dir/src/test/openat2.c.o
Scanning dependencies of target kcmp
[ 24%] Built target bad_syscall
Scanning dependencies of target daemon
Scanning dependencies of target detach_threads
[ 24%] Built target wait_sigstop
Scanning dependencies of target fcntl_owner_ex
Scanning dependencies of target aio
[ 24%] Building C object CMakeFiles/kcmp.dir/src/test/kcmp.c.o
[ 24%] Building C object CMakeFiles/big_select.dir/src/test/big_select.c.o
Scanning dependencies of target sigchld_interrupt_signal
[ 24%] Building C object CMakeFiles/daemon.dir/src/test/daemon.c.o
[ 24%] Building C object CMakeFiles/detach_threads.dir/src/test/detach_threads.c.o
[ 24%] Building C object CMakeFiles/fcntl_owner_ex.dir/src/test/fcntl_owner_ex.c.o
[ 24%] Building C object CMakeFiles/aio.dir/src/test/aio.c.o
[ 25%] Building C object CMakeFiles/sigchld_interrupt_signal.dir/src/test/sigchld_interrupt_signal.c.o
/media/nvidia/external_drive/rr/src/test/openat2.c:6:10: fatal error: linux/openat2.h: No such file or directory
    6 | #include <linux/openat2.h>  /* Definition of RESOLVE_* constants */
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/openat2.dir/build.make:63: CMakeFiles/openat2.dir/src/test/openat2.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:8609: CMakeFiles/openat2.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 25%] Linking C executable bin/daemon
[ 25%] Linking C executable bin/kcmp
[ 25%] Linking C executable bin/detach_threads
[ 26%] Linking C executable bin/aio
[ 26%] Linking C executable bin/fcntl_owner_ex
[ 26%] Linking C executable bin/big_select
[ 26%] Linking C executable bin/sigchld_interrupt_signal
[ 26%] Built target daemon
[ 26%] Built target kcmp
[ 26%] Built target detach_threads
[ 26%] Built target fcntl_owner_ex
[ 26%] Built target aio
[ 26%] Built target big_select
[ 26%] Built target sigchld_interrupt_signal

**Comment by multun** [comment]
@MadhuriPatil1694 can you try this out? https://github.com/rr-debugger/rr/pull/3657
