### ISSUE TITLE
Does rr support ARM cortex-A55 CPU?

### ISSUE THREAD

**Issue by zhongweiy** [rr-debugger/rr#3664]
Hi, there,

Cortex-A55 has atomics instructions like CAS etc. So does rr support this mico-arch? I got rr built on a platform with 4 core Cortex-A55. But runs into issue like:
```
./build/bin/rr record ls
[FATAL src/PerfCounters.cc:460:get_pmu_microarchs()] No supported microarchitectures found.
```

And the related cpuinfo:
```
processor	: 3
model name	: ARMv8 Processor rev 0 (v8l)
BogoMIPS	: 48.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0xd05
CPU revision	: 0
```

**Comment by yuyichao** [comment]
See the top comment at https://github.com/rr-debugger/rr/pull/3265

**Comment by zhongweiy** [comment]
Got it, thanks!

**Comment by zhongweiy** [comment]
@yuyichao , I notice the comment about A55 in the code. I'm on SoC has only 4 A-55 cores and does not have big cores. I wonder whether the result can be different. May I know what kind of testing I can do to verify whether there is reliable PMU event for rr's record and replay?
```
  // cortex-a55, cortex-a75 and neoverse-e1 counts uarch ISB
  // as retired branches so the BR_RETIRED counter is not reliable.
  // There are some counters that are somewhat more reliable than
  // the total branch count (0x21) including
  // 0x0D (BR_IMMED_RETIRED) 0x0E (BR_RETURN_RETIRED)
  // 0xCD (BR_INDIRECT_ADDR_PRED) 0x76 (PC_WRITE_SPEC)
  // 0x78 (BR_IMMED_SPEC), 0xC9 (BR_COND_PRED)
  // 0xCD (BR_INDIRECT_ADDR_PRED)
  // but according to tests on the LITTLE core on a snapdragon 865
  // none of them (including the sums) seems to be useful/reliable enough.
```

**Comment by yuyichao** [comment]
> Do you know what is "micro architectural ISB"?

AFAICT this means whenever the CPU core decide it's appropriate to issue an ISB. The tests I did that showed the count instability had no explicit ISB instructions in them.

> It is a pity a55 is not supported. There are some nice single board computers available on the market with this core.

I agree. Their performance is a bit too low for my own need but I can see why it would've been a good target to support.

**Comment by zhongweiy** [comment]
It's helpful, thanks again!
