### ISSUE TITLE
openat test leads to undeclared SYS_openat2

### ISSUE THREAD

**Issue by GitMensch** [rr-debugger/rr#3665]
dea5bc6105629ac266ef2babab67916fd489379a by @multun added openat2 support.
The code [does handle the case of undefined `SYS_openat2`](https://github.com/rr-debugger/rr/commit/dea5bc6105629ac266ef2babab67916fd489379a#diff-5494fc68fbbc792a4858284854e0111ef12c0f701e3d84112842720bcfc89a55R2525), but while the test [handles the missing syscall](https://github.com/rr-debugger/rr/commit/dea5bc6105629ac266ef2babab67916fd489379a#diff-f51ca5be53de4876116d3db798aec0ba07b72bc0c9fe713d00829dc51f339634R32-R37), it doesn't handle the missing definition.

**Comment by rocallahan** [comment]
Fixed n 98991b97400c451df0ddb8533e55f1b0208c89f8

**Comment by GitMensch** [comment]
Shouldn't this be done for SYS_openat2 in https://github.com/rr-debugger/rr/blob/master/src/preload/syscallbuf.c, too?

**Comment by rocallahan** [comment]
That would be a slight improvement, but it's not that important. If your system headers don't include `SYS_openat2` then your kernel probably doesn't support it and applications using it will probably get `ENOSYS`, so they shouldn't call it a lot. If this code is omitted from syscallbuf, everything still works but `openat2` will be slower.

**Comment by GitMensch** [comment]
I understand that there's no urgent need to adjust this, it's just "monkey see, monkey do" - this PR would have used the RR constants if the main source, which was adjusted exactly for the same reason, would use those...
