### ISSUE TITLE
LICENSE / Copyright adjustments needed (Pernesco, contributors?)

### ISSUE THREAD

**Issue by GitMensch** [rr-debugger/rr#3671]
When adding rr to the free software directory, I've seen that the [LICENSE file](https://raw.githubusercontent.com/rr-debugger/rr/master/LICENSE) has

> Copyright (c) 2013 Mozilla Foundation
Copyright 2015 VMware, Inc
Copyright 2015 Google Inc.

and 

> Contributors: Albert Noll <noll.albert@gmail.com>, Thomas Anderegg <thomas@tanderegg.com>, Nimrod Partush <nimrodpar@gmail.com> Andrew Walton <awalton@vmware.com>

and `rr -version` only outputs a version number.

I think that the copyright year should be adjusted and the contributors possibly should be moved out to a CONTRIBUTORS file, but most likely be extended.

That likely would be a task for @rocallahan.

**Comment by khuey** [comment]
I vaguely recall that back at Mozilla there was a company wide decision from legal that advancing copyright dates was unnecessary and we should just skip it.

**Comment by GitMensch** [comment]
Apart from the copyright dates, the copyright owner also needs an adjustment. I'd suggest to either have the copyright dates up to date or otherwise go with either "not specifying the year" or "specifying the first year only", or go with the "never change again version": check which dates apply to the old copyright owners (may be fine as is) and add another one with Pernesco stating the first year and something like "since".

... or go with what seems to be the Mozilla way - drop the Copyright completely, just specifying the license.

**Comment by rocallahan** [comment]
I don't think we need to do anything here. Changing the LICENSE file is all risk and no benefit.
