### ISSUE TITLE
`rr replay -g` and `run <event>` don't agree with `when`

### ISSUE THREAD

**Issue by rocallahan** [rr-debugger/rr#3674]
Generally when you `rr replay -g <N>`, `when` reports N+1. Sometimes it reports N+2. The latter happens when event N+1 is a `SYSCALLBUF_FLUSH`. I think both cases should be treated as bugs; it's confusing for `when` to disagree with what was requested.

**Comment by rocallahan** [comment]
From `target_eventReached`:
```
return timeline.current_session().current_trace_frame().time() > target.event;
```
The intent was that `replay -g <N>` should complete the execution of event N and apply its effects. OTOH `when` reports the current event that we're executing up to. So the question is, do we change the behavior of `-g` or do we change the behavior of `when`?

**Comment by rocallahan** [comment]
Another thing we want is that when `rr replay -M` emits an event timestamp for an output line, `rr replay -g` to that timestamp should drop you at the exact point that line was emitted (i.e. the `write` syscall). Currently -M reports the syscall entry event, so if we leave that unchanged, we really do what `rr replay -g` to continue to replay all the way to the end of the specified event.

So I'm leaning towards changing `when` to report the number of the last event that was fully replayed, i.e. its effects were applied.

**Comment by khuey** [comment]
> So I'm leaning towards changing when to report the number of the last event that was fully replayed, i.e. its effects were applied.

👍
