### ISSUE TITLE
Failing tests on on i5-12500?

### ISSUE THREAD

**Issue by Manouchehri** [rr-debugger/rr#3677]
Is it "normal"/expected to have these tests failing? (Possibly related to #3338, probably not though.) I'm using a i5-12500 (Alder Lake) at the moment.

## Failing tests
```
The following tests FAILED:
        218 - futex_restart_race (Failed)
        219 - futex_restart_race-no-syscallbuf (Failed)
        489 - pid_ns_shutdown-no-syscallbuf (Failed)
        760 - sioc (Failed)
        761 - sioc-no-syscallbuf (Failed)
        962 - chaos_oom (Failed)
        963 - chaos_oom-no-syscallbuf (Failed)
        1488 - vfork_done_clone (Failed)
        2262 - sioc-32 (Failed)
        2263 - sioc-32-no-syscallbuf (Failed)
        2454 - breakpoint-32 (Failed)
        2455 - breakpoint-32-no-syscallbuf (Failed)
        2720 - target_process-32 (Failed)
        2721 - target_process-32-no-syscallbuf (Failed)
        2816 - breakpoint_consistent-32 (Failed)
        2817 - breakpoint_consistent-32-no-syscallbuf (Failed)
```

### Kernel version:
```
Linux re 6.7.0-060700-generic #202401072033 SMP PREEMPT_DYNAMIC Sun Jan  7 20:43:59 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

### rr version (fa33606fe951575be823f2aa9b9211fac63d309c):
```
rr version 5.7.0
```

### `lscpu`
```
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Address sizes:                      46 bits physical, 48 bits virtual
Byte Order:                         Little Endian
CPU(s):                             12
On-line CPU(s) list:                0-11
Vendor ID:                          GenuineIntel
Model name:                         12th Gen Intel(R) Core(TM) i5-12500
CPU family:                         6
Model:                              151
Thread(s) per core:                 2
Core(s) per socket:                 6
Socket(s):                          1
Stepping:                           5
CPU max MHz:                        4600.0000
CPU min MHz:                        800.0000
BogoMIPS:                           5990.40
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves split_lock_detect user_shstk avx_vnni dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req hfi vnmi umip pku ospke waitpkg gfni vaes vpclmulqdq tme rdpid movdiri movdir64b fsrm md_clear serialize pconfig arch_lbr ibt flush_l1d arch_capabilities
Virtualization:                     VT-x
L1d cache:                          288 KiB (6 instances)
L1i cache:                          192 KiB (6 instances)
L2 cache:                           7.5 MiB (6 instances)
L3 cache:                           18 MiB (1 instance)
NUMA node(s):                       1
NUMA node0 CPU(s):                  0-11
```

**Comment by rocallahan** [comment]
Can you supply the verbose failure log?

**Comment by rocallahan** [comment]
None of those look particularly worrying but on Alder Lake I'd expect everything to pass.

**Comment by Manouchehri** [comment]
Absolutely! What command should I run to get the verbose logs for you?

**Comment by rocallahan** [comment]
I run this:
```
(cd ~/rr/obj; ctest -j8 --verbose >& ~/tmp/output)
```

**Comment by Manouchehri** [comment]
See attached.
[output.for.roc.1.txt](https://github.com/rr-debugger/rr/files/13924047/output.for.roc.1.txt)

Thanks!

**Comment by rocallahan** [comment]
Did you build with clang?

**Comment by Manouchehri** [comment]
Yep!

**Comment by Manouchehri** [comment]
```
Ubuntu clang version 14.0.0-1ubuntu1.1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by rocallahan** [comment]
5c29fee9b9fa7f4669d3d3d5e6f12dc774ca915e should fix `futex_restart_race`.

**Comment by Manouchehri** [comment]
Thanks!

What distro and compiler do you usually use for rr? Going forward, I want to stick to as close to your setup as possible to avoid running into untested terrority. =)

**Comment by rocallahan** [comment]
We usually build with gcc. Ubuntu and Fedora are both well-supported. But clang builds work too and I'm enthusiastic about making sure clang builds work 100%.

I think all these test failures are likely to be minor issues that shouldn't affect real-world usage. But I would like to fix them anyway.

**Comment by Manouchehri** [comment]
[output.for.roc.2.txt](https://github.com/rr-debugger/rr/files/13924293/output.for.roc.2.txt)

^ Updated results from 5c29fee9b9fa7f4669d3d3d5e6f12dc774ca915e :)

**Comment by rocallahan** [comment]
3bbff9ac703ff4e4b633726c79b37d8820c43687 fixes that `sioc` failure.

**Comment by rocallahan** [comment]
50b60864cd883382fcc9f36fa7e70cbdc256654c will help debug the `chaos_oom` failure.

**Comment by rocallahan** [comment]
ddecac831151bc950dcbfe0b023979c49bbb7b2d seems like a reasonable fix for the `cont_race` failure.

**Comment by rocallahan** [comment]
27d09d831f6effa5b28af046ff3bffbfaccb8fdc should fix the `breakpoint(_consistent)`/`target_process` 32-bit tests.

**Comment by rocallahan** [comment]
`pid_ns_shutdown-no-syscallbuf` and `vfork_done` failed in the first run but not in the second, so they're intermittent. That's annoying but unlikely to cause you any problems. They're hell to debug so I'll look for them next time I'm preparing an rr release.

I think the only remaining easy to reproduce failure on your system is `chaos_oom`. Happy to dig into that with your help, but honestly it's probably not worth your time.

**Comment by Manouchehri** [comment]
[output.for.roc.4.txt](https://github.com/rr-debugger/rr/files/13924694/output.for.roc.4.txt)

Here's my last run with 27d09d831f6effa5b28af046ff3bffbfaccb8fdc. =)

**Comment by rocallahan** [comment]
Can you dump `rr traceinfo /tmp/rr-test-chaos_oom-KRMuEurDy/latest-trace | grep exclusionRange`?

**Comment by Manouchehri** [comment]
```
dave@rr /tmp/obj # ./bin/rr traceinfo /tmp/rr-test-chaos_oom-KRMuEurDy/latest-trace | grep exclusionRange
  "exclusionRange": { "start": 106653407043584, "end": 111051453554688 },
```

**Comment by rocallahan** [comment]
`rr dump -b -m -p /tmp/rr-test-chaos_oom-KRMuEurDy/latest-trace`? This will be a file you'll want to attach somewhere.

**Comment by Manouchehri** [comment]
https://paste.rs/fJ6P0

**Comment by rocallahan** [comment]
Thanks. I don't have any ideas about this one. Let's just forget about it for now.

**Comment by Manouchehri** [comment]
Sounds good, thanks!
