### ISSUE TITLE
Can't single step into a function that's in a shared library

### ISSUE THREAD

**Issue by abbeyj** [rr-debugger/rr#3695]
When trying to single step into a function that's in a shared library, rr instead runs the entire rest of the program and doesn't stop until it exits.  STR:

```
$ cat my_lib.cpp
#include <stdio.h>

void my_lib_function() {
    printf("my_lib_function()\n");
}
```

```
$ cat my_main.cpp
#include <stdio.h>

void my_lib_function();

int main(int argc, char **argv) {
    my_lib_function();
    printf("B\n");
    printf("C\n");
    return 0;
}
```

```
$ g++ -g -fPIC -shared my_lib.cpp -o libmy_lib.so
$ g++ -g -fPIC my_main.cpp -o my_main -L$PWD -Wl,-rpath,$PWD -lmy_lib
$ rr record -n ./my_main
rr: Saving execution to trace directory `<snip>/.local/share/rr/my_main-1'.
my_lib_function()
B
C

$ rr replay
<snip>
0x00007f7b5f141cb0 in _start () from /lib64/ld-linux-x86-64.so.2
(rr) break main
Breakpoint 1 at 0x4006b5: file my_main.cpp, line 6.
(rr) cont
Continuing.

Breakpoint 1, main (argc=1, argv=0x7ffca0a8e0e8) at my_main.cpp:6
6           my_lib_function();
(rr) step
my_lib_function()
B
C

Program received signal SIGKILL, Killed.
0x00007f7b5e085bb6 in _exit () from /lib64/libc.so.6
```

I expected to end up stopped at my_lib.cpp:4.  This used to work properly in v5.3.0.  It looks like this instead:

```
<snip>
Breakpoint 1, main (argc=1, argv=0x7fff3c2be928) at my_main.cpp:6
6           my_lib_function();
(rr) step
my_lib_function () at my_lib.cpp:4
4           printf("my_lib_function()\n");
```

Bisecting indicates commit 8a3955edacacb3d7c54a3d80e87de77c3bf6d522 as the culprit.  This has some logging so I reran things with `RR_LOG=Monkeypatcher:debug`.  In v5.3.0 where stepping works as expected, I get:

```
[Monkeypatcher] monkeypatched __vdso_clock_gettime to syscall 228 at 0x7ffd47be0ad0 (0xad0)
[Monkeypatcher] monkeypatched __vdso_gettimeofday to syscall 96 at 0x7ffd47be0880 (0x880)
[Monkeypatcher] monkeypatched __vdso_time to syscall 201 at 0x7ffd47be0aa0 (0xaa0)
[Monkeypatcher] monkeypatched __vdso_getcpu to syscall 309 at 0x7ffd47be0df0 (0xdf0)
[WARN patch_dl_runtime_resolve()] _dl_runtime_resolve implementation doesn't look right
[WARN patch_dl_runtime_resolve()] _dl_runtime_resolve implementation doesn't look right
[WARN patch_dl_runtime_resolve()] _dl_runtime_resolve implementation doesn't look right
```

With latest git master (commit 5722778a471e03516b5c3bcdc601404628fac54e) where trying to step runs to the end of the program, I get:

```
[Monkeypatcher] Starts with endbr, skipping
[Monkeypatcher] Starts with endbr, skipping
[Monkeypatcher] Starts with endbr, skipping
```

It appears that the patching for `_dl_runtime_resolve_fxsave`, `_dl_runtime_resolve_xsave`, and `_dl_runtime_resolve_xsavec` was failing but that this was ignored and single stepping worked.  After 8a3955edacacb3d7c54a3d80e87de77c3bf6d522 the patching now works as intended but this has the unfortunate effect of breaking single stepping.  The actual problem is possibly somewhere in the commit that originally introduced the patching for these functions: e67e83c219139e68f66aedf4205a5d0d5fad8637 .

I'm running AlmaLinux 8 on an Intel Xeon 6240R with glibc-2.28-236.el8.7.x86_64.

**Comment by rocallahan** [comment]
Not sure what's going on here. gdb behaves strangely: it steps over the function call we inject into the start of `_dl_runtime_resolve_xsavec`, and then does a `continue` which keeps going to program exit. In the passing case where we don't patch `_dl_runtime_resolve_xsavec`, gdb single-steps all the way through that function and its callees until it `_dl_runtime_resolve_xsavec` tail-calls the resolved function. I think maybe gdb has special handling for this and we're breaking its heuristics. Time to read some gdb code.

**Comment by rocallahan** [comment]
Yeah, so gdb does this: https://github.com/bminor/binutils-gdb/blob/97f2a34ed1d255ea301f858b31c0fbe75da1c4f6/gdb/infrun.c#L7684C1-L7688C54
```
  /* If we are stepping at the source level and entered the runtime
     loader dynamic symbol resolution code...

     EXEC_FORWARD: we keep on single stepping until we exit the run
     time loader code and reach the callee's address.
```
but it only keeps stepping while `in_solib_dynsym_resolve_code()` returns true:
```
svr4_in_dynsym_resolve_code (CORE_ADDR pc)
{
  struct svr4_info *info = get_svr4_info (current_program_space);

  return ((pc >= info->interp_text_sect_low
           && pc < info->interp_text_sect_high)
          || (pc >= info->interp_plt_sect_low
              && pc < info->interp_plt_sect_high)
          || in_plt_section (pc)
          || in_gnu_ifunc_stub (pc));
}
```
and our patched code is outside those ranges :-(.

**Comment by rocallahan** [comment]
I don't like it, but the best fix I can think of so far is, if gdb issues a single-step command at the call to our `X64DLRuntimeResolvePrelude` helper function, step over instead of step into.

**Comment by rocallahan** [comment]
One problem with that is that we don't store in the trace currently why we monkeypatched code.

**Comment by khuey** [comment]
Is this only an issue for the resolver patch? If so, can we create a PLT section in librrpage.so with enough available space to stick that resolver function in and drop the patch in there instead of the usual place?

**Comment by rocallahan** [comment]
That's a great idea! Generally the code we need to patch won't be within 2GB of the rr page, but I suppose we can load the address into RAX and do an indirect call.

**Comment by rocallahan** [comment]
Actually we're OK because the rr page addresses fit into 32 bits so we can do something like
```
0:  b8 34 12 00 70          mov    eax,0x70001234
5:  ff d0                   call   rax 
```

**Comment by rocallahan** [comment]
This breaks the `tracee_unmap_vdso` locally for me, but not on CI. The `fork()` syscall triggers a `_dl_runtime_resolve_xsavec()` which we have patched to call into the VDSO, which has been unmapped.

Probably we should try to unpatch `_dl_runtime_resolve*` when our VDSO is unmapped.
