### ISSUE TITLE
ioctl function cannot record

### ISSUE THREAD

**Issue by likui1123** [rr-debugger/rr#3700]
<img width="829" alt="rr" src="https://github.com/rr-debugger/rr/assets/37236882/72b34170-4bcc-4756-b14c-5c97716e5154">
I want to record my program, but my program has a call to the ioctl function, which cannot be deleted. Is there any parameter during the recording process that can avoid the problem in the diagram? Thank you

**Comment by khuey** [comment]
Do you know what ioctl this is?

**Comment by likui1123** [comment]
> Do you know what ioctl this is?

In my program, ioctl mainly interacts with kernel mode

**Comment by khuey** [comment]
Yes, all ioctls interact with the kernel. That's the point of an ioctl.

Without knowing anything about this ioctl there's nothing we can do to support it.

**Comment by likui1123** [comment]
> Yes, all ioctls interact with the kernel. That's the point of an ioctl.
> 
> Without knowing anything about this ioctl there's nothing we can do to support it.

very sad，This programis quite large, and many of them are from others. Is there a quick way to avoid this problem? I want to use rr record to locate the problem of randomly stepping on memory，I found that my problem is very similar to the issue 3495 （https://github.com/rr-debugger/rr/issues/3495） phenomenon，thanks

**Comment by likui1123** [comment]
> Yes, all ioctls interact with the kernel. That's the point of an ioctl.
> 
> Without knowing anything about this ioctl there's nothing we can do to support it.

excuse me，Can I ignore all system calls? I don't care about system calls

**Comment by khuey** [comment]
rr needs to understand the semantics of syscalls to replay the inputs to the program during replay.
