### ISSUE TITLE
A simple feeling about using rr record for ioctl

### ISSUE THREAD

**Issue by likui1123** [rr-debugger/rr#3703]
After reviewing the source code, rr can only pass a fixed request through the switch case for the ioctl (fd, request,...) function. Users may customize some requests, and for custom requests, rr will asset and expect EINVAL. Can you provide a function to globally disable non-existent requests? Otherwise, rr will not be able to use it

source code：
 switch (request) {
    case 0xc020462a: // Nvidia driver ioctl
      syscall_state.emulate_result(-ENOTTY);
      return PREVENT_SWITCH;

    case SIOCETHTOOL:
      prepare_ethtool_ioctl<Arch>(t, syscall_state);
      return PREVENT_SWITCH;

    case SIOCGIFCONF: {
      auto ifconfp =
          syscall_state.reg_parameter<typename Arch::ifconf>(3, IN_OUT);
      syscall_state.mem_ptr_parameter(
          REMOTE_PTR_FIELD(ifconfp, ifc_ifcu.ifcu_buf),
          ParamSize::from_initialized_mem(t,
                                          REMOTE_PTR_FIELD(ifconfp, ifc_len)));
      syscall_state.after_syscall_action(record_page_below_stack_ptr);
      return PREVENT_SWITCH;
    }
my request
![image](https://github.com/rr-debugger/rr/assets/37236882/81f2ef11-11c9-4561-ad54-548e86f1cef4)

**Comment by likui1123** [comment]
rdma_get_devices_dlsym function  will call ioctl, and rr cannot record it

**Comment by khuey** [comment]
What is OFS_KHELPER_IOCTL_CMD from? I can't find that on Google.

rr cannot in general ignore unknown ioctls. Any ioctl that modifies memory in the program needs to be understood and those memory modifications must be recorded. You could patch rr to allow unknown ioctls but if any of them modify memory your program won't replay correctly.

**Comment by likui1123** [comment]
> What is OFS_KHELPER_IOCTL_CMD from? I can't find that on Google.
> 
> rr cannot in general ignore unknown ioctls. Any ioctl that modifies memory in the program needs to be understood and those memory modifications must be recorded. You could patch rr to allow unknown ioctls but if any of them modify memory your program won't replay correctly.

very thanks，OFS_KHELPER_IOCTL_CMD is not a standard definition, it is just my custom request. There are over 100 similar requests  and they will modify memory, so in this program , rr cannot be used directly。By the way, I would like to ask if there are any methods for record and replay this program without modifying the source code

**Comment by khuey** [comment]
If you modify userspace memory simply disabling the rr assertion about unknown ioctls is not sufficient. If you do not capture those memory modifications for replay then rr replay will diverge. You could patch rr to always return ENOSYS for your custom ioctls, or you could actually implement support for your custom ioctls. Neither of those are things we would take upstream.
