### ISSUE TITLE
CPU type unknown on Ryzen 7 7840U

### ISSUE THREAD

**Issue by silversquirl** [rr-debugger/rr#3715]
Running `rr record /bin/echo` results in the following error on my laptop:

```
[FATAL /home/ubuntu/rr/src/PerfCounters_x86.h:121:compute_cpu_microarch()] AMD CPU type 0x70f40 (ext family 0xa) unknown
```

I'm guessing rr just needs to add this CPU type to allow it to be correctly recognized.

**Comment by rocallahan** [comment]
Can you try adding it and running the rr tests? The PR would look something like d9e4547a8e94242b62efe684d55c6edc7690c7ea

**Comment by yalfg** [comment]
> Can you try adding it and running the rr tests? The PR would look something like [d9e4547](https://github.com/rr-debugger/rr/commit/d9e4547a8e94242b62efe684d55c6edc7690c7ea)

Actually the commit you pointed to solves the problem already ;) I have a 7840U laptop too and just tried the current top of tree with this commit, it works.

**Comment by silversquirl** [comment]
Seems to be working! Thanks :)
