### ISSUE TITLE
Doing a recording as root

### ISSUE THREAD

**Issue by sj-raima** [rr-debugger/rr#3716]
Background:  We have an application that needs to run with privileges. But the replay should of course be able to run as a normal user.

The workaround I did was as follows:

     $ sudo -EP --preserve-env=HOME rr record script.sh
     $ sudo chown -R $USER.$USER ~/.local/share/rr/latest-trace/.

Unfortunately, the script did use sudo and the result of the second command was that the permission changed for /usr/bin/sudo.  How can I do this safely?  It other words, how can I do a recording as root but have the recording being owned by another user?

Actually, the only thing I need in this case is for pthread_setschedparam to succeed.

**Comment by rocallahan** [comment]
Do `sudo rr pack` between those two steps.

**Comment by sj-raima** [comment]
FYI in case you laded her:

I ended up doing the pack+chown as follows to make it safer (there could be another trace finishing between the pack and the chown):

```
        trace_id=~/.local/share/rr/$(ls -l ~/.local/share/rr/latest-trace | sed 's/.*[ ][-][>][ ]//')
        if sudo rr pack $trace_id; then
            sudo chown -R $USER.$USER $trace_id
        else
            echo Failed to pack $trace_id
        fi
```
