### ISSUE TITLE
[RFE] Print tracee's stack when `ASSERT()` fails

### ISSUE THREAD

**Issue by Hi-Angel** [rr-debugger/rr#3749]
I am currently debugging an instance of

```
Assertion `t->regs().syscall_result_signed() == -syscall_state.expect_errno' failed to hold. Expected ENOSYS for 'io_destroy' but got result -22 (errno EINVAL); execution of syscall unsupported by rr
```

and the first thing I struggle with is that I have no idea where exactly `rr` fails. syscalls are typically hidden under 3rdparty libs, in particular I found that the `io_destroy` from this error message [is wrapped over by `io_queue_release`](https://github.com/crossbuild/libaio/blob/5a546a834c36070648158d19dd564762d59f8eb8/src/io_queue_release.c#L26), so I can't grep over the project for `io_destroy`.

I think it would be an immense help if in `ASSERT()` along with the internal trace `rr` would print the debuggee's stack as well.

**Comment by Hi-Angel** [comment]
*(for reference: the assert per se comes from lack of libaio implementation in `rr`, and there is a separate issue for that https://github.com/rr-debugger/rr/issues/3034)*

**Comment by rocallahan** [comment]
If you run rr in the terminal then after the ASSERT failure it should print emergency debugger instructions and then pause. If you follow those instructions, you should be able to get a debuggee stack trace with gdb.
