### ISSUE TITLE
can rr detect the nullptr dereference at int z=*g ?

### ISSUE THREAD

**Issue by navinp0304** [rr-debugger/rr#3750]
Can rr record and replay the detection of nullptr dereference at z=*g ? I tried recording it but replaying it didn't show that .

```
#include<sys/types.h>
#include<unistd.h>
#include<sys/wait.h>
int main()
{
	int i=5;
	int *g=&i;
	if(fork()==0){
		//child
		g=nullptr;
		if(fork()) int z=*g;
		else {
		}
	} else {
		wait(&i);
	}
}

```

**Comment by khuey** [comment]
rr stays with the parent process by default. Use `rr ps` to find the child process you want to debug and `rr replay -f <pid>` to debug that child process instead.
