### ISSUE TITLE
CLion integration: To open a remote debug connection, you need to specify what serial device is attached to the remote system

### ISSUE THREAD

**Issue by khismatullin** [rr-debugger/rr#3782]
1. setup CLion by this doc: 'https://github.com/rr-debugger/rr/wiki/Using-rr-in-an-IDE#setting-up-clion'
2. run server

```sh
rr replay -s 50505 -k
```

3. On CLion run debug throw this error

**Comment by rocallahan** [comment]
I don't get this error. Let's work on this in issue #3783
