### ISSUE TITLE
CLion integration: Invalid option --interpreter=mi2

### ISSUE THREAD

**Issue by khismatullin** [rr-debugger/rr#3783]
rr version: 5.8.0

1. setup CLion by this doc: 'https://github.com/rr-debugger/rr/wiki/Using-rr-in-an-IDE#setting-up-clion'
   1.1. set custom GDB: '/usr/bin/rr'
3. run server

```sh
rr replay -s 50505 -k
```

4. On CLion run debug throw this error

**Comment by rocallahan** [comment]
I don't get this error. I've updated the wiki with what I did that worked.

**Comment by rocallahan** [comment]
In the failing case something weird is going on:
```
[GdbServerConnection] raw request X400318,0:
[GdbServerConnection] debugger setting memory (addr=0x400318, len=0, data=)
[GdbServerConnection] write_flush: '$OK#9a'
[GdbServerConnection] raw request X400318,1c:/lib64/ld-linux-x86-64.so.2
[GdbServerConnection] debugger setting memory (addr=0x400318, len=28, data=2f6c696236342f6c642d6c696e75782d7838362d36342e736f2e3200)
[ERROR src/GdbServer.cc:570:dispatch_debugger_request() errno: EIO] Attempt to write memory outside diversion session
[GdbServerConnection] write_flush: '$E01#a6'
```

**Comment by rocallahan** [comment]
`2f6c696236342f6c642d6c696e75782d7838362d36342e736f2e3200` is `"/lib64/ld-linux-x86-64.so.2"`.

**Comment by rocallahan** [comment]
It's trying to set the ELF `INTERP`. No idea why :-(. I guess in this case it's innocuous since the memory at that location already has that value. I suppose rr could allow setting memory outside a diversion session if it doesn't actually change the memory...
