### ISSUE TITLE
Separate recordings for child processes only?

### ISSUE THREAD

**Issue by agentzh** [rr-debugger/rr#3785]
Hi there, we're trying to record individual worker processes of nginx or apache/httpd servers simultaneously. The worker processes might share some memory via the shm zones which are created in their common parent process. Is there a way to implement a variant of the following `rr record` option that supports discarding the outer recording but still allows the individual recordings of the children to share some memory pages?

```
  --nested=detach            Start a separate recording session.
                             Must not share memory with the outer.
```

Many thanks!

**Comment by agentzh** [comment]
We originally want to attack this limitation via #3698 but it seems much harder as per @rocallahan's reply :)

**Comment by rocallahan** [comment]
> Is there a way to implement a variant of the following `rr record` option that supports discarding the outer recording but still allows the individual recordings of the children to share some memory pages?

No, this won't work.

**Comment by rocallahan** [comment]
When one process reads from a shared memory page, we won't know what the other processes wrote to that page.

**Comment by rocallahan** [comment]
If only a subset of the processes write to the pages (e.g. only one process writes), and you know what those processes are ahead of time, you could detach the read-only processes that you don't care about.
