### ISSUE TITLE
Recording terminated abnormally and the trace is incomplete

### ISSUE THREAD

**Issue by Svalorzen** [rr-debugger/rr#3788]
Hello, I am new to rr, so I apologize in advance if this error is due to some silly mistake I made.

I am trying to use rr to debug a C++ test executable that uses Catch2, using `rr record ./myexe options`. The executable terminates due to an assert failing, with the last line being
```
Trace/breakpoint trap (core dumped)
```
However, when I try to replay the recording using `rr replay`, I get the message
```
rr: Trace file `[...]/incomplete' found.
rr recording terminated abnormally and the trace is incomplete.
```
Looking at the recording folder, all files are empty but for the `incomplete` one which contains the number `85` (I tried 2 recordings and both get the same result). The program to debug is single-threaded, console only, and is not doing anything overly strange as far as I'm aware, and I can debug it normally using `gdb`.

As additional information regarding my installation of `rr`, I am on Lubuntu 22.04. I installed `rr` from the `.deb` package on GitHub. I had to set `kernel.perf_event_paranoid = 1` to `/etc/sysctl.d/10-rr.conf` and loaded the new config using `sysctl -p /etc/sysctl.d/10-rr.conf`. I also have a Zen CPU (Ryzen 9 3950X), and I ran the `zen_workaround.py` script, which reported `Zen workaround in place`. I'm not sure if there's anything else that I am missing. Thanks in advance for the help.

**Comment by Svalorzen** [comment]
As an additional note, I have now tried to end the process prematurely by using `Ctrl-C`, and this results in a valid recording (although it does not reach the place where the assert triggers).

**Comment by Svalorzen** [comment]
I think this is it, I just made a very small test case and it ends up in the same state:
```
int main() {
    ::kill(0, SIGTRAP);

    return 0;
}
```
Can this be bypassed in some way?

**Comment by rocallahan** [comment]
Blocking `SIGTRAP` in rr seems like the best bet. Delivering `SIGTRAP` to all processes in the process group sounds kind of risky to me --- why not just deliver the signal to the current process? --- but it is what it is.
