### ISSUE TITLE
madvise syscall changed in our back breaking firefox sandbox when running under rr

### ISSUE THREAD

**Issue by lissyx** [rr-debugger/rr#3793]
As seen on https://bugzilla.mozilla.org/show_bug.cgi?id=1910387, it looks like since https://github.com/rr-debugger/rr/commit/5b02260ab8b524e6fd936ae6b36ded46a9a0f451#diff-5494fc68fbbc792a4858284854e0111ef12c0f701e3d84112842720bcfc89a55R2347 `madvise()` with `MADV_DONTNEED` will trigger some `madvise` with `MADV_COLD` which our sandbox does not support.

As per Matrix discussion, while we can workaround that in the sandbox, this rr change should not be exposed directly

**Comment by khuey** [comment]
It seems like we either need to modify the tracee seccomp filter to allow the MADV_COLD we trigger from MADV_DONTNEED or we need to hide the MADV_COLD we trigger from the seccomp filter entirely.

**Comment by rocallahan** [comment]
Should be trivial, we just need to make it privileged.

**Comment by lissyx** [comment]
> Should be trivial, we just need to make it privileged.

i can test a patch if you want

**Comment by rocallahan** [comment]
That should work. I haven't written a test, hopefully I'll get around to it :-).

**Comment by lissyx** [comment]
Thanks, I just tested and I can confirm there's no need to tune the sandbox now :)

**Comment by khuey** [comment]
> Should be trivial, we just need to make it privileged.

Ah, right, I totally blanked on us already having infra for that.
