### ISSUE TITLE
Maybe it would be better to check for cpu features (on aarch64) rather than hardcoding list of "known to work" cpus?

### ISSUE THREAD

**Issue by hrw** [rr-debugger/rr#3795]
[PerfCounters_aarch64.h](https://github.com/rr-debugger/rr/tree/master/src/PerfCounters_aarch64.h) checks for "known to work" cpu implementations and quit if there is no match.

Maybe it would be better to check for required features (even by parsing /proc/cpuinfo 'Features' line) rather than keeping such list?

Lists get out of date sooner or later. Compared to [my list of Arm cpu cores](https://gpages.juszkiewicz.com.pl/arm-socs-table/arm-cpu-cores.html) you already miss several entries.

**Comment by rocallahan** [comment]
It's not just a list of "known to work" CPUs, there's also a table of PMU counter IDs that we need to look up: https://github.com/rr-debugger/rr/blob/03f6446a991bc3b1b9d28c1c2df61f277dd96626/src/PerfCounters.cc#L216
We can't get that information out of /proc/cpuinfo.

**Comment by rocallahan** [comment]
And the counters we need are generally non-architectural, i.e. there is no guarantee they stay they same across microarchitectural revisions, although as you can see from our data they generally do. Thus it seems like a good idea to be able to determine which microarchitecture is present and then map that to the counter ID.

**Comment by rocallahan** [comment]
It would be great if there was a database somewhere that we could copy this data from, but we haven't found one yet.

**Comment by hrw** [comment]
Thanks for explaining.
