### ISSUE TITLE
Add support for AMD Ryzen AI 9 HX 370 (Zen 5)

### ISSUE THREAD

**Issue by ngg** [rr-debugger/rr#3853]
I get an `AMD CPU type 0x20f40 (ext family 0xb) unknown` error if I try to run rr.

**Comment by rocallahan** [comment]
Please update to 12be53ddcfe968656e125a36f8c35ff383daa2ea and try it out. It would be great if you can run the rr tests --- see https://github.com/rr-debugger/rr/wiki/Building-And-Installing.

**Comment by ngg** [comment]
Hi! The patch works great. I also tried to run the tests, the first time 12 tests failed, but after re-running the failed tests, there were only 6 failures.

**Comment by rocallahan** [comment]
Sounds good enough.
