### ISSUE TITLE
assembly error on aarch64

### ISSUE THREAD

**Issue by GitMensch** [rr-debugger/rr#3858]
~~~
/tmp/ccDYpY0x.s: Assembler messages:
/tmp/ccDYpY0x.s:302: Error: unknown or missing system register name at operand 2 -- `mrs x0,cntvctss_el0'
/tmp/ccDYpY0x.s:374: Error: unknown or missing system register name at operand 2 -- `mrs xzr,cntvctss_el0'
make[2]: *** [CMakeFiles/arch_timer.dir/build.make:76: CMakeFiles/arch_timer.dir/src/test/arm/arch_timer.c.o] Error 1
~~~

on CPU: 3.0 GHz Ampere® Altra™

~~~
cat /proc/cpuinfo
processor       : 0
BogoMIPS        : 50.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x3
CPU part        : 0xd0c
CPU revision    : 1
~~~

**Comment by rocallahan** [comment]
@pcc How is it possible for some assemblers tonot know about these registers? What can we do about it?

**Comment by yuyichao** [comment]
What version is the binutils? It seems that the support for this is added in 2.38 https://github.com/bminor/binutils-gdb/commit/e9dac4f0125752f64f7fa76ff4208a3b56493a19#diff-be4a91243c8b9717e52a6e5c204e808e48c212b6fdff4d89afd6f63c145a3383

**Comment by yuyichao** [comment]
If it was an old binutils version and if such version is to be supported. One can either just hard code the register number and instruction, (or one can use assembly trick to translate inline assembly name back to number to be manually encoded in the assembly).

**Comment by pcc** [comment]
Yeah, it's probably an old binutils. No need to encode the instruction, we can just encode the system register number, i.e. `s/cntvctss_el0/s3_3_c14_c0_6/g`.

**Comment by GitMensch** [comment]
This was happening with binutils 2.35.2 (RHEL9).

**Comment by GitMensch** [comment]
Thanks, I can confirm that it builds fine now. Sadly nearly all tests fail, I create a new issue for that.
