### ISSUE TITLE
Spurious "Really redefine built-in command" logged on screen

### ISSUE THREAD

**Issue by user202729** [rr-debugger/rr#3859]
Not a bug, but it's mildly annoying.

Currently, when rr starts, these lines are logged

```
Really redefine built-in command "restart"? (y or n) [answered Y; input not from terminal]
Really redefine built-in command "jump"? (y or n) [answered Y; input not from terminal]
```

that's annoying.

It's possible to delete them by setting `set confirm off` before the redefinitions and `set confirm on` afterwards, but then user might be confused if they put `set confirm off` themselves.

Relevant code: https://github.com/rr-debugger/rr/blob/master/src/launch_debugger.cc#L51

A better way may be to use Python:

```
python gdb.execute('''define restart\nrun c$arg0\nend''')
```

Somehow, that suppresses the message.

(we're already using Python later anyway, so it doesn't seem to be an issue.)

**Comment by rocallahan** [comment]
Send a PR?

**Comment by GitMensch** [comment]
So I gave that a try. No local tests at this hour but if the CI passes...
