### ISSUE TITLE
Zen warning breaks -i=mi

### ISSUE THREAD

**Issue by LemonBreezes** [rr-debugger/rr#3889]
![image](https://github.com/user-attachments/assets/9c987325-16a0-4693-a7a2-08913ad2d185)
Basically, what is happening is that the "On Zen CPUs..." warning is not being formatted in the output acceptable to `-i=mi` output so it is breaking the UI. Please make `rr` detect when `-i=mi` is used and format the warning output accordingly.

**Comment by rocallahan** [comment]
Pass `--suppress-environment-warnings` to avoid this problem.
Making these warnings compatible with `-i=mi` is not really feasible or desirable.
