### ISSUE TITLE
rr running under a VM

### ISSUE THREAD

**Issue by navinp0304** [rr-debugger/rr#3892]
Hi,
    i've 2 linux ubuntu 24 vms under Vmware hypervisor and another running on WSL2. Unfortunately Vmware hypervisor workaround for PMU passthrough is not enabled by admin due to performance reasons and security concerns. Currently don't have a KVM vm with PMU enabled.
           When i run under WSL2 on my laptop rr doesn't run. So i tried to comment out all the ASSERT and enable something like https://github.com/rr-debugger/rr/issues/2815#issuecomment-782584935 . But it failed and didn't work like when you replay it says remote connection closed.

So i have 2 questions:

1.  Since when you run under VM like many cloud providers or Vmware where the settings of hypervisor/vmx can't be changed. What all changes are required in rr to support software counters when hardware is not present like PERF_COUNT_SW_CPU_CLOCK . Can we not work with SW clocks and events . This may require host kernel exposing new counters in /proc , /sys, /dev and being passed to guest kernel.

2. Is it really possible or worth exploring the software path ? If possible do we have any wiki that describes how to achieve that .

**Comment by rocallahan** [comment]
We cannot use software events such as `PERF_COUNT_SW_CPU_CLOCK`. Have you read [the paper](https://arxiv.org/abs/1705.05937)?
